### ISSUE TITLE
[Bug]: xattr: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by shdm2d** [PlayCover/PlayCover#1367] opened 2024-01-31 04:32 UTC
### Describe the bug

An error occurs when uploading an ipa file

xattr: [Errno 13] Permission denied: '/var/folders/_h/l4yw4_y176xdh20p3zgtkj9w0000gn/T/TemporaryItems/NSIRD_PlayCover_uUNOja/Payload/GenshinImpact.app/GenshinImpact'
<img width="891" alt="Снимок экрана 2024-01-31 в 06 54 58" src="https://github.com/PlayCover/PlayCover/assets/103522489/0bb817a6-b47c-4219-bbb2-37dd91447510">

### Steps to reproduce

import any ipa file

### Expected behaviour

the application will be installed

### Crash log

```shell
Версия 14.3 (Выпуск 23D56)
Installing PlayTools
Copying PlayTools to Frameworks

xattr: [Errno 13] Permission denied: '/var/folders/_h/l4yw4_y176xdh20p3zgtkj9w0000gn/T/TemporaryItems/NSIRD_PlayCover_do3KSW/Payload/GenshinImpact.app/GenshinImpact'


xattr: [Errno 13] Permission denied: '/var/folders/_h/l4yw4_y176xdh20p3zgtkj9w0000gn/T/TemporaryItems/NSIRD_PlayCover_HfXH58/Payload/GenshinImpact.app/GenshinImpact'


xattr: [Errno 13] Permission denied: '/var/folders/_h/l4yw4_y176xdh20p3zgtkj9w0000gn/T/TemporaryItems/NSIRD_PlayCover_uUNOja/Payload/GenshinImpact.app/GenshinImpact'
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-01-31 04:36
Duplicate of #1349.

**Closed as completed by TheMoonThatRises** 2024-01-31 04:36 UTC
Labels: bug
