### ISSUE TITLE
[Bug]: any app not support OS 14.1 stable

### ISSUE THREAD

**Issue by mo3et** [PlayCover/PlayCover#1181] opened 2023-10-27 04:33 UTC
### Describe the bug

I try to run **honkai star rail** in OS 14.1. But just only quit.
Also test to **Genshin Impact** as same.

### Steps to reproduce

every app is  quit unexpectedly.

### Expected behaviour

release new version to support macOS 14.1 stable.

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Yuanshen [37596]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/Yuanshen
Identifier:            com.miHoYo.Yuanshen
Version:               4.1.0 (661)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-27 12:28:54.2714 +0800
OS Version:            macOS 14.1 (23B74)
Report Version:        12

Time Awake Since Boot: 44000 seconds
Time Since Wake:       1344 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: BSXPCCnx:com.apple.frontboard.systemappservices (BSCnx:client:com.apple.frontboard.workspace-service)

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a1b11a88

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [37596]
```

### What version of PlayCover are you using?

3.0.0 Beta

### What version of macOS are you using?

macOS 14.1 stable

### Issue Language

- [X] Yes my issue is written in English

**Comment by AGou-ops** [comment] 2023-10-27 05:09
same here.

**Comment by TheMoonThatRises** [comment] 2023-10-27 05:09
Duplicate of #1108.

**Closed as not planned** 2023-10-27 05:09 UTC
Labels: bug

**Comment by valeriorussotto** [comment] 2023-10-27 17:02
god I thought it was a problem of my Mac, I really hope they release a new version soon :)

**Comment by mo3et** [comment] 2023-10-27 17:45
> god I thought it was a problem of my Mac, I really hope they release a new version soon :)

you can try to #1108. Use Nighty version. But I also have a graph error. So just wait the latest Nighty.

**Comment by valeriorussotto** [comment] 2023-10-27 17:59
> > god I thought it was a problem of my Mac, I really hope they release a new version soon :)
> 
> you can try to #1108. Use Nighty version. But I also have a graph error. So just wait the latest Nighty.

I don’t find the nighy version on my playcover app :(
