### ISSUE TITLE
[App Support]: Tried doing everything still cannot make the app "Identity V" to start

### ISSUE THREAD

**Issue by flopdisks** [PlayCover/PlayCover#1381] opened 2024-02-11 16:32 UTC
### App Store link

[https://decrypt.day/app/id1347780764](url) is the link to the app

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Hi, I'm very new here in github and this is my last resort to be able to play identity v. My chip is APPLE M1 and my macOS type is sonoma 14.2.1. I'm not sure which build nightly build I'm using but I am using nightly ver and downloaded from this site [https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_634.dmg](url) .It says playcover nightly 634 which is the latest ver, at least thats what it told me.

As I have said, I did everything including downloading from different IPA sources yet all still crash. I even changed the application type of It doesn't even give me the crashing notification, it just appears in my dock and then disappears. I tried enabling my sip and disabling it but still nothing, I've followed each and every step in the tutorial.  [https://docs.playcover.io/getting_started/download_playcover#download](url)

Every game I donwload, hsr and genshin work so I don't know what is the problem.

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-05-03 20:48
Duplicate of #657. Theres currently no way to get Identity V working through PlayCover.

**Closed as not planned by TheMoonThatRises** 2024-05-03 20:47 UTC
Labels: app-support

**Comment by YukihimeFG** [comment] 2025-01-16 16:14
Still no way to get it work?
