### ISSUE TITLE
[Bug]: All App Crash - MacOS 13.0.1 - 2.0 Beta

### ISSUE THREAD

**Issue by quan0509** [PlayCover/PlayCover#528] opened 2022-11-20 06:52 UTC
### Describe the bug

All app with ipa download from : https://decrypt.day/ crashed 

### Steps to reproduce

NA

### Expected behaviour

NA

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               YouTube [1215]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/YouTube
Identifier:            com.google.ios.youtube
Version:               17.45.1 (17.45.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-20 13:51:11.1081 +0700
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Anonymous UUID:        5BC857DE-8C2F-6D7A-2E95-A9F5BF4FB621


Time Awake Since Boot: 370 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: _OBJC_CLASS_$_AVPictureInPicturePrerollAttributes
Referenced from: <3DAC7E69-A076-3E85-B4EF-D401ED15AD2A> /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/Module_Framework.framework/Module_Framework
Expected in:     <5200620A-2F3B-31A5-8B3A-30353949871A> /System/iOSSupport/System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x19ce3ae58 __abort_with_payload + 8
1   dyld                          	       0x19ce456c0 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x19ce456f4 abort_with_payload + 16
3   dyld                          	       0x19cdd40a4 dyld4::halt(char const*) + 328
4   dyld                          	       0x19cdd1098 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4204
5   dyld                          	       0x19cdcfdc4 start + 2404


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016d5c3a80   x3: 0x0000000000000114
    x4: 0x000000016d5c3680   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016d5c3068
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x00000002424cc947  x15: 0x000000016d5c27f8
   x16: 0x0000000000000209  x17: 0x000000019cdcd344  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d5c3680  x21: 0x0000000000000114  x22: 0x000000016d5c3a80  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x000000016d5c7370  x26: 0x0000000000000001  x27: 0x0000000103b09818
   x28: 0x0000000000000000   fp: 0x000000016d5c3650   lr: 0x000000019ce456c0
    sp: 0x000000016d5c3610   pc: 0x000000019ce3ae58 cpsr: 0x00001000
   far: 0x0000000103b84000  esr: 0x56000080  Address size fault

Binary Images:
       0x19cdca000 -        0x19ce544bf dyld (*) <de46dd52-4994-3fd8-b4b4-e352a1a19354> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)
Writable regions: Total=9936K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9936K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            2630K      476 
__AUTH_CONST                      27.8M      710 
__CTF                               756        1 
__DATA                            37.0M      701 
__DATA_CONST                      37.5M      721 
__DATA_DIRTY                      2633K      301 
__ETC                              112K        1 
__FONT_DATA                        2352        1 
__LINKEDIT                       782.4M        5 
__OBJC_CONST                      5846K      444 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1981K        1 
__TEXT                           768.4M      740 
dyld private memory                512K        2 
===========                     =======  ======= 
TOTAL                              1.8G     4108 



-----------
Full Report
-----------

{"app_name":"YouTube","timestamp":"2022-11-20 13:51:11.00 +0700","app_version":"17.45.1","slice_uuid":"2d15eaa6-dc80-32b2-9d39-332834822b68","build_version":"17.45.1","platform":6,"bundleID":"com.google.ios.youtube","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0.1 (22A400)","roots_installed":0,"name":"YouTube","incident_id":"E1F0CCB9-1033-4962-AAF0-A74ACB49B651"}
{
  "uptime" : 370,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "coalitionID" : 1327,
  "osVersion" : {
    "train" : "macOS 13.0.1",
    "build" : "22A400",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-20 13:51:11.1081 +0700",
  "incident" : "E1F0CCB9-1033-4962-AAF0-A74ACB49B651",
  "pid" : 1215,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-11-20 13:51:09.8571 +0700",
  "procStartAbsTime" : 8925506398,
  "procExitAbsTime" : 8955524647,
  "procName" : "YouTube",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.45.1","CFBundleVersion":"17.45.1","CFBundleIdentifier":"com.google.ios.youtube","DTAppStoreToolsBuild":"14B44"},
  "storeInfo" : {"deviceIdentifierForVendor":"33EF1F8B-37E0-5B9D-87EA-CE9FD5422FBE","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube",
  "crashReporterKey" : "5BC857DE-8C2F-6D7A-2E95-A9F5BF4FB621",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _OBJC_CLASS_$_AVPictureInPicturePrerollAttributes","Referenced from: <3DAC7E69-A076-3E85-B4EF-D401ED15AD2A> \/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/Frameworks\/Module_Framework.framework\/Module_Framework","Expected in:     <5200620A-2F3B-31A5-8B3A-30353949871A> \/System\/iOSSupport\/System\/Library\/Frameworks\/AVKit.framework\/Versions\/A\/AVKit"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":14232,"threadState":{"x":[{"value":6},{"value":4},{"value":6129728128},{"value":276},{"value":6129727104},{"value":0},{"value":0},{"value":6129725544},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":49},{"value":9702263111},{"value":6129723384},{"value":521},{"value":6926684996,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6129727104},{"value":276},{"value":6129728128},{"value":4},{"value":6},{"value":6129742704},{"value":1},{"value":4356872216},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6927177408},"cpsr":{"value":4096},"fp":{"value":6129727056},"sp":{"value":6129726992},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6927134296,"matchesCrashFrame":1},"far":{"value":4357373952}},"frames":[{"imageOffset":462424,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":505536,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":505588,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":41124,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":28824,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4204,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6926671872,
    "size" : 566464,
    "uuid" : "de46dd52-4994-3fd8-b4b4-e352a1a19354",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6926024704,
  "size" : 3403612160,
  "uuid" : "2d053604-1cb6-3821-a8df-360eb2eb519b"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=9936K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9936K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            2630K      476 \n__AUTH_CONST                      27.8M      710 \n__CTF                               756        1 \n__DATA                            37.0M      701 \n__DATA_CONST                      37.5M      721 \n__DATA_DIRTY                      2633K      301 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       782.4M        5 \n__OBJC_CONST                      5846K      444 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1981K        1 \n__TEXT                           768.4M      740 \ndyld private memory                512K        2 \n===========                     =======  ======= \nTOTAL                              1.8G     4108 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "62699e1ec1ff2978b47f6c3b",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "631f72d1de559130376df1fb"
      },
      "deploymentId" : 240000023
    }
  ],
  "experiments" : [

  ]
}
}
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by singhalrishi27** [comment] 2022-11-27 05:17
same here you found any fix?

**Comment by Depal1** [comment] 2022-11-27 05:21
This bug report is a stub. Provide more detailed information for the next time.

**Comment by ZhichGaming** [comment] 2022-11-27 05:22
This issue is also a duplicate of #311.

**Closed as not planned by Depal1** 2022-11-27 05:21 UTC
Labels: bug, duplicate
