### ISSUE TITLE
[Bug]: open Yushen.app  fail

### ISSUE THREAD

**Issue by Striveonger** [PlayCover/PlayCover#1218] opened 2023-11-14 23:13 UTC
### Describe the bug

open `Yushen.app` fail.....

System Version: 14.1.1 (23B81)
PlayCover Version: 2.0.4

### Steps to reproduce

...

### Expected behaviour

...

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Yuanshen [6239]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/Yuanshen
Identifier:            com.miHoYo.Yuanshen
Version:               4.2.0 (685)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-15 07:02:13.9503 +0800
OS Version:            macOS 14.1.1 (23B81)
Report Version:        12
Anonymous UUID:        6F19FF22-2046-A9FA-362B-F9774F510CD6

Sleep/Wake UUID:       756E0A64-CCD9-455D-A4C7-7163F35DDBD9

Time Awake Since Boot: 7000 seconds
Time Since Wake:       1987 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: BSXPCCnx:com.apple.frontboard.systemappservices (BSCnx:client:com.apple.frontboard.workspace-service)

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000019bd00a88

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [6239]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1866148b4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x186626d30 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18661d4f0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x186614c38 mach_msg + 24
4   libdispatch.dylib             	       0x1864c2794 _dispatch_mach_send_and_wait_for_reply + 540
5   libdispatch.dylib             	       0x1864c2b24 dispatch_mach_send_with_result_and_wait_for_reply + 60
6   libxpc.dylib                  	       0x186379510 xpc_connection_send_message_with_reply_sync + 288
7   LaunchServices                	       0x186b9327c LSClientToServerConnection::sendWithReply(void*) + 68
8   LaunchServices                	       0x186baab4c _LSSendNotification + 340
9   AppKit                        	       0x189f12420 -[NSApplication _sendFinishLaunchingNotification] + 248
10  AppKit                        	       0x189f1091c -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 504
11  AppKit                        	       0x189f10518 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 492
12  Foundation                    	       0x18780f454 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 316
13  Foundation                    	       0x18780f248 _NSAppleEventManagerGenericHandler + 80
14  AE                            	       0x18d660d8c 0x18d655000 + 48524
15  AE                            	       0x18d6606b4 0x18d655000 + 46772
16  AE                            	       0x18d659cc4 aeProcessAppleEvent + 488
17  HIToolbox                     	       0x190cbc2d4 AEProcessAppleEvent + 68
18  AppKit                        	       0x189f0af60 _DPSNextEvent + 1440
19  AppKit                        	       0x18a6e0ebc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
20  AppKit                        	       0x189efe100 -[NSApplication run] + 476
21  AppKit                        	       0x189ed53cc NSApplicationMain + 880
22  AppKit                        	       0x18a128240 _NSApplicationMainWithInfoDictionary + 24
23  UIKitMacHelper                	       0x19f2dfd8c UINSApplicationMain + 972
24  UIKitCore                     	       0x1b4c6f93c UIApplicationMain + 148
25  Yuanshen                      	       0x102e01098 0x102dfc000 + 20632
26  dyld                          	       0x1862d90e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x18664fe28 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18664fe28 start_wqthread + 0

Thread 3::  Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib        	       0x18661666c __ulock_wait + 8
1   libdispatch.dylib             	       0x1864a8300 _dlock_wait + 56
2   libdispatch.dylib             	       0x1864a80b4 _dispatch_thread_event_wait_slow + 56
3   libdispatch.dylib             	       0x1864b6fb0 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4   libdispatch.dylib             	       0x1864b6b5c _dispatch_sync_f_slow + 148
5   AXCoreUtilities               	       0x1a5f31870 AXPerformBlockSynchronouslyOnMainThread + 80
6   libdispatch.dylib             	       0x1864a5cb8 _dispatch_call_block_and_release + 32
7   libdispatch.dylib             	       0x1864a7910 _dispatch_client_callout + 20
8   libdispatch.dylib             	       0x1864aaa5c _dispatch_queue_override_invoke + 928
9   libdispatch.dylib             	       0x1864b91f4 _dispatch_root_queue_drain + 392
10  libdispatch.dylib             	       0x1864b9a04 _dispatch_worker_thread2 + 156
11  libsystem_pthread.dylib       	       0x1866510d8 _pthread_wqthread + 228
12  libsystem_pthread.dylib       	       0x18664fe30 start_wqthread + 8

Thread 4 Crashed::  Dispatch queue: BSXPCCnx:com.apple.frontboard.systemappservices (BSCnx:client:com.apple.frontboard.workspace-service)
0   FrontBoardServices            	       0x19bd00a88 _flushBulkMethods + 308
1   FrontBoardServices            	       0x19bcfe8c4 _realizeSettingsExtension + 5456
2   FrontBoardServices            	       0x19bcfcb24 FBSRealizeSettingsExtension + 56
3   FrontBoardServices            	       0x19bd4f09c -[FBSSettings initWithSettings:] + 192
4   FrontBoardServices            	       0x19bcee3cc -[FBSSceneSettings initWithSettings:] + 72
5   FrontBoardServices            	       0x19bcee268 -[FBSSceneParameters initWithSpecification:] + 152
6   FrontBoardServices            	       0x19bcee0d8 -[FBSSceneParameters initWithXPCDictionary:] + 112
7   BaseBoard                     	       0x18d5b0890 _BSXPCDecodeObjectFromContext + 2548
8   BaseBoard                     	       0x18d527580 _BSXPCDecodeObjectForKey + 248
9   BoardServices                 	       0x19bdb1d64 +[BSXPCServiceConnectionProxy decodeArguments:outArgs:fromMessage:forConnection:] + 640
10  BoardServices                 	       0x19bdb6a1c +[BSXPCServiceConnectionProxy invokeMethod:onTarget:withMessage:forConnection:] + 264
11  BoardServices                 	       0x19bdb653c __63-[BSXPCServiceConnectionEventHandler connection:handleMessage:]_block_invoke + 592
12  BoardServices                 	       0x19bdb048c BSXPCServiceConnectionExecuteCallOut + 268
13  BoardServices                 	       0x19bdb6178 -[BSXPCServiceConnectionEventHandler connection:handleMessage:] + 176
14  BoardServices                 	       0x19bdb59e0 -[BSXPCServiceConnection _connection_handleMessage:fromPeer:withHandoff:] + 540
15  libdispatch.dylib             	       0x1864a5cb8 _dispatch_call_block_and_release + 32
16  libdispatch.dylib             	       0x1864a7910 _dispatch_client_callout + 20
17  libdispatch.dylib             	       0x1864aeea4 _dispatch_lane_serial_drain + 748
18  libdispatch.dylib             	       0x1864afa08 _dispatch_lane_invoke + 432
19  libdispatch.dylib             	       0x1864aed28 _dispatch_lane_serial_drain + 368
20  libdispatch.dylib             	       0x1864afa08 _dispatch_lane_invoke + 432
21  libdispatch.dylib             	       0x1864ba61c _dispatch_root_queue_drain_deferred_wlh + 288
22  libdispatch.dylib             	       0x1864b9e90 _dispatch_workloop_worker_thread + 404
23  libsystem_pthread.dylib       	       0x186651114 _pthread_wqthread + 288
24  libsystem_pthread.dylib       	       0x18664fe30 start_wqthread + 8

Thread 5:: NIO-ELT-0-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 6:: NIO-ELT-1-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 7:: NIO-ELT-2-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 8:: NIO-ELT-3-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 9:: NIO-ELT-4-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 10:: NIO-ELT-5-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 11:: NIO-ELT-6-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 12:: NIO-ELT-7-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 13:: NIO-ELT-8-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 14:: NIO-ELT-9-#0
0   libsystem_kernel.dylib        	       0x18661aa00 kevent + 8
1   PlayTools                     	       0x111da938c specialized static KQueue.kevent(kq:changelist:nchanges:eventlist:nevents:timeout:) + 56
2   PlayTools                     	       0x111d93e0c specialized Selector.whenReady0(strategy:onLoopBegin:_:) + 412
3   PlayTools                     	       0x111d90990 SelectableEventLoop.run() + 376
4   PlayTools                     	       0x111d792e8 closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 316
5   PlayTools                     	       0x111d7cab8 partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:parentGroup:selectorFactory:initializer:) + 36
6   PlayTools                     	       0x111d7e8dc thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () + 24
7   PlayTools                     	       0x111daad98 closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) + 272
8   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 15:: ShaderLoadManagerT
0   libsystem_kernel.dylib        	       0x186614848 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	       0x1864a7f28 _dispatch_sema4_timedwait + 64
2   libdispatch.dylib             	       0x1864a8524 _dispatch_semaphore_wait_slow + 76
3   Yuanshen                      	       0x10b4f7b90 0x102dfc000 + 141540240
4   Yuanshen                      	       0x10b4f5538 0x102dfc000 + 141530424
5   Yuanshen                      	       0x10b4d4f98 0x102dfc000 + 141397912
6   libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 16:
0   libsystem_pthread.dylib       	       0x18664fe28 start_wqthread + 0

Thread 17:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x1866148b4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x186626d30 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18661d4f0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x186614c38 mach_msg + 24
4   CoreFoundation                	       0x186731ea4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18673076c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18672fc5c CFRunLoopRunSpecific + 608
7   Foundation                    	       0x187838a78 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x1878ad3f0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 100
9   UIKitCore                     	       0x1b4c70d08 -[UIEventFetcher threadMain] + 104
10  Foundation                    	       0x187831ff4 __NSThread__start__ + 716
11  libsystem_pthread.dylib       	       0x186655034 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x18664fe3c thread_start + 8

Thread 18:
0   libsystem_pthread.dylib       	       0x18664fe28 start_wqthread + 0


Thread 4 crashed with ARM Thread State (64-bit):
    x0: 0x0000600000f4fe51   x1: 0x0000000008000100   x2: 0x0000000000000001   x3: 0x0000000000000000
    x4: 0x00000001db6984b0   x5: 0x0000000000000002   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x00000001db7b5000   x9: 0x37a8b6b4481d0032  x10: 0x0000000000000005  x11: 0x000000000000007f
   x12: 0x0000000000000060  x13: 0x000000012f01dbf0  x14: 0x01000001dc8205d9  x15: 0x00000001dc8205d8
   x16: 0x000000018d59cfe0  x17: 0x00000001e1fdc778  x18: 0x0000000000000000  x19: 0x0000600000f4fe40
   x20: 0x00000001dc828918  x21: 0x00006000025268b0  x22: 0x0000600002b20d20  x23: 0x0000600003e669c0
   x24: 0x9d67436ab4c6d0f0  x25: 0x0000600002b20d20  x26: 0x0000600002b20d60  x27: 0x0000000000000001
   x28: 0x0000000000000840   fp: 0x000000016d22c950   lr: 0x000000019bd00a88
    sp: 0x000000016d22c8b0   pc: 0x000000019bd00a88 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000000 (Breakpoint) brk 0

Binary Images:
       0x1118c0000 -        0x1118c3fff io.playcover.AKInterface (1.0) <a783d879-0077-3951-9393-d3c015b5c551> /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/PlugIns/AKInterface.bundle/Contents/MacOS/AKInterface
       0x111778000 -        0x111783fff libobjc-trampolines.dylib (*) <c9ce7923-2f2d-31eb-a6e4-0f3b7a78f895> /usr/lib/libobjc-trampolines.dylib
       0x111c74000 -        0x111df3fff io.playcover.PlayTools (1.1.7) <62ccaf6d-3d71-303b-9f0f-74faad38c834> /Users/USER/Library/Frameworks/PlayTools.framework/PlayTools
       0x102dfc000 -        0x10ed23fff com.miHoYo.Yuanshen (4.2.0) <96c6140b-b04e-358c-91f4-7b6bc2cdc99f> /Users/USER/Library/Containers/io.playcover.PlayCover/原神.app/Yuanshen
       0x186613000 -        0x18664dfef libsystem_kernel.dylib (*) <b7751381-1442-30b5-91b9-ad7be461bebe> /usr/lib/system/libsystem_kernel.dylib
       0x1864a4000 -        0x1864eafff libdispatch.dylib (*) <dc1d0187-7149-3100-bc63-f633afebee6c> /usr/lib/system/libdispatch.dylib
       0x18636d000 -        0x1863b3fff libxpc.dylib (*) <212b4ed6-cbb2-33de-95c0-7f8a405b3ebd> /usr/lib/system/libxpc.dylib
       0x186b8c000 -        0x186e3efff com.apple.LaunchServices (1141.1) <0c46b08c-2aa0-345c-bf3b-44f28b9dbb86> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
       0x189ed1000 -        0x18b1e5fff com.apple.AppKit (6.9) <b475e541-691d-39c6-8ca4-e414b0d3dd88> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1877de000 -        0x18842bfff com.apple.Foundation (6.9) <2126fd9a-52ce-3eb2-8640-b57535e073b8> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x18d655000 -        0x18d6c8fff com.apple.AE (944) <9a97fc75-cb6d-309b-845e-56c54b72d6a8> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
       0x190c7c000 -        0x190f3bfff com.apple.HIToolbox (2.1.1) <4dffb7eb-bbcd-3ff6-a203-5a0b97358ee8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x19f2db000 -        0x19f3edfff com.apple.UIKitMacHelper (1.0) <913abd4b-3cd0-3d1e-ad1a-7f45b7928c86> /System/Library/PrivateFrameworks/UIKitMacHelper.framework/Versions/A/UIKitMacHelper
       0x1b4c6c000 -        0x1b65acfff com.apple.UIKitCore (1.0) <f561f942-ab8a-387e-b3dc-c57bc7378285> /System/iOSSupport/System/Library/PrivateFrameworks/UIKitCore.framework/Versions/A/UIKitCore
       0x1862d3000 -        0x186367317 dyld (*) <ec7a3ba0-f9bf-3ab8-a0f4-8622e5606b20> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18664e000 -        0x18665aff3 libsystem_pthread.dylib (*) <daf95373-5de6-39a1-a6ce-d87f3f0629cc> /usr/lib/system/libsystem_pthread.dylib
       0x1a5f30000 -        0x1a5f4afff com.apple.accessibility.AXCoreUtilities (1.0) <588e89ad-3eca-3628-b031-01cba849afa4> /System/Library/PrivateFrameworks/AXCoreUtilities.framework/Versions/A/AXCoreUtilities
       0x19bcea000 -        0x19bda3fff com.apple.FrontBoardServices (867.8.1) <5f26f3bb-4708-3ae8-8842-a91966deb562> /System/Library/PrivateFrameworks/FrontBoardServices.framework/Versions/A/FrontBoardServices
       0x18d522000 -        0x18d5f2fff com.apple.BaseBoard (651.3) <924c2819-691e-3d1a-a031-749de6a32fd8> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
       0x19bda4000 -        0x19be05fff com.apple.BoardServices (1.0) <c6ca1d66-c1cc-3294-b002-e845538d295b> /System/Library/PrivateFrameworks/BoardServices.framework/Versions/A/BoardServices
       0x1866b4000 -        0x186b8bfff com.apple.CoreFoundation (6.9) <9f046e36-7286-3a6e-a280-699d6e47cfaf> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 28

VM Region Summary:
ReadOnly portion of Libraries: Total=1.9G resident=0K(0%) swapped_out_or_unallocated=1.9G(100%)
Writable regions: Total=1.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.1G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          560K       26 
CoreAnimation                      320K       20 
CoreGraphics                        32K        2 
CoreServices                       848K        3 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.1G       43 
MALLOC guard page                  192K       12 
SQLite page cache                  256K        2 
STACK GUARD                       56.3M       19 
Stack                             17.3M       19 
VM_ALLOCATE                        112K        7 
__AUTH                            3974K      576 
__AUTH_CONST                      39.9M      817 
__CTF                               824        1 
__DATA                            50.2M      809 
__DATA_CONST                      43.1M      828 
__DATA_DIRTY                      2850K      325 
__FONT_DATA                          4K        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       895.3M        5 
__OBJC_RO                         70.8M        1 
__OBJC_RW                         2156K        1 
__TEXT                             1.0G      850 
dyld private memory                272K        2 
mapped file                      287.2M      301 
shared memory                     1376K       14 
===========                     =======  ======= 
TOTAL                              3.6G     4688 



-----------
Full Report
-----------

{"app_name":"Yuanshen","timestamp":"2023-11-15 07:02:14.00 +0800","app_version":"4.2.0","slice_uuid":"96c6140b-b04e-358c-91f4-7b6bc2cdc99f","build_version":"685","platform":6,"bundleID":"com.miHoYo.Yuanshen","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.1.1 (23B81)","roots_installed":0,"name":"Yuanshen","incident_id":"29306325-3691-4332-A061-C093559FF36D"}
```
```


### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-11-15 00:09
Duplicate of #1108.

**Closed as not planned by TheMoonThatRises** 2023-11-15 00:09 UTC
Labels: game-support
