### ISSUE TITLE
[Bug]: I can't move the mouse after using elemental burst in Genshin Impact [ 2.0.0 (174) ]

### ISSUE THREAD

**Issue by quxn734** [PlayCover/PlayCover#577] opened 2022-12-15 06:17 UTC
### Describe the bug

So after using elemental burst in Genshin. I can't use my mouse to move unless I press "option" and move the screen by cursor then press "option" again to move fine like it nerver happens before

### Steps to reproduce

Using elemental burst

### Expected behaviour

This is the link how I experienced that https://www.youtube.com/shorts/yxPT_CXiwio (even with the touchpad btw)

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [x] Yes my issue is written in English

**Comment by dere4a** [comment] 2022-12-22 01:02
Can you send screenshot of your keymaps? 
Maybe I can guess what's going on

**Comment by quxn734** [comment] 2022-12-24 16:31
> Can you send screenshot of your keymaps? Maybe I can guess what's going on
<img width="478" alt="Screenshot_2022-12-17_at_19 26 27" src="https://user-images.githubusercontent.com/120622484/209444242-77baf29b-7e2c-4da5-856e-ba8e8dc29fc0.png">

Here. Everything is fine unless these 2 of mouse mapping. The right one I can move smoothly but when teleported or after used Q it doesn't work, the left one I can use normally but it is choppy/ stuttering.

**Comment by ashran** [comment] 2023-01-01 09:35
Exactly. Some people speculate that this issue is caused by the return rate of the mouse, but this bug does not exist in the 1.X version. The left mouse mapping is very laggy, and the right one is very smooth but fails frequently.

**Comment by quxn734** [comment] 2023-01-02 04:52
> Exactly. Some people speculate that this issue is caused by the return rate of the mouse, but this bug does not exist in the 1.X version. The left mouse mapping is very laggy, and the right one is very smooth but fails frequently.

I hope it will get fixed soon. The 1.1.1 gaming experience is good but I'm interested in 2.0+ new features.

**Comment by TheMoonThatRises** [comment] 2023-02-22 20:06
Issue is fixed on nightlies through one of Xyct's prs. Use the circular mouse area instead of the rounded square, as the rounded square is not intended for mouse movement.

**Closed as completed by TheMoonThatRises** 2023-02-22 20:06 UTC
Labels: bug
