### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fruitcatt** [PlayCover/PlayCover#502] opened 2022-11-05 22:33 UTC
### Describe the bug

when I want to change the squad to see the characters genshin crashes

### Steps to reproduce

go to the menu and click squad

### Expected behaviour

the squad opens, I can change or characters open and I can change artifacts and so on

### What version of PlayCover are you using?

1.1.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by fruitcatt** [comment] 2022-11-05 22:33
> ### Describe the bug
> when I want to change the squad to see the characters genshin crashes
> 
> ### Steps to reproduce
> go to the menu and click squad
> 
> ### Expected behaviour
> the squad opens, I can change or characters open and I can change artifacts and so on
> 
> ### Crash log
> _No response_
> 
> ### What version of PlayCover are you using?
> 1.1.1
> 
> ### What version of macOS are you using?
> Ventura (macOS 13)
> 
> ### Issue Language
> * [x]  Yes my issue is written in English
![GenshinImpact-2022-11-06-011224](https://user-images.githubusercontent.com/117546488/200143833-ece379a8-bbea-4ccc-abca-6813bacf9cbc.jpeg)

**Comment by ZhichGaming** [comment] 2022-11-05 22:52
Duplicate of #468.

**Closed as not planned** 2022-11-07 14:35 UTC
Labels: bug, duplicate
