### ISSUE TITLE
[Game Support]: Brawl Stars

### ISSUE THREAD

**Issue by mkyuone** [PlayCover/PlayCover#400] opened 2022-10-05 09:56 UTC
### App Store link

https://apps.apple.com/us/app/brawl-stars/id1229016807

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

App crashes when I clicked open and it asked me to reopen all the time. 

### Crash log

```shell
Date/Time:        2022-10-05 17:53:27.787 +0800
End time:         2022-10-05 17:53:50.269 +0800
OS Version:       macOS 13.0 (Build 22A5358e)
Architecture:     arm64e
Report Version:   40
Incident Identifier: 093D3E84-9EF4-4B38-B8F1-4BFBA98F8AF7

Data Source:      Stackshots
Shared Cache:     DDFDBACE-1FFF-3B1C-871F-8509EDA1F2B1 slid base address 0x192e08000, slide 0x12e08000 (System Primary)
Shared Cache:     8517B7B0-ED9E-3821-9ACC-B8F15471A25C slid base address 0x7ff8013f8000, slide 0x13f8000 (Rosetta)
Shared Cache:     4B7C8AE5-C27C-373D-8CC9-05123587D8D9 slid base address 0x196bec000, slide 0x16bec000 (DriverKit)

Command:          Brawl Stars
Path:             /Users/USER/Library/Containers/io.playcover.PlayCover/Brawl Stars.app/Brawl Stars
Identifier:       com.supercell.laser
Version:          45.198 (45.198)
Is First Party:   No
Architecture:     arm64
Parent:           launchd [1]
PID:              2611
Time Since Fork:  22s

Event:            hang
Duration:         22.48s
Duration Sampled: 1.10s (process was unresponsive for 21 seconds before sampling)
Steps:            11 (100ms sampling interval)

Hardware model:   MacBookPro17,1
Active cpus:      8
HW page size:     16384
VM page size:     16384
Boot args:        amfi_get_out_of_my_way=0x1 ipc_control_port_options=0

Time Since Boot:  1020s
Time Awake Since Boot: 1020s
Time Since Wake:  n/a (machine hasn't slept)

Fan speed:        0 rpm
Total CPU Time:   3.734s (7.3G cycles, 19.7G instructions, 0.37c/i)
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  334.50 GB/460.43 GB, low space threshold 3072 MB
Vnodes Available: 69.02% (83467/120938)

Preferred User Language: en-HK, zh-Hans-HK
Country Code:     HK
Keyboards:        ABC
OS Cryptex File Extents: 3178

Process:          Brawl Stars [2611]
UUID:             49229A9A-2C94-3A59-8986-EBE1A2374EED
Path:             /Users/USER/Library/Containers/io.playcover.PlayCover/Brawl Stars.app/Brawl Stars
Identifier:       com.supercell.laser
Version:          45.198 (45.198)
Is First Party:   No
Shared Cache:     DDFDBACE-1FFF-3B1C-871F-8509EDA1F2B1 slid base address 0x192e08000, slide 0x12e08000 (System Primary)
Architecture:     arm64
Parent:           launchd [1]
UID:              501
Footprint:        19.85 MB
Time Since Fork:  22s
Num samples:      11 (1-11)
CPU Time:         0.995s (3.2G cycles, 14.9G instructions, 0.21c/i)
Note:             Unresponsive for 21 seconds before sampling
Note:             3 idle work queue threads omitted
...
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment] 2022-10-05 09:58
none of supercell games would work. they have kernel(?) jailbreak detection and there is no known workaround for them

**Comment by TheMoonThatRises** [comment] 2023-02-07 03:00
Duplicate of #168.

**Closed as not planned by TheMoonThatRises** 2023-02-07 03:00 UTC
Labels: game-support
