### ISSUE TITLE
[Bug]: Games sometimes freeze or hang on quit 

### ISSUE THREAD

**Issue by ghost** [PlayCover/PlayCover#1165] opened 2023-10-18 17:18 UTC
### Describe the bug

When closing apps through Command + Q, the app often hangs or freezes, requiring the user to use the Force Quit menu to close the game.

### Steps to reproduce

I normally use Honkai: Star Rail with PlayCover, so I'm not sure if this affects other games.

May not be reproducible at first, it seems to only freeze during around half the time I close the app. The chances are increased if I've been using the app for over 5-10 minutes.

Version Info: macOS Sonoma / PlayCover Nightly (514) - (however, this also occurs on the 3.0.0 Beta version)

### Expected behaviour

Normally, clicking the red button in the top left or pressing Command + Q should close the application.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-10-18 19:53
Duplicate of #689. See https://github.com/PlayCover/PlayCover/issues/689#issuecomment-1409805281.

**Closed as not planned by TheMoonThatRises** 2023-10-18 19:53 UTC
Labels: bug
