### ISSUE TITLE
[Bug]: Genshin Impact not opening

### ISSUE THREAD

**Issue by WiktorOlf** [PlayCover/PlayCover#1226] opened 2023-11-20 07:09 UTC
### Describe the bug

I'm on macOS Sonoma 14.1.1 running Playcover v2.0.5 (these aren't available in the drop downs below). When I try to open Genshin it just gives me the "Genshin Impact quit unexpectedly" dialogue and does not run.

### Steps to reproduce

1. Try to open Genshin.
2. It does not.

### Expected behaviour

1. Try to open Genshin.
2. It does.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2023-11-20 10:42
Duplicate of #1108

**Comment by wang-kg** [comment] 2023-11-21 00:36
Me too, I have this issue. Also, Honkai Star Rail can't open too. And I am using the MacOS Sonoma 14.1.1 and PlayCover 3.0.0 Beta.

**Comment by wang-kg** [comment] 2023-11-21 00:54
Again me, I literally just fix this issue, so again I am using the MacOS Sonoma 14.1.1 and PlayCover 3.0.0 Beta. So all you have to do is to replace the Playcover with the latest nighty version. Then,  right click the game -> Settings -> Misc -> change Application Type from **public.app-category.none** to **public.app-category.games**

**Comment by Binzmmc** [comment] 2023-11-21 10:33
<img width="1440" alt="Ảnh màn hình 2023-11-21 lúc 17 31 41" src="https://github.com/PlayCover/PlayCover/assets/151627504/b6db587b-0e39-4b6e-8ac2-7e2339863595">
 Can you show each step by showing pictures?

**Comment by Binzmmc** [comment] 2023-11-21 10:37
<img width="1440" alt="Ảnh màn hình 2023-11-21 lúc 17 34 10" src="https://github.com/PlayCover/PlayCover/assets/151627504/33d6e019-7664-4ebe-b8ab-ab0b4ac566ae">
I can't find where to change the application type

**Comment by Binzmmc** [comment] 2023-11-21 10:42
@KingGlacier help

**Comment by MEMORIEmusic** [comment] 2023-11-21 11:26
> <img alt="Ảnh màn hình 2023-11-21 lúc 17 34 10" width="1440" src="https://user-images.githubusercontent.com/151627504/284548493-33d6e019-7664-4ebe-b8ab-ab0b4ac566ae.png"> I can't find where to change the application type

Please read the entirety of the solution before compaining. KingGlacier clearlt mentioned that they downloaded nightly. You need to be on the latest nightly for the option to show.

**Comment by Dhi47** [comment] 2023-11-21 13:06
Hello, I tried to download the latest nightly version, but MacBook unable to install it due to "Apple cannot check it for malicious software

**Comment by wang-kg** [comment] 2023-11-21 14:11
> @KingGlacier help

You have to download the latest nightly [here](https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_548.dmg). Then, drag the playcover.app into your application folder. When it show something like playcover.app already exists, you click on replace. So reopen playcover the option will be there. Good Luck.

**Comment by wang-kg** [comment] 2023-11-21 14:13
> Hello, I tried to download the latest nightly version, but MacBook unable to install it due to "Apple cannot check it for malicious software

please download the first link of the comment above. Is a .dmg file.

**Comment by Dhi47** [comment] 2023-11-21 14:15
yup, 
<img width="964" alt="Screenshot 2023-11-21 at 10 14 23 PM" src="https://github.com/PlayCover/PlayCover/assets/151641996/61947d14-517e-48c0-96f3-7d74486ec4c6">

still the same

**Comment by MEMORIEmusic** [comment] 2023-11-21 14:26
> yup, <img alt="Screenshot 2023-11-21 at 10 14 23 PM" width="964" src="https://user-images.githubusercontent.com/151641996/284607205-61947d14-517e-48c0-96f3-7d74486ec4c6.png">
> 
> still the same

Go to system settings -> Privacy and Security -> scroll down and click Allow/Open Anyway

**Comment by Dhi47** [comment] 2023-11-21 14:40
Life saver!. yupp it works. Thanks so much!

**Comment by ajithreddy2** [comment] 2023-11-22 07:03
> > yup, <img alt="Screenshot 2023-11-21 at 10 14 23 PM" width="964" src="https://user-images.githubusercontent.com/151641996/284607205-61947d14-517e-48c0-96f3-7d74486ec4c6.png">
> > still the same
> 
> Go to system settings -> Privacy and Security -> scroll down and click Allow/Open Anyway

thx i was worried 😇

**Comment by TerrenceMiao** [comment] 2023-11-22 20:19
> Again me, I literally just fix this issue, so again I am using the MacOS Sonoma 14.1.1 and PlayCover 3.0.0 Beta. So all you have to do is to replace the Playcover with the latest nighty version. Then, right click the game -> Settings -> Misc -> change Application Type from **public.app-category.none** to **public.app-category.games**

Following above instructions, download [PlayCover_nightly_551.dmg](https://github.com/PlayCover/PlayCover/suites/18423924795/artifacts/1067866867), then can run Genshin Impact successfully on my M2 Max, Sonoma 14.1.1  (crashed with PlayCover 3.0.0 Beta)

**Comment by Haruki-JP** [comment] 2023-11-23 06:56
@TerrenceMiao
I followed the instructions as told, but could not start the app with the message "The application was terminated for unexpected reasons. and could not start the application. I am using M1mac Sonoma 14.1.1.

**Closed as completed** 2023-11-23 07:24 UTC
Labels: bug

**Comment by kryptofaz** [comment] 2023-12-09 01:29
This fixed it! Thank! 🙏🏼

**Comment by asrorbek-mannonov** [comment] 2023-12-23 20:27
> > Again me, I literally just fix this issue, so again I am using the MacOS Sonoma 14.1.1 and PlayCover 3.0.0 Beta. So all you have to do is to replace the Playcover with the latest nighty version. Then, right click the game -> Settings -> Misc -> change Application Type from **public.app-category.none** to **public.app-category.games**
> 
> Following above instructions, download [PlayCover_nightly_551.dmg](https://github.com/PlayCover/PlayCover/suites/18423924795/artifacts/1067866867), then can run Genshin Impact successfully on my M2 Max, Sonoma 14.1.1 (crashed with PlayCover 3.0.0 Beta)



This really worked for me. After disabling the SIP, altering boot options and installing nightly build instead from the link above and upgrading the XCode to latest version.
