### ISSUE TITLE
[Game Support]: Background music despite app being closed

### ISSUE THREAD

**Issue by Moonshee5288** [PlayCover/PlayCover#1332] opened 2024-01-17 05:51 UTC
### Describe the bug

I am also a victim of the Sonoma 14.2.1 glitch where no apps work. BUT. MY PLAYCOVER HAS TAKEN IT TO ANOTHER LEVEL AND DECIDED TO PLAY THE GENSHIN BACKGROUND MUSIC WHILST NOTHING IS ON, I HAVE TRIED EVERYTHING AND STILL NOTHING WORKS, I CAN'T EVEN PLAY AUDIO FROM MY MAC ANYMORE BECAUSE ALL I HEAR IS THE GENSHIN AUDIO TRACK.

### Steps to reproduce

I think i had genshin open when i updated, but that is probably not the problem. Use a app that has background music in it and open it on playcover 3.0.0 beta 2 and have a mac on update 14.2.1. 

### Expected behaviour

The app opens and THE MUSIC IS NOT PLAYING IN THE BACKGROUND 24/7

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2024-01-17 10:19
Perhaps Genshin is running in the background. Press command + option + escape and select genshin impact and PlayCover in the force quit menu and quit both of those.

Maybe you accidentally hid the genshin impact window by accidentally pressing command + H, which doesn't close the application but temporarily hides the application window

**Comment by XuYicong** [comment] 2024-01-18 10:52
lol you could just open task monitor and end the Genshin process. 

It's probably something wrong with window creation, but we probably can't reproduce it with the limited information you provided. Maybe try changing random settings like application category?

**Comment by Moonshee5288** [comment] 2024-01-19 07:48
i tried and nothing happened

**Comment by Moonshee5288** [comment] 2024-01-19 09:26
you could try to have genshin open in 2.0.5 playcover then update whilst it is open, then try to open it again with the same playcover and genshin

**Comment by TheMoonThatRises** [comment] 2024-08-29 02:52
A new version of PlayCover has released, and I believe that this issue should have been fixed in it. If this issue still occurs, open a new issue.

**Closed as completed by TheMoonThatRises** 2024-08-29 02:52 UTC
Labels: game-support
