### ISSUE TITLE
[Bug]: The screen does not display correctly when the resolution is changed.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#895] opened 2023-03-27 07:42 UTC
### Describe the bug

If you change Settings→Graphics→Resolution, the display will not be correct.
This problem started around the update to Ver. 2.0.4 and has not been resolved in the latest Ver. 2.0.5 or Nightly builds.

The Issue was closed by someone who did not recognize the issue correctly, so I am posting a new one.
As you can see in the attached image, you can see that the screen configuration is broken, can't you?

Ver2.0.5 or later
<img width="666" alt="スクリーンショット 2023-03-27 16 31 27" src="https://user-images.githubusercontent.com/25951129/227873751-42d9a8f7-269a-4407-b2ba-240225421ebb.png">

Ver2.0.0 sample
<img width="666" alt="スクリーンショット 2023-03-27 16 34 46" src="https://user-images.githubusercontent.com/25951129/227873792-925d79cb-75c6-4af3-bb5f-e8cb356fd2ed.png">

### Steps to reproduce

I used the following application to check.
https://apps.apple.com/us/app/destiny-child/id1416959016
You can check by installing the application on PlayCover (2.0.4) and following the steps below.

confirm activation of normal settings
Start up without modifying the graphics settings.
The application starts up in iPad resolution and can be played without any problems.

exit the application and change the graphics settings
First, exit the application that was normally launched.
Then open the application settings and go to the graphics settings.
Select anything other than "Default" from the resolution settings.

*Auto, 1080p, 4K, or custom. Any of these is acceptable.
*Enter a value that matches the monitor resolution to finalize the resolution setting.

When start the application, a window with a corrupted display opens.
When the application is launched, the window resizes but is not displayed correctly.
The game screen is stretched horizontally and much of the screen extends outside the window.

### Expected behaviour

The application display should conform to the window size.
*Displayed correctly in PlayCover (2.0.0)
　Once resolved with a nightly build, the problem still exists in both the latest Ver 2.0.5 and the latest nightly build.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by tellus1019** [comment] 2023-03-27 07:47
@TheMoonThatRises 
Remember the Issue you responded to?
This issue is happening again.
#801 [[Bug]: Changing the resolution does not display correctly.](https://github.com/PlayCover/PlayCover/issues/801)

**Comment by IsaacMarovitz** [comment] 2023-03-27 14:05
Duplicate of #888

**Closed as not planned by IsaacMarovitz** 2023-03-27 14:05 UTC
Labels: bug
