### ISSUE TITLE
[Bug]: Hay Day Unable to Open

### ISSUE THREAD

**Issue by ghost** [PlayCover/PlayCover#1047] opened 2023-07-19 13:21 UTC
### Describe the bug

The app Hay Day is unable to open.

### Steps to reproduce

Open Hay Day app in PlayCover (Hay Day downloaded from Decrypt IPA Store). And it will not open and show error.

### Expected behaviour

It is supposed to open the game. 

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Hay Day [22097]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/Hay Day.app/Hay Day
Identifier:            com.supercell.soil
Version:               1.58.81 (1.58.81)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-19 21:19:06.8021 +0800
OS Version:            macOS 13.3 (22E252)
Report Version:        12
Anonymous UUID:        1CA6C913-8F95-AFC5-743A-B175CD7C576E


Time Awake Since Boot: 35000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/soilx.framework/soilx
Referenced from: <2A5688E8-0C01-30A0-83A0-E6DEECD5F29B> /Users/USER/Library/Containers/io.playcover.PlayCover/Hay Day.app/Hay Day
Reason: tried: '/usr/lib/swift/soilx.framework/soilx' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/soilx.framework/soilx' (no such file), '/usr/lib/swift/soilx.framework/soilx' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/soilx.framework/soilx' (no such file), '/System/Library/Frameworks/soilx.framework/soilx' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x186311118 __abort_with_payload + 8
1   dyld                          	       0x18631cd7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18631cdb0 abort_with_payload + 16
3   dyld                          	       0x1862a88a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x1862a5590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x1862a3e18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d33a8f0   x3: 0x000000000000007a
    x4: 0x000000016d33a4f0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000ba0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x00000001862a135c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d33a4f0  x21: 0x000000000000007a  x22: 0x000000016d33a8f0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001e1f5acc0  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016d33a4c0   lr: 0x000000018631cd7c
    sp: 0x000000016d33a480   pc: 0x0000000186311118 cpsr: 0x00001000
   far: 0x0000000104e24000  esr: 0x56000080  Address size fault

Binary Images:
       0x102ac4000 -        0x10459bfff com.supercell.soil (1.58.81) <2a5688e8-0c01-30a0-83a0-e6deecd5f29b> /Users/USER/Library/Containers/io.playcover.PlayCover/Hay Day.app/Hay Day
       0x18629e000 -        0x18632c53b dyld (*) <6f2c2bb8-4bbc-3b64-b927-d3f3193b6295> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=830.2M resident=0K(0%) swapped_out_or_unallocated=830.2M(100%)
Writable regions: Total=8864K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8864K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            5963K        3 
__DATA_CONST                        22K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       802.8M        2 
__TEXT                            27.4M        2 
dyld private memory                272K        2 
===========                     =======  ======= 
TOTAL                            900.4M       14 



-----------
Full Report
-----------

{"app_name":"Hay Day","timestamp":"2023-07-19 21:19:07.00 +0800","app_version":"1.58.81","slice_uuid":"2a5688e8-0c01-30a0-83a0-e6deecd5f29b","build_version":"1.58.81","platform":6,"bundleID":"com.supercell.soil","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3 (22E252)","roots_installed":0,"name":"Hay Day","incident_id":"7ABEDE90-47F9-45C1-B8C9-1873A124B5BB"}
{
  "uptime" : 35000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "coalitionID" : 4091,
  "osVersion" : {
    "train" : "macOS 13.3",
    "build" : "22E252",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-19 21:19:06.8021 +0800",
  "incident" : "7ABEDE90-47F9-45C1-B8C9-1873A124B5BB",
  "pid" : 22097,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-19 21:19:06.7735 +0800",
  "procStartAbsTime" : 848638451643,
  "procExitAbsTime" : 848638770268,
  "procName" : "Hay Day",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Hay Day.app\/Hay Day",
  "bundleInfo" : {"CFBundleShortVersionString":"1.58.81","CFBundleVersion":"1.58.81","CFBundleIdentifier":"com.supercell.soil","DTAppStoreToolsBuild":"14E221"},
  "storeInfo" : {"deviceIdentifierForVendor":"06B190CD-1D88-59E4-8A25-57BC7D739382","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.supercell.soil",
  "crashReporterKey" : "1CA6C913-8F95-AFC5-743A-B175CD7C576E",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "com.supercell.soil",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/soilx.framework\/soilx","Referenced from: <2A5688E8-0C01-30A0-83A0-E6DEECD5F29B> \/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Hay Day.app\/Hay Day","Reason: tried: '\/usr\/lib\/swift\/soilx.framework\/soilx' (no such file, not in dyld cache), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/lib\/swift\/soilx.framework\/soilx' (no such file), '\/usr\/lib\/swift\/soilx.framework\/soilx' (no such file, not in dyld cache), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/lib\/swift\/soilx.framework\/soilx' (no such file), '\/System\/Library\/Frameworks\/soilx.framework\/soilx' (no such file, not in dyld cache), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":307136,"threadState":{"x":[{"value":6},{"value":1},{"value":6127069424},{"value":122},{"value":6127068400},{"value":0},{"value":0},{"value":2976},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":50},{"value":4},{"value":32768},{"value":521},{"value":6545871708,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6127068400},{"value":122},{"value":6127069424},{"value":1},{"value":6},{"value":8085941440,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6546378108},"cpsr":{"value":4096},"fp":{"value":6127068352},"sp":{"value":6127068288},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6546329880,"matchesCrashFrame":1},"far":{"value":4376903680}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":1},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":1},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":1},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4339810304,
    "CFBundleShortVersionString" : "1.58.81",
    "CFBundleIdentifier" : "com.supercell.soil",
    "size" : 28147712,
    "uuid" : "2a5688e8-0c01-30a0-83a0-e6deecd5f29b",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Hay Day.app\/Hay Day",
    "name" : "Hay Day",
    "CFBundleVersion" : "1.58.81"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6545858560,
    "size" : 582972,
    "uuid" : "6f2c2bb8-4bbc-3b64-b927-d3f3193b6295",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6545195008,
  "size" : 3539501056,
  "uuid" : "581a6955-d455-3735-973b-5233bd5dd16e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=830.2M resident=0K(0%) swapped_out_or_unallocated=830.2M(100%)\nWritable regions: Total=8864K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8864K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            5963K        3 \n__DATA_CONST                        22K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       802.8M        2 \n__TEXT                            27.4M        2 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                            900.4M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "89054df12864f835baf24cc12727062641f791a7",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63508950b3714d3622fc77f7",
      "factorPackIds" : {
        "SIRI_MEMORY_SYNC_CONFIG" : "63508beab3714d3622fc7808"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "62c751b6bcb0435c2153fe92",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "649a1ff23c66a8254c4d3b9e",
        "SIRI_UNDERSTANDING_MORPHUN" : "63f00b1c06644d312600c7bd"
      },
      "deploymentId" : 240000269
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    },
    {
      "treatmentId" : "8ca8349c-e2bc-482c-9ca7-3907b48a5341",
      "experimentId" : "648b5a581b04c12d4127bbb6",
      "deploymentId" : 400000002
    }
  ]
}
}

Model: Macmini9,1, BootROM 8422.100.650, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: LG FHD, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 12 2023 05:52:26 version 18.20.383.14.7.8.149 FWID 01-1469d19d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB30Bus
USB Device: Wireless Receiver
USB Device: Lenovo Black Silk USB Keyboard
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ghost** [comment] 2023-08-19 08:03
Any updates on this?

**Comment by ghost** [comment] 2023-08-31 09:43
:(

**Comment by TheMoonThatRises** [comment] 2023-09-02 22:19
Duplicate of #897.

**Closed as not planned by TheMoonThatRises** 2023-09-02 22:19 UTC
Labels: bug
