### ISSUE TITLE
[Bug]: the app can not open again

### ISSUE THREAD

**Issue by EvanYzl** [PlayCover/PlayCover#1172] opened 2023-10-22 00:45 UTC
### Describe the bug

Unable to open the software, the system repeatedly keeps prompting flashback, need to reopen the

### Steps to reproduce

open the StarRail ,quit it ,then it can not open again
<img width="263" alt="截屏2023-10-22 08 38 20" src="https://github.com/PlayCover/PlayCover/assets/98632645/46290b03-dc1c-463b-8019-0e34ea9075d7">
<img width="260" alt="截屏2023-10-22 08 38 26" src="https://github.com/PlayCover/PlayCover/assets/98632645/0c6e2499-5e36-46bf-b653-6dd8b8c32dbb">

### Expected behaviour

/

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-10-22 01:18
Duplicate of #1108.

**Closed as not planned by TheMoonThatRises** 2023-10-22 01:18 UTC
Labels: bug
