### ISSUE TITLE
[Bug]: the app go blank after force quit the game

### ISSUE THREAD

**Issue by AntsAndBoots** [PlayCover/PlayCover#1355] opened 2024-01-27 17:49 UTC
### Describe the bug

<img width="1012" alt="image" src="https://github.com/PlayCover/PlayCover/assets/157910770/0dcd9760-a3dc-4834-8205-24e765056d0f">
Playcover and the app worked at first. but after force quit the app, the next time I opened Playcover, all I got was a blank interface with no installed app in it.

### Steps to reproduce

1. open Playcover 
2. run a game
3. close the game (using force quit because the game is not responding)
4. quit Playcover
5. re-open Playcover
6. Playcover App library go blank.

### Expected behaviour

installed apps or games appear on the app library

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-01-29 00:08
Duplicate of #1299. Make sure to turn off auto-updates before updating to 3.0.0 Beta 2.

**Closed as not planned by TheMoonThatRises** 2024-01-29 00:08 UTC
Labels: bug
