### ISSUE TITLE
[Bug]: Typing in game

### ISSUE THREAD

**Issue by MhAmerian** [PlayCover/PlayCover#1336] opened 2024-01-19 01:42 UTC
### Describe the bug
I've installed pubg, and run it from app library, not playcover. in section that players must type a username before they can play, I can't type anything in the game, smartkeymap is on if you want to know
Mac OS 14.0
PlayCover nightly 611

**Comment by TheMoonThatRises** [comment] 2024-01-19 21:14
Duplicate of #1315.

**Closed as not planned by TheMoonThatRises** 2024-01-19 21:14 UTC
Labels: bug

**Comment by colette-exe** [comment] 2025-02-24 15:10
Hello! I tried pressing `ctrl` while typing and it worked! I also tried letting go of `ctrl` and it also worked.
