### ISSUE TITLE
[Bug]: game resolution issue on 2.0.4

### ISSUE THREAD

**Issue by FlyMeToTheMoonAndLetMePlayAmongTheStars** [PlayCover/PlayCover#746] opened 2023-01-24 16:32 UTC
### Describe the bug

games are somehow running at a noticeably lower resolution when using the M1 and M2 identifiers, and have little difference in graphical clarity vs A12Z. 

i noticed this when playing genshin for like half an hour and saw my macbook's temperature were still around 40-50C, at first i was like "wow, did apple or playcover somehow improve optimization with these updates?" but then i realized the game resolution was lower than before and this is actually a bug

also when using the m2 identifier, the joystick UI on genshin gets abnormally BIG compared to m1

update: even the metal HUD shows there's something wrong with the game's render resolution/scaling 

metal HUD from genshin (pre 2.0.4/macOS 13.1)
![image](https://user-images.githubusercontent.com/78054566/214355238-a9759359-fa9c-4463-99b7-fb0059391442.png)

metal HUD from genshin (2.0.4/macOS 13.2)

<img width="343" alt="image" src="https://user-images.githubusercontent.com/78054566/214355554-11dc34e9-cc8d-4f06-9b50-492f6dfca612.png">

my playcover settings of the game were consistent across the two versions, identifier set to M1, resolution set to auto (1440x900)

### Steps to reproduce

test genshin on playcover 2.0.4 + macOS 13.2 vs. genshin on playcover 2.0.3 (or 2.0.2) + macOS 13.1

### Expected behaviour

higher game resolution like it normally was before

### Crash log

```shell
n/a, no crash
```

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13.2)

### Issue Language

- [X] Yes my issue is written in English

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment] 2023-01-24 17:45
i took some screenshots on different resolution settings to see if increasing the resolution improves the render clarity (seems like it doesnt, yet there's still somehow a huge performance penalty at higher resolutions) 

| Auto (1440x900) | 4K preset (16:10) |
| ------- | ------- |
| <img width="1440" alt="Screenshot 2023-01-24 at 12 28 34 PM" src="https://user-images.githubusercontent.com/78054566/214368488-57051397-6cae-4de8-b1fa-cdab69d7b13d.png"> | <img width="1440" alt="Screenshot 2023-01-24 at 12 29 37 PM" src="https://user-images.githubusercontent.com/78054566/214368529-72313d8d-988b-46cb-94e9-1a5d71cf1606.png"> |

**Comment by zanderp25** [comment] 2023-01-24 18:15
Yeah, they look exactly the same...

**Comment by porea** [comment] 2023-01-25 04:19
I got the same issue after upgraded to macOS 13.2, using playcover 2.0.4

**Comment by porea** [comment] 2023-01-25 04:39
![image](https://user-images.githubusercontent.com/12146151/214481222-611e2b5b-7745-4b3b-97a5-6559cd019d07.png)

**Comment by elisezhu123** [comment] 2023-01-25 09:04
actually it will not change the resolution, because it i just the genshin in iOS. for ios, the restricted resolution for genshin is 2K, is can no more than 4k, the solution in the metal is just the size of your windows rather than the resolution itself

**Comment by porea** [comment] 2023-01-25 09:31
![image](https://user-images.githubusercontent.com/12146151/214527535-9b3af4d6-87d2-4fb5-a1d7-df97291ad621.png)
Unfortunately, after the upgrade to macOS 13.2, the resolution of Genshin is only 1024x576.

**Comment by Nipol** [comment] 2023-01-25 10:04
Comparison between versions of screenshot, https://github.com/PlayCover/PlayCover/issues/744#issuecomment-1402958432

**Comment by ohaiibuzzle** [comment] 2023-01-25 10:43
The observations so far points to that on 13.2 whatever Apple changed, it has forced apps to run in portrait mode all the time... somehow

PlayTools was taking what was supposed to be the height of the display area and shove it into the width, which is "good enough" to fill the display area, but is causing them to run at (basically) an aspect ratio lower

It only happens to apps that declare that they are landscape only as well. Portrait oriented apps appears to not run into the same issue

**Comment by Huxiaojiao233** [comment] 2023-01-26 11:27
The same, while I update to macOS 13.2, my game's resolution is very weird. Here are my screenshot.

![截屏2023-01-26 19 22 09](https://user-images.githubusercontent.com/49110989/214824476-e1485970-47ca-4c7a-a5c7-b34ccfe5ddcd.png)

**Comment by vergsparda** [comment] 2023-01-26 11:28
> ![image](https://user-images.githubusercontent.com/12146151/214527535-9b3af4d6-87d2-4fb5-a1d7-df97291ad621.png) Unfortunately, after the upgrade to macOS 13.2, the resolution of Genshin is only 1024x576.

same issue

**Comment by toocoolhenry** [comment] 2023-01-26 17:26
Same issue iOS 13.2 and play cover 2.04
![4DBC3D95-D819-4E58-A387-BFBCFB79EB56](https://user-images.githubusercontent.com/111232660/214906109-5a75b044-881b-4ca0-a21b-13b713dad892.jpeg)

**Comment by 1298509345** [comment] 2023-01-29 07:42
same issue. If I knew, I wouldn't upgrade macos13.2

**Comment by Marsman1996** [comment] 2023-01-29 08:19
It seems that we could start the game in the built-in screen, which makes the  resolution better.

### start game in built-in screen 
![image](https://user-images.githubusercontent.com/22045841/215313888-d642f0db-04c9-431d-87a9-3175dcd0cc35.png)

### start game in external screen (2560*1440)
![image](https://user-images.githubusercontent.com/22045841/215314062-283dcfa0-b458-4764-9b14-22e1c2aaa6b8.png)

**Comment by entisocial** [comment] 2023-01-29 11:35
The previous post inspired me, having a Mac mini I don't have an internal display, if I launch the game in the native resolution of 1920 x 1080 I get this:
![Capture d’écran 2023-01-29 à 12 25 07](https://user-images.githubusercontent.com/9813382/215323026-3069cce4-708e-4ebd-8fad-e0d9bdf756b8.png)
But if I change the settings for the monitor to be any hiDPI resolution the game would launch with a slightly better resolution:
<img width="424" alt="Capture d’écran 2023-01-29 à 12 25 43" src="https://user-images.githubusercontent.com/9813382/215323103-5181b151-ffc6-4f1b-94b5-b809147b41a3.png">
If I extend my monitor with airplay to my iPad and launch it from there it gets even better:
![Capture d’écran 2023-01-29 à 13 30 47](https://user-images.githubusercontent.com/9813382/215326298-78667b64-a6ac-456f-b1f3-d69e4d839e85.png)
I also happen to have an hdmi dongle that can spoof a 4k screen. If I launch the game with it I can get this:
<img width="739" alt="Capture d’écran 2023-01-29 à 13 46 06" src="https://user-images.githubusercontent.com/9813382/215327368-a97b8d5f-0f90-4c60-a73d-9ba40a5b0964.png">

**Comment by ohaiibuzzle** [comment] 2023-01-29 15:29
Okay, lemme explain the issue, so that we can just focus on the problem and not trying to chase around fixes
- In macOS 13.2, Apple forces apps to start in portrait (for some reason) and PlayTools are not correctly rotating these apps
- The bodge in https://github.com/PlayCover/PlayTools/commit/1e17f6d8df39251a9fdc124bb0fade98f69b41d8 gets around the issue by flipping the width and height of the display, but does NOT fix the orientation. This result in your display height being used as width, while macOS still thinking it's running in portrait, which decreases the resolution proportionally to your display's aspect ratio. The viewframe that you see is just macOS truncating what should be spanning way below
- The way macOS determines what resolution the window should be depends on your display resolution and the scaling factor that it's at

The consequences are:
- People who are hit the hardest are people using external display without HiDPI scaling. Those will just get straight up roughly (9/16)*2 the amounts of pixels that should be there
- People running **with** HiDPI, depending on your aspect ratio, may not even notice it (since on a MacBook Air (M1), decreasing by that amount still puts you over its scaled res)

**Comment by lslqtz** [comment] 2023-01-30 01:19
Without injecting PlayTools, the app (Genshin Impact) launches normally in landscape mode, and the resolution on the Metal Hud seems to scale with the window size. Maybe we can wait and see Apple release the next version of macOS.

Edit: After using the latest nightly version (242), I found that the resolution displayed by the Metal HUD seems to have improved compared to 13.1, although it may not be meaningful under the limitation of the rendering resolution. Maybe it's my illusion.

**Comment by IsaacMarovitz** [comment] 2023-01-30 02:30
We have res control back: https://github.com/PlayCover/PlayTools/pull/75

Window still isn't displaying exactly as intended, but progress

**Comment by IsaacMarovitz** [comment] 2023-01-30 05:54
Fixed by https://github.com/PlayCover/PlayTools/pull/75

**Closed as completed by IsaacMarovitz** 2023-01-30 05:54 UTC
Labels: bug

**Comment by marqueesychangco** [comment] 2023-02-19 15:47
when are you going to push the fix?
