### ISSUE TITLE
[Bug]: Genshin Impact: Can't move the camera after teleportation 

### ISSUE THREAD

**Issue by dere4a** [PlayCover/PlayCover#609] opened 2022-12-21 10:16 UTC
### Describe the bug

Can't control camera via mouse after teleportation.
MBP 13 m1, MacOs ventura 13.0
[Demonstration:](https://user-images.githubusercontent.com/112781715/208879842-85fae405-0c42-4389-a6f5-f0225b5bfb25.mp4
)

### Steps to reproduce

Press teleport to some point, wait the game to load. Press "option" to hide mac cursor. You will not be able to control the camera unless you press "option" and move the screen by cursor then press "option" again.

### Expected behaviour

Working normal like was in version 1.1.1. The problem is in version 2.0.0 and 2.0.1.

### What version of PlayCover are you using?

2.0.1

### What version of macOS are you using?

Ventura (macOS 13.0)

### Issue Language

- [X] Yes my issue is written in English

**Comment by quxn734** [comment] 2022-12-21 10:53
have the same issue here

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment] 2022-12-21 20:23
Update to macOS 13.1

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment] 2022-12-21 21:51
I'm not able to reproduce this issue on macOS 13.1 (22C65) using PlayCover 2.0.1 (build number 185)

Try updating to 13.1 and use the same PlayCover version to see if you still have this problem.

**Comment by dere4a** [comment] 2022-12-22 00:33
I've updated to 13.1. I still have the same bug. 
I noticed that rarely if I wait 5-10 seconds after teleporting, everything works fine. But in 80% cases the problem still persists. 
_I also noticed that in cases when I can't control the camera, the first press on W/A/S/D to control the movements does not work. Like it starts working only after the second press._

**Comment by dere4a** [comment] 2022-12-22 11:51
My problem was in using wrong mouse keymap. I used “mouse button” instead of “Directional Arrows Button” to control the camera. I don’t know why but for me they’re working Identically.
Why did I use wrong keymap? Because there’s also a problem. 
With “mouse button” all is ok, unless I try to teleport. Using “Directional Arrows Button” bug with teleport disappears, but I can’t move the camera smoothly. I noticed that is related with polling rate of my mouse. So my mouse has 1000hz. When i change polling rate from 1000 to 125 it starts to be playable. I’ve been trying to change dpi or “mouse sensitivity” in Playcover without changing polling rate. But no luck. 
In Playcover 1.1.1 all was smoothly with 1000hz.

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment] 2023-01-04 20:06
https://github.com/PlayCover/PlayCover/issues/676 similar issue related to mouse/camera unresponsiveness, also fixed by reverting back to playcover 1.1.1 (i did have to make a keymap from scratch as ones made on newer versions are not backwards compatible)

**Comment by IsaacMarovitz** [comment] 2023-03-07 15:49
Stale

**Closed as not planned by IsaacMarovitz** 2023-03-07 15:49 UTC
Labels: bug
