### ISSUE TITLE
[Game Support]: Blue Archive Does not work on nightly versions

### ISSUE THREAD

**Issue by COBBNELSON** [PlayCover/PlayCover#906] opened 2023-04-03 04:38 UTC
### App Store link

https://apps.apple.com/jp/app/%E3%83%96%E3%83%AB%E3%83%BC%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96/id1515877221

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When opened on playcover, the app is detected as an unofficially licensed app and closed directly.
It cannot be bypassed even after opening with jailbreak detection enabled.
The app was able to open properly in the RELEASE version 2.05.
I apologize for not submitting the crash log because it was too long and exceeded the limit of what could be submitted, but I can submit it if you want.

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2023-05-23 12:14
1. You need to right click Blue Archive -> settings -> bypasses -> insert introspection binaries 
2. You still won't be able to log in.

**Comment by mmkzer0** [comment] 2023-06-08 10:49
I am experiencing the same issue using the latest 3.0.0 Beta Version. A bit after launch, the games anti-tamper throws an exception and closes the application. Neither Jailbreak Bypass nor enabling "Insert Introspection Binaries" works, and disabling PlayChain also has no effect. All combinations of these settings being enabled or disabled lead to the same error.

<img width="1440" alt="Screenshot 2023-06-08 at 12 40 03" src="https://github.com/PlayCover/PlayCover/assets/74553440/aa11aab7-11f9-4e70-b98b-6160a495eb1c">

The latest stable release 2.0.5 works without issue, so this seems to be a regression.

**Comment by Format-DJ** [comment] 2023-06-12 17:56
me too
maybe should uninstall 2.0.5
then using beta>?

**Comment by memekurage** [comment] 2023-06-18 12:23
same issue here

**Comment by TheMoonThatRises** [comment] 2023-09-03 20:51
Closing in favour of #1019.

**Closed as not planned by TheMoonThatRises** 2023-09-03 20:51 UTC
Labels: game-support
