### ISSUE TITLE
[Game Support]: Infinity Nikki

### ISSUE THREAD

**Issue by holidayyy777** [PlayCover/PlayCover#1760] opened 2024-12-06 18:09 UTC
### App Store link

infinity nikki

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Cant open

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Joan1226yyy** [comment] 2024-12-07 04:52
1

**Comment by qqice** [comment] 2024-12-07 09:47
Duplicate of #1755.

**Closed as not planned** 2024-12-19 23:31 UTC
Labels: duplicate, game-support
