### ISSUE TITLE
[Bug]: wrong screen rotation problem in all games!! After upgrading to MacOS 13.2, Playcover 2.0.4.

### ISSUE THREAD

**Issue by Sandeep-K-Suthar** [PlayCover/PlayCover#755] opened 2023-01-29 05:16 UTC
### Describe the bug

When I set my games resolution to App Default I get wrong screen rotation in my all games and some apps after upgrading to macOS 13.2!! In Auto Screen resolution mode there is no such problem but Auto Screen resolution mode makes my games graphics quality bad!!! plz fix this bug!!

### Steps to reproduce

<img width="1440" alt="Screenshot 2023-01-29 at 10 10 44 AM" src="https://user-images.githubusercontent.com/112924224/215306382-7dad40df-1092-49b4-8814-cf3671efae60.png">
<img width="957" alt="Screenshot 2023-01-29 at 10 10 22 AM" src="https://user-images.githubusercontent.com/112924224/215306443-c5979bf0-a9aa-4d9b-9a3a-667a8d5bf3c7.png">

### Expected behaviour

<img width="957" alt="Screenshot 2023-01-29 at 10 11 37 AM" src="https://user-images.githubusercontent.com/112924224/215306419-1afe097d-8ef5-4101-ae93-af0a15f529b5.png">
<img width="1440" alt="Screenshot 2023-01-29 at 10 14 41 AM" src="https://user-images.githubusercontent.com/112924224/215306479-8bcacff2-e900-44de-9658-bd311410ffa6.png">

here in auto resolution mode it works great but it decreases the graphics quality of a game!!

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2023-01-29 15:49
Duplicate of #746

**Closed as not planned by IsaacMarovitz** 2023-01-29 15:49 UTC
Labels: bug
