### ISSUE TITLE
[Game Support]: This one game won't open but other games I have downloaded opened. Please help

### ISSUE THREAD

**Issue by sanamadapaka** [PlayCover/PlayCover#1418] opened 2024-03-20 16:29 UTC
### App Store link

[https://play.google.com/store/apps/details?id=com.netease.idv.googleplay&hl=en&gl=US&pli=1](url)

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

**REPEAT POST CAUSE I DIDN'T GET ANY REPLIES LAST TIME**

Hi, I'm very new here in github and this is my last resort to be able to play identity v. My chip is APPLE M1 and my macOS type is sonoma 14.2.1. I'm not sure which build nightly build I'm using the LATEST version from this site [https://nightly.link/PlayCover/PlayCover/workflows/2.nightly_release/develop/PlayCover_nightly_687.dmg]. It says playcover nightly 687 which is the latest ver, at least thats what it told me.

As I have said, I did everything including downloading from different IPA sources yet all still crash. I even changed the application type of It doesn't even give me the crashing notification, it just appears in my dock and then disappears. I tried enabling my sip and disabling it but still nothing, I've followed each and every step in the tutorial. [https://docs.playcover.io/getting_started/download_playcover#download](https://github.com/PlayCover/PlayCover/issues/url)

Every game I donwload, honkai star rail and genshin work so I don't know what is the problem.

### Crash log

```shell
NO CRASH LOG, WHENEVER I CLICK ON THE APP PLAYCOVER JUST BLINKS (?) and then NOTHING HAPPENS. I CHECKED THE CRASHED LOG IN MY MAC BUT SAW NOTHING RELATED TO IDENTITY V
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-05-03 20:47
Duplicate of #1381. Please do not post duplicate issues (copy & paste).

**Closed as not planned by TheMoonThatRises** 2024-05-03 20:47 UTC
Labels: game-support
