### ISSUE TITLE
[Bug]: Error when playing VOD on Netflix.

### ISSUE THREAD

**Issue by Paimonm** [PlayCover/PlayCover#460] opened 2022-10-28 06:23 UTC
### Describe the bug

Profile selection errors have been resolved in the alpha version. However, an error occurs when playing VOD afterwards.

### Steps to reproduce

Login > Select Profile > Play Video

<img width="1052" alt="스크린샷 2023-01-20 17 28 45" src="https://user-images.githubusercontent.com/116867433/213650486-3b6422ca-e8a6-45fb-a96d-33679a160935.png">

### Expected behaviour

I look forward to playing the video.

### Crash log

```shell
The operation could not be completed.(CHD Error 1005.)
(Playb:10008;CHD:1005;)
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [x] Yes my issue is written in English

**Comment by ZhichGaming** [comment] 2022-10-28 12:52
What app are you trying to use?

**Comment by Paimonm** [comment] 2022-10-28 23:32
> What app are you trying to use?

Ah!! sorry. Error when playing VOD on Netflix.

**Comment by meghrathod** [comment] 2022-12-13 11:04
Had the same problem when I got the IPA from [here](https://ipa.decrypt.day). However, the IPA from [here](http://armconverter.com/decryptedappstore/us/netflix) worked.

**Comment by Paimonm** [comment] 2022-12-15 07:05
I get the same error with both ipas.

> Had the same problem when I got the IPA from [here](https://ipa.decrypt.day). However, the IPA from [here](http://armconverter.com/decryptedappstore/us/netflix) worked.

I get the same error with both ipas.

**Comment by meghrathod** [comment] 2023-01-02 11:40
@Paimonm is your SIP disabled?

**Comment by Paimonm** [comment] 2023-01-03 04:52
@meghrathod Yes. Disabled SIP. Um... Same error on Netflix.

**Comment by storyphoto** [comment] 2023-01-20 05:46
Dear, I found something.

When I set the language "English" as a primary on MacOS,
I can play a video with Netflix well.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/13009165/213625762-114575a0-e697-48fc-b340-927d38e10938.png">

However, if I set the language as "한글(Korean)" as a primary on MacOS,
I get the same error "(Playb:10008;CHD:1005;)" like @Paimonm reported.

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/13009165/213626020-35e9d8c2-89f5-418c-b27b-51b8e356d602.png">

Best Regards,
storyphoto

**Comment by IsaacMarovitz** [comment] 2023-01-31 22:11
Duplicate of #752

**Closed as not planned by IsaacMarovitz** 2023-01-31 22:11 UTC
Labels: bug

**Comment by NMacUser** [comment] 2023-03-03 12:05
I used the one from decrypt store but seem to have the same issue reported here.

Is anyone able to share the Netflix IPA you get from ARM converter via dropbox/email or something please, I seem to be unable to retrieve this from the site myself as stuck on 2 days of waiting.
