### ISSUE TITLE
[App Support]: YouTube missing code symbol

### ISSUE THREAD

**Issue by doctorstrange99992** [PlayCover/PlayCover#1061] opened 2023-07-29 10:44 UTC
### App Store link

https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664

### Current issues

- [x] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

when i open the app it loads for a few seconds and crashes 

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               YouTube [13790]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/YouTube
Identifier:            com.google.ios.youtube
Version:               18.29.1 (18.29.1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-29 07:40:15.2023 +0000
OS Version:            macOS 13.4.1 (22F82)
Report Version:        12
Anonymous UUID:        C6A26ADB-6A04-E95F-4CBC-8451DC83F1FB

Sleep/Wake UUID:       27D4AC2A-A344-4BCA-9E00-1786784131A9

Time Awake Since Boot: 1500000 seconds
Time Since Wake:       54074 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: _OBJC_CLASS_$_AVPictureInPicturePrerollAttributes
Referenced from: <0781CA22-511E-3301-9E35-56DC3CD5EE1B> /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/Module_Framework.framework/Module_Framework
Expected in:     <88D38E90-AD95-3140-ACA3-F1801ED2166C> /System/iOSSupport/System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x188161118 __abort_with_payload + 8
1   dyld                          	       0x18816cd7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18816cdb0 abort_with_payload + 16
3   dyld                          	       0x1880f88a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x1880f5590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x1880f3e18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016efbb830   x3: 0x0000000000000110
    x4: 0x000000016efbb430   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016efbae18
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x0000000234c597a4  x15: 0x000000016efba5a8
   x16: 0x0000000000000209  x17: 0x00000001880f135c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016efbb430  x21: 0x0000000000000110  x22: 0x000000016efbb830  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x0000000000001850  x26: 0x0000000000000001  x27: 0x000000001f070004
   x28: 0x0000000101fcf268   fp: 0x000000016efbb400   lr: 0x000000018816cd7c
    sp: 0x000000016efbb3c0   pc: 0x0000000188161118 cpsr: 0x00001000
   far: 0x0000000101fe0000  esr: 0x56000080  Address size fault

Binary Images:
       0x100e40000 -        0x101aeffff com.google.ios.youtube (18.29.1) <36e28b8c-685e-3225-aeb8-50651c8c39cd> /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/YouTube
       0x10add4000 -        0x111b4ffff com.google.ios.youtube.modules (18.29.1) <0781ca22-511e-3301-9e35-56dc3cd5ee1b> /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/Module_Framework.framework/Module_Framework
       0x102344000 -        0x102473fff com.google.widevine-cdm-secured-ios-2 (15.2.4) <509fdab7-cedf-3fc3-81e1-ccfd6ce62f36> /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/widevine_cdm_secured_ios.framework/widevine_cdm_secured_ios
       0x102d64000 -        0x102f17fff io.playcover.PlayTools (1.1.7) <4a11e56b-92e5-39af-9d43-dd0a1745b0b6> /Users/USER/Library/Frameworks/PlayTools.framework/PlayTools
       0x1880ee000 -        0x18817c553 dyld (*) <2237410f-d39c-30ce-9a94-13aacb66b766> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=9760K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9760K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            3011K      505 
__AUTH_CONST                      34.0M      750 
__CTF                               824        1 
__DATA                            34.8M      742 
__DATA_CONST                      42.0M      758 
__DATA_DIRTY                      2695K      301 
__ETC                              112K        1 
__FONT_DATA                        2352        1 
__LINKEDIT                       822.6M        5 
__OBJC_RO                         66.3M        1 
__OBJC_RW                         2011K        1 
__TEXT                           853.3M      780 
dyld private memory                272K        2 
===========                     =======  ======= 
TOTAL                              1.9G     3851 



-----------
Full Report
-----------

{"app_name":"YouTube","timestamp":"2023-07-29 07:40:21.00 +0000","app_version":"18.29.1","slice_uuid":"36e28b8c-685e-3225-aeb8-50651c8c39cd","build_version":"18.29.1","platform":6,"bundleID":"com.google.ios.youtube","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4.1 (22F82)","roots_installed":0,"name":"YouTube","incident_id":"4EA334CD-2CBF-40DF-B695-FCAC9EB70C2F"}
{
  "uptime" : 1500000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 171973,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F82",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-29 07:40:15.2023 +0000",
  "incident" : "4EA334CD-2CBF-40DF-B695-FCAC9EB70C2F",
  "pid" : 13790,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-29 07:40:10.8648 +0000",
  "procStartAbsTime" : 37960927237765,
  "procExitAbsTime" : 37961031305268,
  "procName" : "YouTube",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"18.29.1","CFBundleVersion":"18.29.1","CFBundleIdentifier":"com.google.ios.youtube","DTAppStoreToolsBuild":"14E221"},
  "storeInfo" : {"deviceIdentifierForVendor":"239910E3-581A-5BCE-AE18-A71C2D19E7CD","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube",
  "crashReporterKey" : "C6A26ADB-6A04-E95F-4CBC-8451DC83F1FB",
  "codeSigningID" : "com.google.ios.youtube",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 54074,
  "sleepWakeUUID" : "27D4AC2A-A344-4BCA-9E00-1786784131A9",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: _OBJC_CLASS_$_AVPictureInPicturePrerollAttributes","Referenced from: <0781CA22-511E-3301-9E35-56DC3CD5EE1B> \/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/Frameworks\/Module_Framework.framework\/Module_Framework","Expected in:     <88D38E90-AD95-3140-ACA3-F1801ED2166C> \/System\/iOSSupport\/System\/Library\/Frameworks\/AVKit.framework\/Versions\/A\/AVKit"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":39621910,"threadState":{"x":[{"value":6},{"value":4},{"value":6156957744},{"value":272},{"value":6156956720},{"value":0},{"value":0},{"value":6156955160},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":49},{"value":9475299236},{"value":6156953000},{"value":521},{"value":6577656668,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6156956720},{"value":272},{"value":6156957744},{"value":4},{"value":6},{"value":6224},{"value":1},{"value":520552452},{"value":4328321640}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6578163068},"cpsr":{"value":4096},"fp":{"value":6156956672},"sp":{"value":6156956608},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6578114840,"matchesCrashFrame":1},"far":{"value":4328390656}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":4},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":4},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":4},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":4},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":4},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4309909504,
    "CFBundleShortVersionString" : "18.29.1",
    "CFBundleIdentifier" : "com.google.ios.youtube",
    "size" : 13303808,
    "uuid" : "36e28b8c-685e-3225-aeb8-50651c8c39cd",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/YouTube",
    "name" : "YouTube",
    "CFBundleVersion" : "18.29.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4477239296,
    "CFBundleShortVersionString" : "18.29.1",
    "CFBundleIdentifier" : "com.google.ios.youtube.modules",
    "size" : 114802688,
    "uuid" : "0781ca22-511e-3301-9e35-56dc3cd5ee1b",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/Frameworks\/Module_Framework.framework\/Module_Framework",
    "name" : "Module_Framework",
    "CFBundleVersion" : "18.29.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4331945984,
    "CFBundleShortVersionString" : "15.2.4",
    "CFBundleIdentifier" : "com.google.widevine-cdm-secured-ios-2",
    "size" : 1245184,
    "uuid" : "509fdab7-cedf-3fc3-81e1-ccfd6ce62f36",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/YouTube.app\/Frameworks\/widevine_cdm_secured_ios.framework\/widevine_cdm_secured_ios",
    "name" : "widevine_cdm_secured_ios",
    "CFBundleVersion" : "15.2.4"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342562816,
    "CFBundleShortVersionString" : "1.1.7",
    "CFBundleIdentifier" : "io.playcover.PlayTools",
    "size" : 1785856,
    "uuid" : "4a11e56b-92e5-39af-9d43-dd0a1745b0b6",
    "path" : "\/Users\/USER\/Library\/Frameworks\/PlayTools.framework\/PlayTools",
    "name" : "PlayTools",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6577643520,
    "size" : 582996,
    "uuid" : "2237410f-d39c-30ce-9a94-13aacb66b766",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6576979968,
  "size" : 3551641600,
  "uuid" : "be59bb71-7b69-3efc-86a8-5625a077ae2e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)\nWritable regions: Total=9760K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9760K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            3011K      505 \n__AUTH_CONST                      34.0M      750 \n__CTF                               824        1 \n__DATA                            34.8M      742 \n__DATA_CONST                      42.0M      758 \n__DATA_DIRTY                      2695K      301 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       822.6M        5 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2011K        1 \n__TEXT                           853.3M      780 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                              1.9G     3851 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "5f0e22c668ca9ca889cd60a9f69c33800561d0b0",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000329
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 8422.121.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Apr  7 2023 15:18:26 version 20.96.28.1.8.7.146 FWID 01-aff1b48a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-11-05 21:58
Duplicate of #666.

**Closed as not planned by TheMoonThatRises** 2023-11-05 21:58 UTC
Labels: app-support
