### ISSUE TITLE
[Game Support]: (Wuthering Waves) Failed to get patch list: File Rename Error

### ISSUE THREAD

**Issue by kang49** [PlayCover/PlayCover#1478] opened 2024-05-21 16:04 UTC
Solved: https://github.com/PlayCover/PlayTools/commit/ae534366169ce19f89563f911732c1d43677786d ~~https://github.com/PlayCover/PlayCover/issues/1478#issuecomment-2123943659~~

### App Store link

https://apps.apple.com/th/app/wuthering-waves/id6475033368?platform=ipad

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

Using nightly 749
MacOS: Sonoma 14.4.1
MacBook Air M1
Ram 8GB
Game version: 1.0.0

Game can't download full game files.
<img width="1440" alt="Screenshot 2024-05-21 at 22 53 12" src="https://github.com/PlayCover/PlayCover/assets/81503963/3c987f7e-247e-4db9-87a7-fa16d597c05d">

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Ryu-ga** [comment] 2024-05-21 16:13
> Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> 
> No other voodoo necessary. Automatically continue to work even if Kuro push updates
> 
> ```
> rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> ```

PlayTools Fix Patch: https://github.com/Ryu-ga/PlayTools/commit/d9fa41c059b6b8f6d1f74b6c78efe7d80cd11417
If I cannot find good alternative solution, I will PR this.
This patch fixes WuWa install error and ToF login error.

Unreal Engine use file path from `ConvertToIOSPath` in their source code.
They separated read path and write path.
In iOS, these functions work well,
But in MacOS they go like this.
original path => '../../Content/Some_Content'
read path '../../Content/Some_Content' => '/Users/\<User\>/Library/Containers/\<App\>/\<Documents or Library\>//Users/\<User\>/Library/Containers/\<App\>/\<Documents or Library\>/\<Some Path\>/Content/Some_Content'
write path '../../Content/Some_Content' => '/Users/\<User\>/Library/Containers/\<App\>/\<Documents or Library ( not same to read path )\>//Users/\<User\>/Library/Containers/\<App\>/\<Documents or Library (same to read path )\>/\<Some Path\>/Content/Some_Content'

**Comment by kang49** [comment] 2024-05-21 16:25
Thank you! This is a temporary fix, so I'll keep the issue open until a permanent solution is found. I appreciate your help!
![image](https://github.com/PlayCover/PlayCover/assets/81503963/0ba85dc2-1036-4399-9291-5581535479a6)

**Comment by boiwertz** [comment] 2024-05-21 22:57
Hi, not very well versed in this stuff. Am I supposed to paste that into the Mac Terminal while the game says checking launcher resource version? And what does ctrl + c do (which I'm assuming is different from cmd + c)?

**Comment by boiwertz** [comment] 2024-05-22 00:43
I just tried creating a script and running it in zsh, and it does bypass "Checking Launcher resource version". It passes "Checking Resource resource version", but I have to stop the script and then re-run it every time. Then, it gets stuck on "Checking Resource_zh resource version", en, ja, and a bunch of other language resources, it seems? Any way to streamline this process?

**Comment by kang49** [comment] 2024-05-22 02:06
@boiwertz Please open your preferred IDE, such as VSCode or any other tool capable of creating files, and paste this improved script:

``` sh
#!/usr/bin/env sh

BASEDIR="/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Client/Saved/Resources/1.0.0"
CACHEDIR="/Users/$USER/Downloads/wuwaScript"
APP_NAME="com.kurogame.wutheringwaves.global"

LATESTMV=""

mkdir -p "$CACHEDIR"

check_if_complete() {
  file=$1
  filesize=$(stat -f%z "$file")
  sleep 1
  new_filesize=$(stat -f%z "$file")
  echo "old:" "$filesize" "new:" "$new_filesize"
  if [ "$filesize" -eq "$new_filesize" ]; then
    return 0
  else
  if [ "$LATESTMV" = "${file%.download}" ]; then
        sleep 1
        osascript -e "tell application \"$APP_NAME\" to quit with force"
        # Move file from cache to current path
        rm "${file}"
        cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
        echo "✅ This Download section is completed. You can reopen you game again!"
  fi
    return 1
  fi
}

while true; do
  for file in $(find "$BASEDIR" -name "*.download"); do
    if check_if_complete "$file"; then
      if [ "$LATESTMV" = "${file%.download}" ]; then
        sleep 1
        osascript -e "tell application \"$APP_NAME\" to quit with force"
        # Move file from cache to current path
        rm "${file}"
        cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
        echo "✅ This Download section is completed. You can reopen you game again!"
      else
        echo "$file => ${file%.download}"
        mv "$file" "${file%.download}"
        # Copy the file to cache directory
        cp "${file%.download}" "$CACHEDIR"
        LATESTMV="${file%.download}"
      fi
    fi
  done
  sleep 1
done
```
After pasting the script, follow these steps in your terminal:
```
chmod +x yourfile.sh
```
```
./yourfile.sh
```
Once you've executed these commands, you can open your game. If the game unexpectedly quits due to a "force quit", don't worry. It's part of the process I've implemented in the code. Simply reopen the game to continue downloading. If you encounter the same error popup again, you can press "Retry" to proceed. Don't forget to remove all cache in "~/Downloads" after all process completed

**Comment by o2buzzle** [comment] 2024-05-22 05:10
I wonder if this is one of those really stupid situation that happened with ToF as well where it was using the base directory completely out of specs, will investigate

**Comment by ohaiibuzzle** [comment] 2024-05-22 06:15
Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.

No other voodoo necessary. Automatically continue to work even if Kuro push updates
```
rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
```

**Comment by indomisotobiasa** [comment] 2024-05-22 06:22
Thx u so muchhhh it works

**Comment by prinzchao** [comment] 2024-05-22 07:19
`rm -r /Users/$USER/Library/Containers/com.kurogame.mingchao/Data/Library/Users/$USER/Library/Containers/com.kurogame.mingchao/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.mingchao/Data /Users/$USER/Library/Containers/com.kurogame.mingchao/Data/Library/Users/$USER/Library/Containers/com.kurogame.mingchao/Data`


CN version with this command

**Comment by ngocsok** [comment] 2024-05-22 07:59
> > Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> > No other voodoo necessary. Automatically continue to work even if Kuro push updates
> > ```
> > rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> > ```


Great it works perfectly, thank you

**Comment by OverLord86** [comment] 2024-05-22 08:09
> Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> 
> No other voodoo necessary. Automatically continue to work even if Kuro push updates
> 
> ```
> rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> ```

It says no such file or directory, what do i do?

**Comment by kang49** [comment] 2024-05-22 08:31
> Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> 
> No other voodoo necessary. Automatically continue to work even if Kuro push updates
> 
> ```
> rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> ```

Symlink...Genius! Thank bro🙏

**Comment by SebastianHsu01** [comment] 2024-05-22 08:59
No such file or directory

**Comment by kang49** [comment] 2024-05-22 09:01
> No such file or directory


What's your command you got that error? rm -r or ln?

**Comment by SebastianHsu01** [comment] 2024-05-22 09:02
can u make a video plz

**Comment by SebastianHsu01** [comment] 2024-05-22 09:03
rm: /Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory
hsusebastian@Hsus-MacBook-Air ~ %

**Comment by kang49** [comment] 2024-05-22 09:04
> rm: /Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory hsusebastian@Hsus-MacBook-Air ~ %

Do you run this command before open the game or after?

**Comment by SebastianHsu01** [comment] 2024-05-22 09:04
after quitting the game

**Comment by SebastianHsu01** [comment] 2024-05-22 09:09
rm: /Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/hsusebastian/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory
hsusebastian@Hsus-MacBook-Air ~ % Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.

No other voodoo necessary. Automatically continue to work even if Kuro push updates


zsh: command not found: Here
zsh: command not found: No
hsusebastian@Hsus-MacBook-Air ~ %

**Comment by SebastianHsu01** [comment] 2024-05-22 09:12
can I send a video to u?

**Comment by kang49** [comment] 2024-05-22 09:13
> can I send a video to u?

Sure, but how?

**Comment by SebastianHsu01** [comment] 2024-05-22 09:14
gmail

**Comment by SebastianHsu01** [comment] 2024-05-22 09:14
ins: Hsu.0601

**Comment by kang49** [comment] 2024-05-22 09:15
In my Github profile has Discord, you can

**Comment by OverLord86** [comment] 2024-05-22 11:02
> In my Github profile has Discord, you can

If the problem is resolved can you pls send solution here as well

**Comment by kang49** [comment] 2024-05-22 11:06
> > In my Github profile has Discord, you can
> 
> If the problem is resolved can you pls send solution here as well

Nothing to send a new solution. SebastianHsu01 Just the wrong step

**Comment by RenMing-Huang** [comment] 2024-05-22 12:31
> No such file or directory

replace  `com.kurogame.wutheringwaves.global ` with `com.kurogame.mingchao`

**Comment by cal099** [comment] 2024-05-22 15:08
what if we dont have access to terminal?

**Comment by kang49** [comment] 2024-05-22 15:23
> what if we dont have access to terminal?

Why? It's not your PC?

**Comment by yameroni** [comment] 2024-05-22 15:57
> > Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> > No other voodoo necessary. Automatically continue to work even if Kuro push updates
> > ```
> > rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> > ```

Thank you soo much

**Comment by SHSIDCJ** [comment] 2024-05-22 16:30
what if i cant even open the game tho other games like genshin and hsr always worked fine for me... i also changed to .games directory but it just crashes. I remember opening it once the first time but i just closed it on accident

**Comment by yorgetsuten** [comment] 2024-05-22 16:34
> what if i cant even open the game tho other games like genshin and hsr always worked fine for me... i also changed to .games directory but it just crashes. I remember opening it once the first time but i just closed it on accident

you should try to reinstall the game or playcover if it won't help

**Comment by YNSEE** [comment] 2024-05-22 20:32
Was the issue of [such file or directory] ever resolved in terminal? I'm not sure how to successfully complete this fix

**Comment by kang49** [comment] 2024-05-22 20:43
> Was the issue of [such file or directory] ever resolved in terminal? I'm not sure how to successfully complete this fix

All such problems can be solved. And every time it will happen from doing the wrong steps.

**Comment by YNSEE** [comment] 2024-05-22 20:46
> All such problems can be solved. And every time it will happen from doing the wrong steps.

Do you recall what the wrong step was? I executed the command after quitting the game, prior to agreement. What am I missing?

**Comment by kang49** [comment] 2024-05-22 20:51
> > All such problems can be solved. And every time it will happen from doing the wrong steps.
> 
> 
> 
> Do you recall what the wrong step was? I executed the command after quitting the game, prior to agreement. What am I missing?

Everyone who found this problem, their execute that commands before open the game and waiting it to try downloading.

Step:
Open the game > wait a sec > it's can't continue download or stuck > execute commands > retry

**Comment by YNSEE** [comment] 2024-05-22 20:55
> Everyone who found this problem, their execute that commands before open the game and waiting it to try downloading.
> 
> Step: Open the game > wait a sec > it's can't continue download or stuck > execute commands > retry

Still same issue, unfortunately. Thank you for offering assistance though! I will just wait for a permeant fix.

**Comment by yorgetsuten** [comment] 2024-05-22 21:27
> > Everyone who found this problem, their execute that commands before open the game and waiting it to try downloading.
> > Step: Open the game > wait a sec > it's can't continue download or stuck > execute commands > retry
> 
> Still same issue, unfortunately. Thank you for offering assistance though! I will just wait for a permeant fix.

what are you doing exatly? as i understand, just the fact there is no dir is not necessarily an issue. it was the same for me until the download started

**Comment by YNSEE** [comment] 2024-05-22 21:33
> what are you doing exatly? as i understand, just the fact there is no dir is not necessarily an issue. it was the same for me until the download started
Initially: open game > get to user agreement > quit > run command > try again and still get the frozen screen

I may have interrupted prior advice wrong, but i also attempted open game > allow game to progress to the error > quit > run command > try again and still encounter issue

I have reinstalled the game for each attempt to ensure I had a 'clean' attempt

**Comment by yorgetsuten** [comment] 2024-05-22 22:21
> > what are you doing exatly? as i understand, just the fact there is no dir is not necessarily an issue. it was the same for me until the download started
> > Initially: open game > get to user agreement > quit > run command > try again and still get the frozen screen
> 
> I may have interrupted prior advice wrong, but i also attempted open game > allow game to progress to the error > quit > run command > try again and still encounter issue
> 
> I have reinstalled the game for each attempt to ensure I had a 'clean' attempt

the thing worked for me: 

open and terminal and execute
```
touch whatever.sh
```
```
nano  whatever.sh
```

then copy and paste there this script
```
BASEDIR="/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Client/Saved/Resources/1.0.0"
CACHEDIR="/Users/$USER/Downloads/wuwaScript"
APP_NAME="com.kurogame.wutheringwaves.global"

LATESTMV=""

mkdir -p "$CACHEDIR"

check_if_complete() {
  file=$1
  filesize=$(stat -f%z "$file")
  sleep 1
  new_filesize=$(stat -f%z "$file")
  echo "old:" "$filesize" "new:" "$new_filesize"
  if [ "$filesize" -eq "$new_filesize" ]; then
    return 0
  else
  if [ "$LATESTMV" = "${file%.download}" ]; then
        sleep 1
        osascript -e "tell application \"$APP_NAME\" to quit with force"
        # Move file from cache to current path
        rm "${file}"
        cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
        echo "✅ This Download section is completed. You can reopen you game again!"
  fi
    return 1
  fi
}

while true; do
  for file in $(find "$BASEDIR" -name "*.download"); do
    if check_if_complete "$file"; then
      if [ "$LATESTMV" = "${file%.download}" ]; then
        sleep 1
        osascript -e "tell application \"$APP_NAME\" to quit with force"
        # Move file from cache to current path
        rm "${file}"
        cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
        echo "✅ This Download section is completed. You can reopen you game again!"
      else
        echo "$file => ${file%.download}"
        mv "$file" "${file%.download}"
        # Copy the file to cache directory
        cp "${file%.download}" "$CACHEDIR"
        LATESTMV="${file%.download}"
      fi
    fi
  done
  sleep 1
done
```

press control+X, Y and then Enter or Tab
in the same terminal window execute 
```
chmod +x whatever.sh
```
```
./whatever.sh
```
it probably will say that dir does not exist. Don't close the terminal window and launch a game.

**Comment by YNSEE** [comment] 2024-05-22 23:23
> the thing worked for me:
> 
> open and terminal and execute
> 
> ```
> touch whatever.sh
> ```
> 
> ```
> nano  whatever.sh
> ```
> 
> then copy and paste there this script
> 
> ```
> BASEDIR="/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Client/Saved/Resources/1.0.0"
> CACHEDIR="/Users/$USER/Downloads/wuwaScript"
> APP_NAME="com.kurogame.wutheringwaves.global"
> 
> LATESTMV=""
> 
> mkdir -p "$CACHEDIR"
> 
> check_if_complete() {
>   file=$1
>   filesize=$(stat -f%z "$file")
>   sleep 1
>   new_filesize=$(stat -f%z "$file")
>   echo "old:" "$filesize" "new:" "$new_filesize"
>   if [ "$filesize" -eq "$new_filesize" ]; then
>     return 0
>   else
>   if [ "$LATESTMV" = "${file%.download}" ]; then
>         sleep 1
>         osascript -e "tell application \"$APP_NAME\" to quit with force"
>         # Move file from cache to current path
>         rm "${file}"
>         cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
>         echo "✅ This Download section is completed. You can reopen you game again!"
>   fi
>     return 1
>   fi
> }
> 
> while true; do
>   for file in $(find "$BASEDIR" -name "*.download"); do
>     if check_if_complete "$file"; then
>       if [ "$LATESTMV" = "${file%.download}" ]; then
>         sleep 1
>         osascript -e "tell application \"$APP_NAME\" to quit with force"
>         # Move file from cache to current path
>         rm "${file}"
>         cp "$CACHEDIR/$(basename "${LATESTMV}")" "$LATESTMV"
>         echo "✅ This Download section is completed. You can reopen you game again!"
>       else
>         echo "$file => ${file%.download}"
>         mv "$file" "${file%.download}"
>         # Copy the file to cache directory
>         cp "${file%.download}" "$CACHEDIR"
>         LATESTMV="${file%.download}"
>       fi
>     fi
>   done
>   sleep 1
> done
> ```
> 
> press control+X, Y and then Enter or Tab in the same terminal window execute
> 
> ```
> chmod +x whatever.sh
> ```
> 
> ```
> ./whatever.sh
> ```
> 
> it probably will say that dir does not exist. Don't close the terminal window and launch a game.

still ended with the failed to get patch list error. thanks for trying to help!

**Comment by SHSIDCJ** [comment] 2024-05-23 00:16
> > what if i cant even open the game tho other games like genshin and hsr always worked fine for me... i also changed to .games directory but it just crashes. I remember opening it once the first time but i just closed it on accident
> 
> you should try to reinstall the game or playcover if it won't help

AH ok i'll try ty

**Comment by cal099** [comment] 2024-05-23 00:29
so will it just not work unless you use the command or will this issue be fixed in the future (like is a file problem or smth)

**Comment by azaryabernard** [comment] 2024-05-23 02:20
@YNSEE 
> > it probably will say that dir does not exist. Don't close the terminal window and launch a game.
> 
> still ended with the failed to get patch list error. thanks for trying to help!

I'm using App Cleaner, just in case, to fully delete the app and its file, after that when I booted it up, the user agreement appeared again. I followed the person saying to close it afterwards and put the one-liner code, but noticed that the file actually hasn't been created yet (so the command return "no such file or directory"). 

So I open the game again, agree to the user agreement, then when the game was stuck during the "checking launcher resource version" and BEFORE the error came up, I put the one-liner code, and voila it started loading and downloading the patch!

**Comment by boiwertz** [comment] 2024-05-23 02:52
Okay great! Anyone else able to actually get in? I've tapped the screen a million times after choosing a server but it won't proceed. I've tried clearing the patch and redownloading ~6.8 GB of data but to no avail. Server issue, perhaps?

**Comment by bHaRatH9035** [comment] 2024-05-23 04:04
Hi 

I am facing gateway timeout what can I do to fix this ?

<img width="1100" alt="image" src="https://github.com/PlayCover/PlayCover/assets/40002319/e033fa27-f5e9-4d66-b232-c223128e30e6">

**Comment by azaryabernard** [comment] 2024-05-23 04:10
<img width="1728" alt="Screenshot 2024-05-23 at 06 08 23" src="https://github.com/PlayCover/PlayCover/assets/55510214/704c124a-a948-4e7b-9ba4-036e96befc66">
Maybe connection issue, I've been playing this game smoothly, except the mouse control, using trackpad for the camera is much better for some reason. Funnily enough, they've already implemented several keybinds native on the app, maybe preparing for the upcoming official mac app.

**Comment by khoadangnguyenn** [comment] 2024-05-23 06:38
> > Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> > No other voodoo necessary. Automatically continue to work even if Kuro push updates
> > ```
> > rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> > its work for me, thank you very much !!

**Comment by khoadangnguyenn** [comment] 2024-05-23 06:39
> ### App Store link
> https://apps.apple.com/th/app/wuthering-waves/id6475033368?platform=ipad
> 
> ### Current issues
> * [ ]  Game fails to install
> * [ ]  Game fails to open
> * [ ]  Game crashes randomly during gameplay
> * [ ]  Game does not work with keymapping
> * [ ]  Game experiences graphical issues or broken UI
> * [x]  Game fails to connect to servers or complete download
> 
> ### More details
> Using nightly 749 MacOS: Sonoma 14.4.1 MacBook Air M1 Ram 8GB Game version: 1.0.0
> 
> Game can't download full game files. <img alt="Screenshot 2024-05-21 at 22 53 12" width="1440" src="https://private-user-images.githubusercontent.com/81503963/332497785-3c987f7e-247e-4db9-87a7-fa16d597c05d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDY2MDQsIm5iZiI6MTcxNjQ0NjMwNCwicGF0aCI6Ii84MTUwMzk2My8zMzI0OTc3ODUtM2M5ODdmN2UtMjQ3ZS00ZGI5LTg3YTctZmExNmQ1OTdjMDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA2MzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3Y2U2YTE1MTllNGQ2YjhmY2Q4OWFhNWI3MDg2M2ExZjY0MzY2ODMyYTAwYTg3NzlkNTcyYjczOGMxZjBiNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4m35AVLup3QgcAJG1eEkPeQ6RTICrL255rqTlRwSzc">
> 
> ### Crash log
> _No response_
> 
> ### What version of PlayCover are you using?
> Nightly/beta (please specify build number)
> 
> ### What version of macOS are you using?
> Sonoma (macOS 14)
> 
> ### Issue Languagesdf
> * [x]  Yes my issue is written in English

**Comment by MizuBinga** [comment] 2024-05-23 14:55
Thanks it worked :)

**Comment by flowersyrup** [comment] 2024-05-23 22:55
I was able to solve this issue however Im not able to sign in I linked my Wuthering Waves account to my apple id and it just gives me the failed to sign in error :(

**Comment by kang49** [comment] 2024-05-24 05:15
> I was able to solve this issue however Im not able to sign in I linked my Wuthering Waves account to my apple id and it just gives me the failed to sign in error :(

Install game in your iPhone or another platform and just go to the setting > account center > link your account with X or anything.

**Comment by khojyk** [comment] 2024-06-03 10:02
> > Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> > No other voodoo necessary. Automatically continue to work even if Kuro push updates
> > ```
> > rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> > ```
> 
> PlayTools Fix Patch: [Ryu-ga/PlayTools@d9fa41c](https://github.com/Ryu-ga/PlayTools/commit/d9fa41c059b6b8f6d1f74b6c78efe7d80cd11417) If I cannot find good alternative solution, I will PR this. This patch fixes WuWa install error and ToF login error.
> 
> Unreal Engine use file path from `ConvertToIOSPath` in their source code. They separated read path and write path. In iOS, these functions work well, But in MacOS they go like this. original path => '../../Content/Some_Content' read path '../../Content/Some_Content' => '/Users/<User>/Library/Containers/<App>/<Documents or Library>//Users/<User>/Library/Containers/<App>/<Documents or Library>/<Some Path>/Content/Some_Content' write path '../../Content/Some_Content' => '/Users/<User>/Library/Containers/<App>/<Documents or Library ( not same to read path )>//Users/<User>/Library/Containers/<App>/<Documents or Library (same to read path )>/<Some Path>/Content/Some_Content'

thank you so much! it helped indeed! very useful 👍🏻

**Comment by xyph0** [comment] 2024-06-08 20:28
[Wuwa.playmap.txt](https://github.com/user-attachments/files/15749611/Wuwa.playmap.txt)
just made a keymapping 
delete .txt before using

**Comment by rqiin** [comment] 2024-06-10 05:37
hiii no matter what i do (tried both the nightly & beta 2 PlayCover versions + trying out all the solutions people said in the thread), terminal keeps saying 

> rm: /Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory

I've tried putting it before the User & Agreements, during the checking launcher resource version, & after i quit the game but the result is the same

I've also tried using the chinese version of the code instead but it doesnt work either (since the file isnt the chinese version)

honestly not sure what to do, im running on M1

**Comment by Catta1997** [comment] 2024-06-10 06:52
> hiii no matter what i do (tried both the nightly & beta 2 PlayCover versions + trying out all the solutions people said in the thread), terminal keeps saying
> 
> > rm: /Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory
> 
> I've tried putting it before the User & Agreements, during the checking launcher resource version, & after i quit the game but the result is the same
> 
> I've also tried using the chinese version of the code instead but it doesnt work either (since the file isnt the chinese version)
> 
> honestly not sure what to do, im running on M1

do also 
```
ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
```

**Comment by rqiin** [comment] 2024-06-10 11:31
> > hiii no matter what i do (tried both the nightly & beta 2 PlayCover versions + trying out all the solutions people said in the thread), terminal keeps saying
> > > rm: /Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/jennifer/Library/Containers/com.kurogame.wutheringwaves.global/Data: No such file or directory
> > 
> > 
> > I've tried putting it before the User & Agreements, during the checking launcher resource version, & after i quit the game but the result is the same
> > I've also tried using the chinese version of the code instead but it doesnt work either (since the file isnt the chinese version)
> > honestly not sure what to do, im running on M1
> 
> do also
> 
> ```
> ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> ```

hihii!! thank you so much for the help, i kind of came to the realisation that the users in my mac are a bit jumbled up so i just located WuWa from PlayCover in Finder, and replaced $USER with the user the file is in and it worked! Its probably due to renaming my user a while back so now everything is jumbled up 😭

**Comment by rqiin** [comment] 2024-06-10 11:54
it somehow doesnt work again, after downloading resources it says quit and reopen to play so i did that but it wouldnt open anymore

**Comment by Jack-laoniu** [comment] 2024-07-05 06:16
> [Wuwa.playmap.txt](https://github.com/user-attachments/files/15749611/Wuwa.playmap.txt) just made a keymapping delete .txt before using

thanks for share , but this is use to xbox controller not keyboard

**Comment by Bhpsngum** [comment] 2024-08-18 09:29
> Here is a much faster command. Open WuWa to the User Agreements screen, quit it and pop it right into your terminal.
> 
> No other voodoo necessary. Automatically continue to work even if Kuro push updates
> 
> ```
> rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Library/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
> ```

For anyone successfully doing this before, please check how heavy WuWa is again on your local device, I've been cleaning up my storage recently and noticed that it takes more space in the disk (31GB) than it usually is (~11GB) - as for 1.2 update.

The culprit is under the `[WuWa Container]/Data/Documents` folder, it has the same duplication issue as the `[WuWa Container]/Data/Library/` one. For safety, I ran this command and it works for me, halved the amount of space used by WuWa:

(quit the game before doing so btw, prepend `sudo` to the command it fails due to no permissions)

```bash
rm -r /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Documents/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data /Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data/Documents/Users/$USER/Library/Containers/com.kurogame.wutheringwaves.global/Data
```

CN ver:
```bash
rm -r /Users/$USER/Library/Containers/com.kurogame.mingchao/Data/Documents/Users/$USER/Library/Containers/com.kurogame.mingchao/Data && ln -sf /Users/$USER/Library/Containers/com.kurogame.mingchao/Data /Users/$USER/Library/Containers/com.kurogame.mingchao/Data/Documents/Users/$USER/Library/Containers/com.kurogame.mingchao/Data
```

**Closed as completed** 2024-09-12 18:37 UTC
Labels: game-support
