### ISSUE TITLE
[Bug]:  Parameter Error

### ISSUE THREAD

**Issue by 00UNPRO00** [PlayCover/PlayCover#907] opened 2023-04-03 13:11 UTC
### Describe the bug

I can't login cause it says parameter error and I don't know how.
<img width="1470" alt="Screenshot 2023-04-03 at 21 07 46" src="https://user-images.githubusercontent.com/129649161/229519562-5bb58ebc-3809-465f-b99a-9695e9a4905f.png">

### Steps to reproduce

none

### Expected behaviour

Hoping Playcover will run smoothly

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-04-03 13:27
Duplicate of #741 and #877.

**Closed as not planned by TheMoonThatRises** 2023-04-03 13:27 UTC
Labels: invalid
