### ISSUE TITLE
[Bug]: Genshin Impact display "vertically" and incorrectly

### ISSUE THREAD

**Issue by kknownn** [PlayCover/PlayCover#646] opened 2022-12-28 07:18 UTC
### Describe the bug

The game just display in a vertical way in both windowed mode and fullscreen mode

Using MacBook Air M1 w/ macOS Ventura Beta 13.2 (a) (22D7750270d)

<img width="1049" alt="Screenshot 2565-12-28 at 14 12 01" src="https://user-images.githubusercontent.com/57518024/209773166-1faa0114-f395-4d24-8fa6-c17fdbaa1040.png">
<img width="1680" alt="Screenshot 2565-12-28 at 14 12 14" src="https://user-images.githubusercontent.com/57518024/209773191-5f69f62e-0ed3-4bbd-9c48-35378b1863e7.png">

### Steps to reproduce

Normally open the game with this configuration:

 
<img width="1012" alt="Screenshot 2565-12-28 at 14 17 19" src="https://user-images.githubusercontent.com/57518024/209773838-39b43880-8a8c-4770-af5b-5d63614629b6.png">

### Expected behaviour

The game display vertically.

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kknownn** [comment] 2022-12-28 07:19
I'm so sorry if my English sucks 🥲

**Comment by TheMoonThatRises** [comment] 2022-12-28 14:38
Duplicate of PlayCover/PlayTools#64.

**Comment by IsaacMarovitz** [comment] 2022-12-29 22:46
Duplicate

**Closed as not planned by IsaacMarovitz** 2022-12-29 22:46 UTC
Labels: bug
