### ISSUE TITLE
[Game Support]: Blue Archive (Global) stuck at loading

### ISSUE THREAD

**Issue by mangokamen** [PlayCover/PlayCover#1019] opened 2023-06-28 02:48 UTC
### App Store link

https://apps.apple.com/us/app/blue-archive/id1571873795

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

Game installs and opens successfully, but stuck at the loading screen.

After game opens, at loading screen, game goes through verifying phase, but stuck at:

Resetting game data... [Data Initialize...0%]

No progress after this phase no matter how long I waited, also tried disable SIP, no luck/

Unsure if there is problem connecting to server or it's something local.

My machine is M2 pro, OS 13.4.1 (22F82)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment] 2023-06-28 03:24
If you use 3.0.0, the behavior changes
It will start and download files... but fails on anticheat :/

**Comment by mangokamen** [comment] 2023-06-28 04:15
> If you use 3.0.0, the behavior changes It will start and download files... but fails on anticheat :/

It happened to me on Blue Archive JP during Playcover 2.0.5, always "use of unauthorized app" and quit, but after I tweak with some of the settings I managed to get it to work properly, forgot what I did, but let me update to 3.0.0 and do some experiment. If I figured out I'll post the solution here.

**Comment by mangokamen** [comment] 2023-06-28 04:54
> If you use 3.0.0, the behavior changes It will start and download files... but fails on anticheat :/

I've rolled back to 2.0.5 and tried Blue Archive JP it gave me no "use of unauthorized app" issue, I can login successfully. Now 3.0.0 is giving me "unauthorized" issue (anticheat?) on both Global and JP version.

And I have also discovered in Playcover 3.0.0, the checkbox in options that allows BA Global to pass "data initialization" phase is "start app in root folder", if this option is not checked, then BA Global stuck at "data initializing...0%". After the checkbox is checked, BA Global can pass data initialization phase, but still cannot login due to "unauthorized".

Maybe adding "start app in root folder" to build 2.0.5 might be a workaround? Or maybe it can help with better understanding what the problem is?

Hope this helps.

**Comment by KyonP** [comment] 2023-07-27 03:24
still there is no solution for this? Unauthorized message shown up

**Comment by chuyaowang** [comment] 2023-07-27 17:03
I got `User Verification Failed. Returning to Title Screen.` after entering my nexon ID and password. It seems to be related to the game, since I was also stopped by this message in sideloadly. However, I did not encounter the unauthorized messages described above.

<img width="1440" alt="Screen Shot 2023-07-28 at 01 07 41" src="https://github.com/PlayCover/PlayCover/assets/85109348/4d9364cc-1a48-4c74-a833-cbe91e3f47c4">

**Comment by ohaiibuzzle** [comment] 2023-07-27 17:35
@chuyaowang That is basically the error given if somehow Nexon's NGSM server was blocked (`api.ngsm.nexon.com`). If you do not, it will fail with error 130001 and then quit

**Comment by chuyaowang** [comment] 2023-07-30 13:30
@ohaiibuzzle Is there a fix for it? I don't think I set any firewall rules blocking this server.

**Comment by KyonP** [comment] 2023-07-31 12:48
I have a similar issue. written in Korean, but it seem like similar  error message @chuyaowang posted screenshot.

**Comment by ohaiibuzzle** [comment] 2023-07-31 16:36
@chuyaowang I am trying to reverse engineer Ngsm to see what the heck is up, but as far as I can tell, what they checked, we've patched them already
So it's probably some iOS-specific behaviors I have no knowledge of. Could use some help there
It's a bit annoying since it's native C instead of ObjC so there is no easy runtime-level fix.

**Comment by seia-soto** [comment] 2023-08-10 06:04
Various client fingerprinting for identification can be used. It was hard for me to find out what's wrong since I am not developing iOS. One thing strange is that there was no problem running Blue Archive on jailbroken idevice on iOS 15 even patching system methods. I think patching the file system path only available to iOS or iPad environment might help.

**Comment by ohaiibuzzle** [comment] 2023-08-10 20:06
@seia-soto If you throw the game library (UnityFramework) into Ghidra, you can kinda see where checks are happening (look for the string /bin/bash, being one of the files checked)

But aside from checking `apt` and Bash, there appears to be other checks that looks very weird to me

**Comment by 78796a** [comment] 2023-09-20 09:47
It seems like you can bypass Blue Archive (Global)'s  jailbreak detection by disabling Tweak injection (at least it works on jailbroken iPhone ), but that means removing PlayTools, and therefore you can't start app at root directory, and this leads to stucking at "Resetting game data... [Data Initialize...0%]"...... Yeah, this is an endless loop.

By the way ,only disabling tweak injection doesn't work for Blue Archive JP. Jailbreak bypass within PlayCover 2.0.5 works perfectly, but fails in 3.0.0 beta. I don't know how thing works like that...

**Comment by hotsno** [comment] 2023-11-10 20:02
As the above message mentions, it seems like there's a regression in the "Enable Jailbreak Bypass (Experimental)" setting from 2.0.5 to 3.0.0. Blue Archive JP seems to work fine on 2.0.5 with that setting checked, but on 3.0.0 I get the "use of unauthorized app" message.

Maybe if this regression is fixed it'll help the global version as well?

Edit: [nvm, probably not](https://github.com/PlayCover/PlayCover/issues/296#issuecomment-1237479564)

**Comment by TheMoonThatRises** [comment] 2023-11-27 20:52
Closing in favour of #1231.

**Closed as completed by TheMoonThatRises** 2023-11-27 20:52 UTC
Labels: game-support
