### ISSUE TITLE
[Bug]: version issues

### ISSUE THREAD

**Issue by Midnights-hub** [PlayCover/PlayCover#1519] opened 2024-06-20 07:19 UTC
### Describe the bug

when i install the latest version3.0.0beta2,it will automatically become version2.0 after a period of. time.

### Steps to reproduce

when i install the latest version3.0.0beta2,it will automatically become version2.0 after a period of. time.

### Expected behaviour

i need a solution

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Catta1997** [comment] 2024-06-20 07:40
There is a bug and PlayCover detect 2.0 > 3.0.0 b2 . Are you sure you not updated it with "new update" popup? Also try to install Nightly

**Comment by TheMoonThatRises** [comment] 2024-06-20 07:52
Duplicate of #1299. Make sure to disable auto-updates before installing a 3.0.0 version of PlayCover.

**Closed as not planned by TheMoonThatRises** 2024-06-20 07:52 UTC
Labels: bug

**Comment by Midnights-hub** [comment] 2024-06-20 14:45
ok I'll try the nightly version later
