### ISSUE TITLE
[App Support]: KartRider: Drift

### ISSUE THREAD

**Issue by cy920820** [PlayCover/PlayCover#1444] opened 2024-04-13 09:13 UTC
### App Store link

https://apps.apple.com/us/app/kartrider-rush/id1466736988

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

I can't open it

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-05-03 21:02
Duplicate of #797.

**Closed as not planned by TheMoonThatRises** 2024-05-03 21:02 UTC
Labels: app-support
