### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by frappuccino16** [PlayCover/PlayCover#1044] opened 2023-07-17 09:51 UTC
### Describe the bug

After starting the Blue Archive, "use of unauthorized apps." is displayed and the game is forcefully terminated.
<img width="532" alt="スクリーンショット 2023-07-17 18 37 16" src="https://github.com/PlayCover/PlayCover/assets/136308430/1350ccb1-07a4-4d09-9b30-352800ec4a6e">

The reason my English is not correct is because I used a translation app

### Steps to reproduce

Just start the Blue Archive.

### Expected behaviour

Turn on the game without force-quitting

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-09-03 20:48
Duplicate of #906.

**Closed as not planned by TheMoonThatRises** 2023-09-03 20:48 UTC
Labels: game-support
