### ISSUE TITLE
[Bug]: Honkai Star Rail CN stuck on loading screen

### ISSUE THREAD

**Issue by YukinoYume0** [PlayCover/PlayCover#992] opened 2023-06-08 15:28 UTC
### Describe the bug

Honkai Star Rail CN version has no sound and will not enter the game after completing all updates/checks
Other versions work fine, so the issue is exclusive to CN version
*Genshin CN version works fine

### Steps to reproduce

1. Download IPA https://decrypt.day/app/id1523037824
2. There is no sound upon opening
3. Login successful as described in the doc
4. Complete all updates all checks
5. Game stuck on infinite loading screen no button no error report

### Expected behaviour

There should be background music upon opening the game
After all checks complete, should be able to enter the game

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-06-09 02:38
Duplicate of #921.

**Closed as not planned by TheMoonThatRises** 2023-06-09 02:38 UTC
Labels: duplicate, game-support
