### ISSUE TITLE
[Feature]: Add support to install apps to external disk

### ISSUE THREAD

**Issue by Lucas04-nhr** [PlayCover/PlayCover#1124] opened 2023-10-05 07:51 UTC
### Is your feature request related to a problem?

No, my feature request is not related to any problem.

### Describe the solution you'd like

The built-in storage of my Mac is small, so I want to install the app and locate the data of the side load app to an external disk. However, the only way to solve this problem is to add symlink via terminal, this isn’t convenient.

### Anything else?

There’s nothing else.

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment] 2023-10-06 04:10
Duplicate of #1096

**Closed as not planned by zanderp25** 2023-10-06 04:10 UTC
Labels: enhancement
