### ISSUE TITLE
[Bug]: After closing and restarting play cover, the downloaded games always disappear in the app library.

### ISSUE THREAD

**Issue by zhengyuhan050427** [PlayCover/PlayCover#1380] opened 2024-02-09 05:48 UTC
### Describe the bug

After closing and restarting play cover, the downloaded games always disappear in the app library.

### Steps to reproduce

1.close play cover
2.restart it
3.downloaded games always disappear
4.delete play cover
5.re-install play cover
6.my game is back

### Expected behaviour

find a solution not to re-install it for so many times

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ipiiia** [comment] 2024-02-10 21:24
I have the same problem.

**Comment by TheMoonThatRises** [comment] 2024-02-12 20:40
Duplicate of #1299. Turn off auto-updates before updated to 3.0.0 Beta 2.

**Closed as not planned by TheMoonThatRises** 2024-02-12 20:40 UTC
Labels: bug
