### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KU-Baha** [PlayCover/PlayCover#982] opened 2023-06-03 15:50 UTC
### Describe the bug

Parameter error in genshin impact login

### Steps to reproduce

Login

### Expected behaviour

Authorization

### Crash log

<img width="1143" alt="Screenshot 2023-06-03 at 21 49 32" src="https://github.com/PlayCover/PlayCover/assets/80050571/47265dcc-75cd-42ed-97f2-f47c1e7706a4">

<img width="744" alt="Screenshot 2023-06-03 at 21 49 36" src="https://github.com/PlayCover/PlayCover/assets/80050571/b48d5bd7-3b8e-475c-a3f3-f227d663a3f8">

Parameter error

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-06-03 16:04
Duplicate of #741 and #877.

**Closed as not planned by TheMoonThatRises** 2023-06-03 16:04 UTC
Labels: duplicate, invalid, game-support

**Comment by KU-Baha** [comment] 2023-06-04 13:43
> Duplicate of #741 and #877.

thanks
