### ISSUE TITLE
[Game Support]: Minecraft 1.20.41

### ISSUE THREAD

**Issue by Stonemage** [PlayCover/PlayCover#1222] opened 2023-11-17 00:18 UTC
### App Store link

https://apps.apple.com/us/app/minecraft/id479516143

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [X] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Upon opening, Minecraft runs for 2-3 seconds before freezing completely and must be Force Quit. 

Have attempted with SIP both disabled and enabled: same result.
Have attempted with Enable Jailbreak Bypass: same result.

Game will not run with PlayTools removed.

Running the nightly build, have selected the app type as 'game' (won't run without it).

Macbook Pro, M3 Max, Mac15,8

No crash log appears to be created, as the game freezes up hard.

Log:
-----
Version 14.1.1 (Build 23B2082)
Installing PlayTools
Copying PlayTools to Frameworks
Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.private.tcc.allow</key><array><string>kTCCService</string><string>kTCCServiceAll</string><string>kTCCServiceAddressBook</string><string>kTCCServiceCalendar</string><string>kTCCServiceReminders</string><string>kTCCServiceLiverpool</string><string>kTCCServiceUbiquity</string><string>kTCCServiceShareKit</string><string>kTCCServicePhotos</string><string>kTCCServicePhotosAdd</string><string>kTCCServiceMicrophone</string><string>kTCCServiceCamera</string><string>kTCCServiceMediaLibrary</string><string>kTCCServiceSiri</string><string>kTCCServiceAppleEvents</string><string>kTCCServiceAccessibility</string><string>kTCCServicePostEvent</string><string>kTCCServiceLocation</string><string>kTCCServiceSystemPolicyAllFiles</string><string>kTCCServiceSystemPolicySysAdminFiles</string><string>kTCCServiceSystemPolicyDeveloperFile</string><string>kTCCServiceSystemPolicyDocumentsFolder</string></array><key>com.apple.security.app-sandbox</key><true/><key>com.apple.security.assets.movies.read-write</key><true/><key>com.apple.security.assets.music.read-write</key><true/><key>com.apple.security.assets.pictures.read-write</key><true/><key>com.apple.security.device.audio-input</key><true/><key>com.apple.security.device.bluetooth</key><true/><key>com.apple.security.device.camera</key><true/><key>com.apple.security.device.microphone</key><true/><key>com.apple.security.device.usb</key><true/><key>com.apple.security.files.downloads.read-write</key><true/><key>com.apple.security.files.user-selected.read-write</key><true/><key>com.apple.security.network.client</key><true/><key>com.apple.security.network.server</key><true/><key>com.apple.security.personal-information.addressbook</key><true/><key>com.apple.security.personal-information.calendars</key><true/><key>com.apple.security.personal-information.location</key><true/><key>com.apple.security.print</key><true/><key>com.apple.security.temporary-exception.sbpl</key><array><string>(allow user-preference-write (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow user-preference-read (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow file* file-read* file-write* file-write-data file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Containers/io.playcover.PlayCover&quot;))</string><string>(allow file* file-read* file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Frameworks/PlayTools.framework&quot;))</string><string>(allow file* file-read* (subpath &quot;/Users/aforbes/Library/Group Containers/&quot;))</string><string>(allow network* ipc-posix*)</string></array></dict></plist>

System Integrity Protection status: enabled.

/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app: replacing existing signature

/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/PlugIns/AKInterface.bundle: replacing existing signature

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
Identifier=com.mojang.minecraftpe
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1453263 flags=0x2(adhoc) hashes=45404+7 location=embedded
Signature=adhoc
Info.plist entries=59
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=18263
Internal requirements count=0 size=12

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.app-sandbox</key><true/><key>com.apple.security.assets.movies.read-write</key><true/><key>com.apple.security.assets.music.read-write</key><true/><key>com.apple.security.assets.pictures.read-write</key><true/><key>com.apple.security.device.audio-input</key><true/><key>com.apple.security.device.bluetooth</key><true/><key>com.apple.security.device.camera</key><true/><key>com.apple.security.device.microphone</key><true/><key>com.apple.security.device.usb</key><true/><key>com.apple.security.files.downloads.read-write</key><true/><key>com.apple.security.files.user-selected.read-write</key><true/><key>com.apple.security.network.client</key><true/><key>com.apple.security.network.server</key><true/><key>com.apple.security.personal-information.addressbook</key><true/><key>com.apple.security.personal-information.calendars</key><true/><key>com.apple.security.personal-information.location</key><true/><key>com.apple.security.print</key><true/><key>com.apple.security.temporary-exception.sbpl</key><array><string>(allow user-preference-write (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow user-preference-read (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow file* file-read* file-write* file-write-data file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Containers/io.playcover.PlayCover&quot;))</string><string>(allow file* file-read* file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Frameworks/PlayTools.framework&quot;))</string><string>(allow file* file-read* (subpath &quot;/Users/aforbes/Library/Group Containers/&quot;))</string><string>(allow network* ipc-posix*)</string></array></dict></plist>

/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/PlugIns/AKInterface.bundle: replacing existing signature

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
Identifier=com.mojang.minecraftpe
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1453263 flags=0x2(adhoc) hashes=45404+7 location=embedded
Signature=adhoc
Info.plist entries=59
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=18263
Internal requirements count=0 size=12

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.app-sandbox</key><true/><key>com.apple.security.assets.movies.read-write</key><true/><key>com.apple.security.assets.music.read-write</key><true/><key>com.apple.security.assets.pictures.read-write</key><true/><key>com.apple.security.device.audio-input</key><true/><key>com.apple.security.device.bluetooth</key><true/><key>com.apple.security.device.camera</key><true/><key>com.apple.security.device.microphone</key><true/><key>com.apple.security.device.usb</key><true/><key>com.apple.security.files.downloads.read-write</key><true/><key>com.apple.security.files.user-selected.read-write</key><true/><key>com.apple.security.network.client</key><true/><key>com.apple.security.network.server</key><true/><key>com.apple.security.personal-information.addressbook</key><true/><key>com.apple.security.personal-information.calendars</key><true/><key>com.apple.security.personal-information.location</key><true/><key>com.apple.security.print</key><true/><key>com.apple.security.temporary-exception.sbpl</key><array><string>(allow user-preference-write (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow user-preference-read (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow file* file-read* file-write* file-write-data file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Containers/io.playcover.PlayCover&quot;))</string><string>(allow file* file-read* file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Frameworks/PlayTools.framework&quot;))</string><string>(allow file* file-read* (subpath &quot;/Users/aforbes/Library/Group Containers/&quot;))</string><string>(allow network* ipc-posix*)</string></array></dict></plist>

/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/PlugIns/AKInterface.bundle: replacing existing signature

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
Identifier=com.mojang.minecraftpe
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1453263 flags=0x2(adhoc) hashes=45404+7 location=embedded
Signature=adhoc
Info.plist entries=59
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=18263
Internal requirements count=0 size=12

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.app-sandbox</key><true/><key>com.apple.security.assets.movies.read-write</key><true/><key>com.apple.security.assets.music.read-write</key><true/><key>com.apple.security.assets.pictures.read-write</key><true/><key>com.apple.security.device.audio-input</key><true/><key>com.apple.security.device.bluetooth</key><true/><key>com.apple.security.device.camera</key><true/><key>com.apple.security.device.microphone</key><true/><key>com.apple.security.device.usb</key><true/><key>com.apple.security.files.downloads.read-write</key><true/><key>com.apple.security.files.user-selected.read-write</key><true/><key>com.apple.security.network.client</key><true/><key>com.apple.security.network.server</key><true/><key>com.apple.security.personal-information.addressbook</key><true/><key>com.apple.security.personal-information.calendars</key><true/><key>com.apple.security.personal-information.location</key><true/><key>com.apple.security.print</key><true/><key>com.apple.security.temporary-exception.sbpl</key><array><string>(allow user-preference-write (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow user-preference-read (preference-domain &quot;.GlobalPreferences&quot;))</string><string>(allow file* file-read* file-write* file-write-data file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Containers/io.playcover.PlayCover&quot;))</string><string>(allow file* file-read* file-read-metadata file-ioctl (subpath &quot;/Users/aforbes/Library/Frameworks/PlayTools.framework&quot;))</string><string>(allow file* file-read* (subpath &quot;/Users/aforbes/Library/Group Containers/&quot;))</string><string>(allow network* ipc-posix*)</string></array></dict></plist>

/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/PlugIns/AKInterface.bundle: replacing existing signature

Executable=/Users/aforbes/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
Identifier=com.mojang.minecraftpe
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1453263 flags=0x2(adhoc) hashes=45404+7 location=embedded
Signature=adhoc
Info.plist entries=59
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=18263
Internal requirements count=0 size=12

System Integrity Protection status: enabled.

boot-args	amfi_get_out_of_my_way=0x1 ipc_control_port_options=0

kern.bootargs: 

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2023-11-17 02:08
We tried fixing it. It broke other games so we didn’t merge the fix into the main repo.

**Comment by Stonemage** [comment] 2023-11-17 09:11
> We tried fixing it. It broke other games so we didn’t merge the fix into the main repo.

Did the fix actually work? For me, getting Minecraft working is more important than any other app. Are you able to share a patch I could apply to the source, and compile myself?

**Comment by TheMoonThatRises** [comment] 2023-11-17 18:16
Duplicate of #537.

**Closed as not planned by TheMoonThatRises** 2023-11-17 18:16 UTC
Labels: game-support

**Comment by Stonemage** [comment] 2023-11-17 20:01
> Duplicate of #537.

It's actually not a duplicate. I have realised that the game doesn't crash - only the graphics completely freeze us. The background intro screen music continues to play...

**Comment by GGIEnrike** [comment] 2024-03-15 20:38
Hi, @AkshayanSingla. Do you mind sharing what commit got Minecraft to work?
