### ISSUE TITLE
[Game Support]: Minecraft 1.20.10

### ISSUE THREAD

**Issue by Neosyass** [PlayCover/PlayCover#1040] opened 2023-07-16 09:24 UTC
### App Store link

https://apps.apple.com/fr/app/minecraft/id479516143

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

i have a decrypted ipa
i turned SIP off
i have the nightly build

When i open the Minecraft.ipa in playcover, the app installs, but when i launch it it crashes right away. 

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               minecraftpe [1273]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/Minecraft.app/minecraftpe
Identifier:            com.mojang.minecraftpe
Version:               1.20.10 (1.20.10.01)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-15 22:03:03.3951 +0200
OS Version:            macOS 13.2 (22D49)
Report Version:        12
Anonymous UUID:        8CE4D367-7DF4-95DD-19D4-CF0730811925


Time Awake Since Boot: 300 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001876b47c8

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1273]
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-09-02 22:50
Duplicate of #537.

**Closed as not planned by TheMoonThatRises** 2023-09-02 22:50 UTC
Labels: game-support
