### ISSUE TITLE
[Bug]: Genshin crashes post 4.2 update

### ISSUE THREAD

**Issue by CrashingBootcamp** [PlayCover/PlayCover#1206] opened 2023-11-09 23:37 UTC
### Describe the bug

Have been using Playcover to run Genshin Impact for a while, but as of this week's 4.2 update it crashes on start. Noticed someone posted about a similar issue with screenshot on Reddit (link below, though I didn't see this error screen, just crashed on my end). Running M1 Mac on Sonoma (14.1). https://www.reddit.com/r/PlayCover/comments/17qhfs8/cant_start_genshin_impact/

### Steps to reproduce

Tried to launch genshin as per usual.

### Expected behaviour

normally it would launch.

### Crash log

```shell
Didn't see one myself, but someone else posted one here: https://www.reddit.com/r/PlayCover/comments/17qhfs8/cant_start_genshin_impact/
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ZihouWong** [comment] 2023-11-10 12:34
I got this crash report, I think this is the same problem.

[log.txt](https://github.com/PlayCover/PlayCover/files/13319268/log.txt)

**Comment by MEMORIEmusic** [comment] 2023-11-10 13:32
Right click Genshin -> settings -> misc -> cha ge application type to `public.app-category.games`(latest nightly build required)

**Comment by CrashingBootcamp** [comment] 2023-11-10 17:06
Thank for the quick reply. Only issue is, I don't see that option in settings, attaching screenshots of what my settings window looks like. Appreciate your taking the time to help. 

![Screenshot 2023-11-10 at 9 04 13 AM](https://github.com/PlayCover/PlayCover/assets/95519446/3ec8a80e-7e21-428a-8be3-de12c74cb3c7)
![Screenshot 2023-11-10 at 9 04 42 AM](https://github.com/PlayCover/PlayCover/assets/95519446/3cadde7d-95a4-4e2c-86b6-c92b3f3e147c)
![Screenshot 2023-11-10 at 9 04 46 AM](https://github.com/PlayCover/PlayCover/assets/95519446/ffff3880-1588-450f-aca9-8893b7daa4dd)
![Screenshot 2023-11-10 at 9 04 52 AM](https://github.com/PlayCover/PlayCover/assets/95519446/f9ae877e-60e7-4fe1-b933-1f4340f5bbeb)
![Screenshot 2023-11-10 at 9 04 59 AM](https://github.com/PlayCover/PlayCover/assets/95519446/785ea453-c34b-483e-aad5-89d5900a791a)

**Comment by WZ0616** [comment] 2023-11-10 19:33
I have the same problem, I am the same version (14.1) and I can't open it either

**Comment by nihal2k** [comment] 2023-11-10 20:30
ME too I just updated mac os sonoma 14.1.1 latest version.Now I cant open it crashes ss below
<img width="1440" alt="Screenshot 2023-11-11 at 2 30 04 AM" src="https://github.com/PlayCover/PlayCover/assets/76786577/346c21f9-baaa-4d4a-9c89-67bbf4dffbeb">

**Comment by nihal2k** [comment] 2023-11-10 20:37
> Right click Genshin -> settings -> misc -> cha ge application type to `public.app-category.games`(latest nightly build required)
cha ge application type please explain

**Comment by nihal2k** [comment] 2023-11-10 20:39
holly shit worked thanks @AkshayanSingla 
<img width="1440" alt="Screenshot 2023-11-11 at 2 39 39 AM" src="https://github.com/PlayCover/PlayCover/assets/76786577/e4d4bcd5-932b-4d1e-aca4-bfb01eac2c35">

**Comment by TheMoonThatRises** [comment] 2023-11-10 20:40
Duplicate of #1108.

**Closed as not planned by TheMoonThatRises** 2023-11-10 20:40 UTC
Labels: game-support
