### ISSUE TITLE
[Bug]: Genshin impact

### ISSUE THREAD

**Issue by matejpaulik** [PlayCover/PlayCover#898] opened 2023-03-30 09:05 UTC
### Describe the bug

whenever I go to the party setup in the settings the game crashes, similar to the wishing screen or BP screen. Is there any patch that can fix this?

### Steps to reproduce

just open the game and click on anything from description .

### Expected behaviour

Patch

### Crash log

```shell
none
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by sheng-19** [comment] 2023-03-30 17:12
exactly the same issue over here

**Comment by LinSDK** [comment] 2023-04-01 03:15
This happens when the resolution is set too high. To fix this, I set the resolution to 1080p or lower (custom), since I can't tell the difference anyway.

To be fair, there is a warning on the resolution tab in the app settings that says the game will crash when selecting a resolution that is too high.

**Comment by TheMoonThatRises** [comment] 2023-04-01 03:55
What LinSDK said and duplicate of #885.

**Closed as not planned by TheMoonThatRises** 2023-04-01 03:55 UTC
Labels: bug
