### ISSUE TITLE
[Game Support]: Farlight84

### ISSUE THREAD

**Issue by KyrosWeb** [PlayCover/PlayCover#1389] opened 2024-02-15 16:23 UTC
### App Store link

https://apps.apple.com/it/app/farlight-84/id1673713581

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When try to open it , it shows the splash screen and after that crashes.

### Crash log

```shell
Crashed Thread:        13

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   SolarlandClient [9004]

Application Specific Information:
abort() called

Thread 13 Crashed:
0   libsystem_kernel.dylib        	       0x1877620dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x187799cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1876a5a40 abort + 180
3   SolarlandClient               	       0x103fd5494 0x10058c000 + 61117588
4   SolarlandClient               	       0x1040843e0 0x10058c000 + 61834208
5   SolarlandClient               	       0x1040ebce4 0x10058c000 + 62258404
6   SolarlandClient               	       0x1040b21c8 0x10058c000 + 62022088
7   SolarlandClient               	       0x1046cd6e8 0x10058c000 + 68425448
8   SolarlandClient               	       0x1016d1878 0x10058c000 + 18110584
9   SolarlandClient               	       0x1016cade0 0x10058c000 + 18083296
10  SolarlandClient               	       0x1042d1e18 0x10058c000 + 64249368
11  Foundation                    	       0x18897af14 __NSThread__start__ + 716
12  libsystem_pthread.dylib       	       0x18779a034 _pthread_start + 136
13  libsystem_pthread.dylib       	       0x187794e3c thread_start + 8
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-02-26 03:09
Duplicate of #1026.

**Closed as not planned by TheMoonThatRises** 2024-02-26 03:09 UTC
Labels: game-support
