### ISSUE TITLE
[Bug]: Trying to install an update causes a permission denied error

### ISSUE THREAD

**Issue by souseinu** [PlayCover/PlayCover#1362] opened 2024-01-30 23:42 UTC
### Describe the bug

When I try to download the new version of genshin from both the IPA library and decrypt.day, I get this error message:
xattr: [Errno 13] Permission denied: '/var/folders/lx/zv7dqshx66v76r6pfj8f6fzw0000gn/T/TemporaryItems/NSIRD_PlayCover_OLG1Wd/Payload/GenshinImpact.app/GenshinImpact'

I have tried downloading multiple versions from decrypt.day but to no avail. 
![Screenshot 2024-01-30 at 23 37 19](https://github.com/PlayCover/PlayCover/assets/158231350/3910428b-adc7-43c6-88ae-f6e5e600fa9f)

### Steps to reproduce

Every time I attempt to either download from the IPA library or extract a .ipa file by dragging it directly into the library tab in playcover this error pops up about halfway through.

### Expected behaviour

Usually I am able to drag the files in with no problem. I installed the last update whilst on macOS 14 with no problems.

### What version of PlayCover are you using?
N
Nightly

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Iwasayoung** [comment] 2024-01-30 23:58
My computer is in the same situation

**Comment by tegar09** [comment] 2024-01-31 00:07
I have the exact same problem, just try it before. Even after uninstalled the app data from genshin 4.3 The problem is still the same

**Comment by Miracle-Sakuno** [comment] 2024-01-31 00:23
Excuting an order

`sudo xattr -cr /GenshinImpact.ipa`

Problem solved with PlayCover Nightly 623

**Comment by Iwasayoung** [comment] 2024-01-31 01:30
When I run the above on my computer, the following is displayed
xattr: No such file: /GenshinImpact.ipa

**Comment by Miracle-Sakuno** [comment] 2024-01-31 01:34
> When I run the above on my computer, the following is displayed
> 
> xattr: No such file: /GenshinImpact.ipa

Replace the path with the path of your iPA installation package

**Comment by TheMoonThatRises** [comment] 2024-01-31 01:34
Duplicate of #1349. Use the 623 nightly build.

**Closed as not planned by TheMoonThatRises** 2024-01-31 01:34 UTC
Labels: bug

**Comment by Iwasayoung** [comment] 2024-01-31 01:38
> 注文の実行
> 
> `sudo xattr -cr /GenshinImpact.ipa`
> 
> PlayCover Nightly 623 で問題解決


This was successful but the error still occurs

**Comment by tegar09** [comment] 2024-01-31 04:45
> > 注文の実行
> > 
> > `sudo xattr -cr /GenshinImpact.ipa`
> > 
> > PlayCover Nightly 623 で問題解決
> 
> 
> This was successful but the error still occurs

Hey, have you found the solution? I read in another thread, to use Keka to unzip the ipa file and zip again.
I don't know if it's work or not

**Comment by souseinu** [comment] 2024-01-31 07:02
> > > 注文の実行
> > > `sudo xattr -cr /GenshinImpact.ipa`
> > > PlayCover Nightly 623 で問題解決
> > 
> > 
> > This was successful but the error still occurs
> 
> Hey, have you found the solution? I read in another thread, to use Keka to unzip the ipa file and zip again. I don't know if it's work or not

Today's version of nightly seems to have solved this issue. I still do not understand what the bug was but i tried dragging the same file from last night into the app library and it extracted with no problems. Genshin now opens as normal.

**Comment by tegar09** [comment] 2024-01-31 15:41
> Today's version of nightly seems to have solved this issue. I still do not understand what the bug was but i tried dragging the same file from last night into the app library and it extracted with no problems. Genshin now opens as normal.

You're right. I just updated to 623 version and it works. Maybe the problem is my playcover is still not updated before.
 
Last time i check the update playcove, my playcover said is already up to dated, so i had to donwload manually 623 version from github.

**Comment by abdoufma** [comment] 2024-01-31 17:28
For me, the game kept crashing after updating the to the latest Nightly, I fixed it by setting the game category to `public.app-category.games` in `settings -> misc -> Application type`
