### ISSUE TITLE
[Bug]: App crashing when opening (seems related to playchain data)

### ISSUE THREAD

**Issue by github-daniel-mcdonald** [PlayCover/PlayCover#1461] opened 2024-05-03 09:06 UTC
### Describe the bug

As with a few other issues being reported recently, on mac os Sonoma, Rocket League Sideswipe is crashing on start up.

After trying everything I could think of, I finally had some success.

When clearing the playchain data, the game successfully starts again (obviously have to log in again though)

My temporary work around is clearing the playchain data every time before running the game.

Thought I'd report it here in case this provides any clues for recent bugs.

### Steps to reproduce

Start RLSS and log in

Close the app

Reopen the app

Crashes

Clear playchain data for RLSS

Reopen the app

App opens but must log in again.

### Expected behaviour

No need to clear playchain data in between game loads.

### Crash log

```shell
For some reason, at the moment I'm not getting the crash logs (silently closes)

Before I was seeing something starting with

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [2039]

as seen in some other reports
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-05-03 20:32
Duplicate of #1429.

**Closed as not planned by TheMoonThatRises** 2024-05-03 20:32 UTC
Labels: bug
