### ISSUE TITLE
[Bug]: Genshin Impact 4.4 fail to sign with xattr

### ISSUE THREAD

**Issue by Sokyu04** [PlayCover/PlayCover#1364] opened 2024-01-31 02:08 UTC
### Describe the bug

When trying to import Genshin 4.4 IPA, fails after 5-10 sec

### Steps to reproduce

import genshin 4.4 IPA

### Expected behaviour

after 5-10 secs error appears

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/wv/mny9pmgd7t38pxgxh32qkfn00000gn/T/TemporaryItems/NSIRD_PlayCover_3O7rgF/Payload/GenshinImpact.app/GenshinImpact'
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-01-31 02:13
Duplicate of #1349. Use the latest nightly build.

**Closed as not planned by TheMoonThatRises** 2024-01-31 02:13 UTC
Labels: bug

**Comment by JustinWu00** [comment] 2024-01-31 02:26
I had the same issue on decrypt.day version. Try to change another source like https://ipa.store/2081.html.

**Comment by chengengliu** [comment] 2024-01-31 02:48
I think it is the issue with the ipa source. I followed [this issue](https://github.com/PlayCover/PlayCover/issues/1349#issuecomment-1912966109)

**Comment by TheMoonThatRises** [comment] 2024-01-31 02:53
The issue is not with the IPA source provider or the IPA itself. This issue can be fixed by using the latest PlayCover nightly where a fix for this issue was pushed.

**Comment by chengengliu** [comment] 2024-01-31 02:54
> The issue is not with the IPA source provider or the IPA itself. This issue can be fixed by using the latest PlayCover nightly where a fix for this issue was pushed.

Thanks for the work!
