### ISSUE TITLE
[Bug]: every app crash on m3 chip

### ISSUE THREAD

**Issue by xiuxianchengdi** [PlayCover/PlayCover#1238] opened 2023-11-29 18:30 UTC
### Describe the bug

every app installed by playcover crash, ipa downloaded from decrypt.day. macos 14.1 apple m3 chip
[Discord-2023-11-29-132722.txt](https://github.com/PlayCover/PlayCover/files/13504300/Discord-2023-11-29-132722.txt)

### Steps to reproduce

click app logo in "App Library"
<img width="470" alt="Screenshot 2023-11-29 at 1 24 47 PM" src="https://github.com/PlayCover/PlayCover/assets/93297382/6e2c7972-80ca-4ded-9922-763d3ccb39d1">

Discord quit unexpectedly.

### Expected behaviour

open

### Crash log

```shell
There was an error creating your Issue: body is too long (maximum is 65536 characters).
log file attached in "Describe the bug"
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [x] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-12-01 15:38
Which nightly version are you on?

**Comment by TheMoonThatRises** [comment] 2023-12-01 15:39
Actually, looking at the crash log, it looks like you need to update to the latest nightly build. (Duplicate of #1108).

**Closed as not planned by TheMoonThatRises** 2023-12-01 15:39 UTC
Labels: app-support
