### ISSUE TITLE
[Bug]: Cant Open Call Of Duty

### ISSUE THREAD

**Issue by Ducmanhvn** [PlayCover/PlayCover#953] opened 2023-05-12 04:24 UTC
### Describe the bug

I open the game and it said use this game with PlayCover can get Band

### Steps to reproduce

How to fix it 

### Expected behaviour

How to fix it 

### Crash log

```shell
How to fix it
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-05-12 04:52
Duplicate of #238.

**Closed as not planned by TheMoonThatRises** 2023-05-12 04:52 UTC
Labels: duplicate
