### ISSUE TITLE
[Game Support]: Genshin impact 

### ISSUE THREAD

**Issue by ganuyss** [PlayCover/PlayCover#1370] opened 2024-01-31 13:00 UTC
### App Store link

https://genshin.hoyoverse.com/en

### Current issues

- [X] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

when I try to download the 4.4 decrypted version of genshin impact in the play cover library this message pops up and the download fails. 
<img width="936" alt="Capture d’écran 2024-01-31 à 12 25 34" src="https://github.com/PlayCover/PlayCover/assets/158290144/24a98fcf-d13a-48ef-be95-e0da62260191">

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/2m/1d_6_qln3ls_1v7lshn0bh8r0000gn/T/TemporaryItems/NSIRD_PlayCover_gYFuq0/Payload/GenshinImpact.app/GenshinImpact'
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kang49** [comment] 2024-01-31 13:06
I have same problem.

**Comment by kang49** [comment] 2024-01-31 13:09
Use this version:
https://github.com/PlayCover/PlayCover/actions/runs/7716496315

**Comment by Dhi47** [comment] 2024-01-31 13:51
have the same issue too, but using that it works! Thanks!

**Comment by TheMoonThatRises** [comment] 2024-01-31 15:05
Duplicate of #1349.

**Closed as not planned by TheMoonThatRises** 2024-01-31 15:05 UTC
Labels: game-support
