### ISSUE TITLE
[Game Support]: torchlight-infinite

### ISSUE THREAD

**Issue by zjslqshqz** [PlayCover/PlayCover#959] opened 2023-05-15 01:40 UTC
### App Store link

https://apps.apple.com/app/torchlight-infinite/id1593130084

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

After the game resource is updated, initialization fails

### Crash log

```shell
The complete error message, too long, is .log in the following separate file tool
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by zjslqshqz** [comment] 2023-05-15 01:40
[too.log](https://github.com/PlayCover/PlayCover/files/11473516/too.log)

**Comment by TheMoonThatRises** [comment] 2023-05-15 02:07
Duplicate of #879.

**Closed as not planned by TheMoonThatRises** 2023-05-15 02:07 UTC
Labels: game-support
