### ISSUE TITLE
[Bug]: Instagram doesnt work

### ISSUE THREAD

**Issue by Calexypnos** [PlayCover/PlayCover#1710] opened 2024-10-06 13:05 UTC
### Describe the bug

I opened instagram on playcover I can log in but I cant access reels or look at other people's stories

### Steps to reproduce

Install Instagram 
Sign in to Instagram
Discover that it doesnt work
<img width="742" alt="Screenshot 2024-10-06 at 10 05 36 PM" src="https://github.com/user-attachments/assets/32de7050-d243-40c5-a2db-3d95634667c9">

### Expected behaviour

Instagram loads reels and I am able to use it

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-10-07 15:25
Duplicate of #1205. No current fixes, use either web version or iPhone Mirroring.

**Closed as not planned by TheMoonThatRises** 2024-10-07 15:25 UTC
Labels: bug
