### ISSUE TITLE
[Feature request][Rotation] Turn on "Adaptive Display" will cause iPad apps to be stretched vertically by mistake.

### ISSUE THREAD

**Issue by LifeCoLTD** [PlayCover/PlayCover#182] opened 2022-08-18 23:17 UTC
When I turn on "Adaptive Display" function for "小红书" app, that app will be stretched vertically so long that its boundary exceed the ability of Mac's display. At the same time, I tried all argument under the "Adaptive Display", all will cause that app exceed the display of Mac.

Therefore, my question is that can PlayCover add an option to force app to rotate itself? Because some iPad APPs support rotation. After rotation, the display of app will consistent with Mac: they are both like the rectangle.

PlayCover Version: Version 1.1.0 (17)
macOS Version: 12.5.1 (21G83) & 13.0 Beta3
The link for "小红书"APP: https://apps.apple.com/us/app/小红书-标记我的生活/id741292507

**Comment by Depal1** [comment] 2022-08-18 23:19
This issue has just been fixed in version 1.1.1. For the rotation feature request, please rename this issue.

**Comment by Depal1** [comment] 2022-08-18 23:20
Actually, the new feature should work analogously to a rotation.

**Closed as completed by Depal1** 2022-08-18 23:20 UTC

**Comment by LifeCoLTD** [comment] 2022-08-18 23:22
> This issue has just been fixed in version 1.1.1. For the rotation feature request, please rename this issue.

I have renamed the name. Is that suitable?

**Comment by Depal1** [comment] 2022-08-18 23:23
Could you try the new vertical display feature? If it doesn't work as intended, this issue can be reopened.

**Comment by LifeCoLTD** [comment] 2022-08-18 23:29
> Could you try the new vertical display feature? If it doesn't work as intended, this issue can be reopened.

The new vertical display feature works as intended. Thanks so much!
