### ISSUE TITLE
[Bug]: Game 'Wuthering Wave' 1.4 Version获取补丁列表失败，原因：文件重命名出错

### ISSUE THREAD

**Issue by Jeffchen8488** [PlayCover/PlayCover#1745] opened 2024-11-21 10:36 UTC
### Describe the bug

<img width="1440" alt="Screenshot 2024-11-21 at 18 28 08" src="https://github.com/user-attachments/assets/4f6751e0-5509-445a-a9a4-c050a53b7829">

### Steps to reproduce

[Bug]: Game 'Wuthering Wave' 1.4 Version获取补丁列表失败，原因：文件重命名出错

### Expected behaviour

[Bug]: Game 'Wuthering Wave' 1.4 Version获取补丁列表失败，原因：文件重命名出错

### Crash log

```shell
[Bug]: Game 'Wuthering Wave' 1.4 Version获取补丁列表失败，原因：文件重命名出错
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-12-05 21:45
Duplicate of #1478. Check solutions posted in that thread of temporarily use nightly builds before the next release.

**Closed as not planned by TheMoonThatRises** 2024-12-05 21:45 UTC
Labels: bug
