### ISSUE TITLE
[Bug]: can not configure the VPN by the software "UU booster"

### ISSUE THREAD

**Issue by XuanWen-code** [PlayCover/PlayCover#1258] opened 2023-12-11 03:20 UTC
### Describe the bug

When the software tries to configure the VPN setting, it does not work, it does not open the VPN page.

### Steps to reproduce

UU boster is a paid app that works by automatically configuring the VPN by clicking on the accelerate button, which only requires you to set up an allow request to your computer for the configuration to be successful, however, the autoconfiguration message does not come up on the play cover and the allow button does not show up, so it does not work.

### Expected behaviour

I hope the software can support auto-configuring the VPN setting by the UU booster.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-01-01 02:25
Duplicate of #1241.

**Closed as not planned by TheMoonThatRises** 2024-01-01 02:25 UTC
Labels: bug
