### ISSUE TITLE
[Bug]: playcover is not compatible on Mac Os 14.1 

### ISSUE THREAD

**Issue by Noah19981115** [PlayCover/PlayCover#1185] opened 2023-10-29 08:09 UTC
### Describe the bug

As stated, playcover can be run on Mac Os 14.1, but any apps I installed via it can not be opened. They all crashed. 

### Steps to reproduce

/

### Expected behaviour

/

### Crash log

```shell
/
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-10-29 08:21
Duplicate of #1108.

**Closed as not planned by TheMoonThatRises** 2023-10-29 08:21 UTC
Labels: bug
