### ISSUE TITLE
[Game Support]:Pokemon Unite is blocked from opening - Jailbreak Bypass 

### ISSUE THREAD

**Issue by Jhossi366** [PlayCover/PlayCover#546] opened 2022-11-30 15:48 UTC
### App Store link

https://apps.apple.com/us/app/pokémon-unite/id1512321575

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

The application of Pokemon unite presents problems when starting the application, because it detects Jealbreak on the device, as a possible solution the way to open the game on a Jealbroken device was to install the Tweak called Vnodebypass : https://github.com/ichitaso/vnodebypass

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment] 2022-12-03 21:56
Pokemon Unite won't work on PayCover just like SuperCell games (Clash of Clans & etc.) because they have a (if I remember correctly) kernel jailbreak detection that doesn't allow them to ran.

**Comment by TheMoonThatRises** [comment] 2023-02-07 02:54
Duplicate of #318. See that issue for more information.

**Closed as not planned by TheMoonThatRises** 2023-02-07 02:54 UTC
Labels: game-support
