### ISSUE TITLE
[App Support]: Issue Logging into App

### ISSUE THREAD

**Issue by kikoblueberry2** [PlayCover/PlayCover#1013] opened 2023-06-23 18:02 UTC
### App Store link

Not in Apple App Store

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

Hello there, developers. 
I downloaded Playcover, added the software Genshin Impact, then followed the on-screen instructions. After that, I attempted to enter into my account, but it kept displaying "Parameter Error." I'm not sure why this continues appearing. If logging in was still a difficulty, I tried the other alternatives, but it said the same thing. I'm not sure what the problem could be. I'm running Mac OS X. Could you please resolve the issue? I'm not sure why nothing works when I try to log in. 

Thank you very much.

### Crash log

```shell
No crash Logs
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-06-23 19:02
Duplicate of #741 and #877. Use the latest version of PlayCover (3.0.0).

**Closed as not planned by TheMoonThatRises** 2023-06-23 19:02 UTC
Labels: duplicate, game-support
