### ISSUE TITLE
[Поддержка игры]: Clash of Clans

### ISSUE THREAD

**Issue by yar0m4** [PlayCover/PlayCover#1066] opened 2023-08-05 11:33 UTC
### App Store link

https://apps.apple.com/us/app/clash-of-clans/id529479190

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Game crashes on startup, tried different settings, but nothin changes.

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Clash of Clans [5961]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/Clash of Clans.app/Clash of Clans
Identifier:            com.supercell.magic
Version:               15.352.8 (15.352.8)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-05 14:33:08.8885 +0300
OS Version:            macOS 13.5 (22G74)
Report Version:        12
Anonymous UUID:        F511425C-1F83-C6DE-9F6C-133337BCC195

Sleep/Wake UUID:       34ED4FBA-6D8C-4CA3-8E8F-848E0A821957

Time Awake Since Boot: 9600 seconds
Time Since Wake:       1784 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/magicx.framework/magicx
Referenced from: <6E0DE7AE-612E-3107-8D8D-1EB268FB7900> /Users/USER/Library/Containers/io.playcover.PlayCover/Clash of Clans.app/Clash of Clans
Reason: tried: '/usr/lib/swift/magicx.framework/magicx' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/magicx.framework/magicx' (no such file), '/usr/lib/swift/magicx.framework/magicx' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/magicx.framework/magicx' (no such file), '/System/Library/Frameworks/magicx.framework/magicx' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x19f265118 __abort_with_payload + 8
1   dyld                          	       0x19f270d7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x19f270db0 abort_with_payload + 16
3   dyld                          	       0x19f1fc8a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x19f1f9590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x19f1f7e18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fc9e8c0   x3: 0x000000000000008d
    x4: 0x000000016fc9e4c0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000b50
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000035  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x000000019f1f535c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fc9e4c0  x21: 0x000000000000008d  x22: 0x000000016fc9e8c0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001faac10c0  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016fc9e490   lr: 0x000000019f270d7c
    sp: 0x000000016fc9e450   pc: 0x000000019f265118 cpsr: 0x00001000
   far: 0x00000001013e0000  esr: 0x56000080  Address size fault

Binary Images:
       0x100160000 -        0x100fe7fff com.supercell.magic (15.352.8) <6e0de7ae-612e-3107-8d8d-1eb268fb7900> /Users/USER/Library/Containers/io.playcover.PlayCover/Clash of Clans.app/Clash of Clans
       0x19f1f2000 -        0x19f280587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=818.9M resident=0K(0%) swapped_out_or_unallocated=818.9M(100%)
Writable regions: Total=8784K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8784K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            2107K        3 
__DATA_CONST                        22K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       803.9M        2 
__TEXT                            15.1M        2 
dyld private memory                272K        2 
===========                     =======  ======= 
TOTAL                            885.3M       14 



-----------
Full Report
-----------

{"app_name":"Clash of Clans","timestamp":"2023-08-05 14:33:10.00 +0300","app_version":"15.352.8","slice_uuid":"6e0de7ae-612e-3107-8d8d-1eb268fb7900","build_version":"15.352.8","platform":6,"bundleID":"com.supercell.magic","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5 (22G74)","roots_installed":0,"name":"Clash of Clans","incident_id":"B8DBC869-D254-4D11-B47D-E330D5600FFF"}
{
  "uptime" : 9600,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 3938,
  "osVersion" : {
    "train" : "macOS 13.5",
    "build" : "22G74",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-05 14:33:08.8885 +0300",
  "incident" : "B8DBC869-D254-4D11-B47D-E330D5600FFF",
  "pid" : 5961,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-05 14:33:08.8644 +0300",
  "procStartAbsTime" : 232205649465,
  "procExitAbsTime" : 232206008421,
  "procName" : "Clash of Clans",
  "procPath" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Clash of Clans.app\/Clash of Clans",
  "bundleInfo" : {"CFBundleShortVersionString":"15.352.8","CFBundleVersion":"15.352.8","CFBundleIdentifier":"com.supercell.magic","DTAppStoreToolsBuild":"14E221"},
  "storeInfo" : {"deviceIdentifierForVendor":"708DE4FF-C93E-5D13-8C51-16D34E81534F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.supercell.magic",
  "crashReporterKey" : "F511425C-1F83-C6DE-9F6C-133337BCC195",
  "codeSigningID" : "com.supercell.magic",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1784,
  "sleepWakeUUID" : "34ED4FBA-6D8C-4CA3-8E8F-848E0A821957",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/magicx.framework\/magicx","Referenced from: <6E0DE7AE-612E-3107-8D8D-1EB268FB7900> \/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Clash of Clans.app\/Clash of Clans","Reason: tried: '\/usr\/lib\/swift\/magicx.framework\/magicx' (no such file, not in dyld cache), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/lib\/swift\/magicx.framework\/magicx' (no such file), '\/usr\/lib\/swift\/magicx.framework\/magicx' (no such file, not in dyld cache), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/lib\/swift\/magicx.framework\/magicx' (no such file), '\/System\/Library\/Frameworks\/magicx.framework\/magicx' (no such file, not in dyld cache), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":114473,"threadState":{"x":[{"value":6},{"value":1},{"value":6170470592},{"value":141},{"value":6170469568},{"value":0},{"value":0},{"value":2896},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":53},{"value":4},{"value":32768},{"value":521},{"value":6964597596,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6170469568},{"value":141},{"value":6170470592},{"value":1},{"value":6},{"value":8500547776,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6965103996},"cpsr":{"value":4096},"fp":{"value":6170469520},"sp":{"value":6170469456},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6965055768,"matchesCrashFrame":1},"far":{"value":4315807744}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":1},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":1},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":1},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4296409088,
    "CFBundleShortVersionString" : "15.352.8",
    "CFBundleIdentifier" : "com.supercell.magic",
    "size" : 15237120,
    "uuid" : "6e0de7ae-612e-3107-8d8d-1eb268fb7900",
    "path" : "\/Users\/USER\/Library\/Containers\/io.playcover.PlayCover\/Clash of Clans.app\/Clash of Clans",
    "name" : "Clash of Clans",
    "CFBundleVersion" : "15.352.8"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6964584448,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6963920896,
  "size" : 3553361920,
  "uuid" : "9c875b0a-d532-3933-b1f0-f1ea72cedde2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=818.9M resident=0K(0%) swapped_out_or_unallocated=818.9M(100%)\nWritable regions: Total=8784K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8784K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            2107K        3 \n__DATA_CONST                        22K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       803.9M        2 \n__TEXT                            15.1M        2 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                            885.3M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "0091a78b30cad07da655b1b25c529692b8d4d80d",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    },
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000016
    },
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    }
  ]
}
}
```

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-08-31 20:58
Duplicate of #775. See https://github.com/PlayCover/PlayCover/issues/559#issuecomment-1345461531.

**Closed as not planned by TheMoonThatRises** 2023-08-31 20:58 UTC
Labels: game-support
