### ISSUE TITLE
[Bug]: Permission denied when installing IPA

### ISSUE THREAD

**Issue by HuangWeiHaii** [PlayCover/PlayCover#1353] opened 2024-01-27 05:38 UTC
### Describe the bug

I encountered an error while installing an IPA application

### Steps to reproduce

<img width="520" alt="image" src="https://github.com/PlayCover/PlayCover/assets/44046269/2bf17167-5e8b-42b1-9e81-c3a9e0f6fd83">

### Expected behaviour

<img width="520" alt="image" src="https://github.com/PlayCover/PlayCover/assets/44046269/809a296d-a20b-437d-a535-89d00deadd20">

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/jkchess'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/PlugIns/Notification.appex/Notification'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/GCloudCore.framework/GCloudCore'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/crosCurl.framework/crosCurl'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/CrashSight.framework/CrashSight'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/kgvmp_dy.framework/kgvmp_dy'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/tersafe.framework/tersafe'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/TDataMaster.framework/TDataMaster'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKWebView.framework/MSDKWebView'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/TDMIDFA.framework/TDMIDFA'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/Hippy.framework/Hippy'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKSensitivity.framework/MSDKSensitivity'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/tgpa_wrapper.framework/tgpa_wrapper'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKDns.framework/MSDKDns'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKTDM.framework/MSDKTDM'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/CrashSightCore.framework/CrashSightCore'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKSystem.framework/MSDKSystem'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/GCloud.framework/GCloud'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/MSDKLBS.framework/MSDKLBS'
xattr: [Errno 13] Permission denied: '/var/folders/hc/f2pxn31x5wg987qb30zj_61m0000gn/T/TemporaryItems/NSIRD_PlayCover_P5NcgR/Payload/jkchess.app/Frameworks/CrashSightAdapter.framework/CrashSightAdapter'
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Nihts** [comment] 2024-01-27 06:22
The same as you when I installed  "com.tencent.jkchess_1.6.17_1028__und3fined.ipa". Then I tried to install the old version "com.tencent.jkchess_1.5.14_998__und3fined.ipa", it can be installed successfully! I think the lastest version "jkchess_1.6.17_1028" had some bugs.

**Comment by Nihts** [comment] 2024-01-27 06:28
My macOS is Sonoma 14.3, My PlayCover is 3.0.0(619).

**Comment by licat233** [comment] 2024-01-27 08:19
Maybe you need to try this method：[https://github.com/PlayCover/PlayCover/issues/1349#issuecomment-1912966109](url)

**Comment by Nihts** [comment] 2024-01-27 11:06
> Maybe you need to try this method：[https://github.com/PlayCover/PlayCover/issues/1349#issuecomment-1912966109](url)

I try the following method:
Download  https://github.com/Ryu-ga/PlayTools/blob/Sonoma14_1b/PlayTools.framework.zip  and unzip
```
rm -rf ~/Library/Frameworks/PlayTools.framework
rm -rf /Applications/PlayCover.app/Contents/Frameworks/PlayTools.framework
cp -R ~/Downloads/PlayTools.framework /Applications/PlayCover.app/Contents/Frameworks/PlayTools.framework
```
and restart the playcover. But I also can't install "com.tencent.jkchess_1.6.17_1028__und3fined.ipa"

**Comment by Nihts** [comment] 2024-01-27 11:21
"com.tencent.jkchess_1.6.17_1028__und3fined.ipa" ’s link is https://decrypt.day/app/id1478101301; I think it has some problems, I down the "ipa" file in [there](https://ipa.store/3431.html), also I update them on [BaiDu NetDisk](https://pan.baidu.com/s/1zamj0fFVO7T7vSt8DJZwcA?pwd=37gu)

**Comment by xuanxuan88HDDD** [comment] 2024-01-28 05:25
> "com.tencent.jkchess_1.6.17_1028__und3fined.ipa" ’s link is https://decrypt.day/app/id1478101301; I think it has some problems, I down the "ipa" file in [there](https://ipa.store/3431.html), also I update them on [BaiDu NetDisk](https://pan.baidu.com/s/1zamj0fFVO7T7vSt8DJZwcA?pwd=37gu)

安装源的问题 淘宝买的没什么问题
https://item.taobao.com/item.htm?id=723694045869

**Comment by TheMoonThatRises** [comment] 2024-01-29 00:14
Duplicate of #1349.

**Closed as not planned by TheMoonThatRises** 2024-01-29 00:14 UTC
Labels: bug

**Comment by EricYu-personal** [comment] 2024-01-30 05:25
> "com.tencent.jkchess_1.6.17_1028__und3fined.ipa" ’s link is https://decrypt.day/app/id1478101301; I think it has some problems, I down the "ipa" file in [there](https://ipa.store/3431.html), also I update them on [BaiDu NetDisk](https://pan.baidu.com/s/1zamj0fFVO7T7vSt8DJZwcA?pwd=37gu)

Can you help me to download “暗区突围” for me please(on that ipastore website)?
I can't visit it.
Thank you.
