### ISSUE TITLE
[Game Support]: jkchess

### ISSUE THREAD

**Issue by afflatus0522** [PlayCover/PlayCover#1058] opened 2023-07-26 15:20 UTC
### App Store link

When I play jkchess in Playcover,I can not open my microphone and can not communicate with my friend.
PS:I can hear the game music and i have already open my computer's microphone,just can not use microphone in the game.My comptuter is Macbook Air Apple M2.Please help me!thanks!It's my favorite game.I just want to play it in my mac.

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [X] Game experiences graphical issues or broken UI
- [X] Game fails to connect to servers or complete download

### More details

If I open the microphone in the game,"can not find your microphone"is in the screen.how should i do?

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-07-28 22:01
Duplicate of #385.

**Closed by TheMoonThatRises** 2023-07-28 22:01 UTC
Labels: game-support
