### ISSUE TITLE
[Bug]: Wrong game window size.

### ISSUE THREAD

**Issue by kotleni** [PlayCover/PlayCover#699] opened 2023-01-14 07:20 UTC
### Describe the bug

After starting games I have wrong window size, and render position bugs in some games. 
https://pasteboard.co/aqEjdsMwx7aY.png
https://pasteboard.co/8xwvztUvcyHz.png

But, if set mirrored window size. (aka 1080x1080, or 720x720) I have nice work, but in stupid window size.
https://pasteboard.co/ggE0aCvBBJaS.png
https://pasteboard.co/N9Uj5u26ApcU.png

### Steps to reproduce

Just install and start game. (Works for me)

### Expected behaviour

Game starting in my screen resolution.

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment] 2023-01-14 20:37
Hello! 
Have you tried selecting "Auto" in the graphics settings in PlayCover?
What does it show as the detected resolution?
<img width="594" alt="Screenshot 2023-01-14 at 15 35 38" src="https://user-images.githubusercontent.com/13000207/212495620-d675ebb6-6316-4580-beb5-95e01bf29f2e.png">

**Comment by kotleni** [comment] 2023-01-14 20:45
> Hello! 
> 
> Have you tried selecting "Auto" in the graphics settings in PlayCover?
> 
> What does it show as the detected resolution?
> 
> <img width="594" alt="Screenshot 2023-01-14 at 15 35 38" src="https://user-images.githubusercontent.com/13000207/212495620-d675ebb6-6316-4580-beb5-95e01bf29f2e.png">

Yes. I tried all this settings (and custom).
I have 1440x900.

**Comment by zanderp25** [comment] 2023-01-14 21:54
What happens if you do Keymapping -> Rotate display area?

**Comment by kotleni** [comment] 2023-01-15 07:34
@zanderp25 
<img width="959" alt="Screenshot 2023-01-15 at 09 33 48" src="https://user-images.githubusercontent.com/38311102/212528584-65e91710-3b26-4da9-9947-a7e538bd1b0e.png">

**Comment by zanderp25** [comment] 2023-01-15 19:28
That's bizarre. I've never seen that happen before. This must be a PlayTools issue, and I'm not really familiar with it.

**Comment by kotleni** [comment] 2023-01-15 19:33
> That's bizarre. I've never seen that happen before. This must be a PlayTools issue, and I'm not really familiar with it.

((

**Comment by amirsaam** [comment] 2023-01-15 19:35
are you on macos 13.2 beta?

**Comment by kotleni** [comment] 2023-01-15 19:38
> are you on macos 13.2 beta?
<img width="392" alt="Screenshot 2023-01-15 at 21 38 14" src="https://user-images.githubusercontent.com/38311102/212563293-d4295d8a-5716-4e27-831c-2e76588d865f.png">

**Comment by amirsaam** [comment] 2023-01-15 19:40
You should've searched issues before opening one, anyway that's a bug on PlayTools on macOS 13.2 beta.
Devs looking into it, for now downgrade to 13.1.
_(why on earth users update to beta os version)_

**Comment by kotleni** [comment] 2023-01-15 19:41
> You should've searched issues before opening one, anyway that's a bug on PlayTools on macOS 13.2 beta. Devs looking into it, for now downgrade to 13.1. _(why on earth users update to beta os version)_

Okay, thx

**Comment by TheMoonThatRises** [comment] 2023-01-15 20:23
Duplicate of https://github.com/PlayCover/PlayTools/issues/64

**Closed as not planned by TheMoonThatRises** 2023-01-15 20:23 UTC
Labels: bug

**Comment by zanderp25** [comment] 2023-01-16 01:40
> are you on macos 13.2 beta?

Whoops, I hadn't thought of that
