### ISSUE TITLE
[Game Support]: KartRider: Drift

### ISSUE THREAD

**Issue by Sunalamye** [PlayCover/PlayCover#857] opened 2023-03-11 04:19 UTC
### App Store link

https://apps.apple.com/us/app/kartrider-drift/id1554978344

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I tried to open KartRider: Drift,
 but received an error message "illegal program has been detected (110/0)" when trying to log in.
 The game automatically closed after a short while.
 I enabled the option "Enable Jailbreak Bypass (Experimental)" to try to bypass this issue.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment] 2023-03-13 04:30
You can try adding `api.ngsm.nexon.com` to your Mac's Hosts file. It won't necessarily get rid of AC but it **may** prevent your game from crashing

**Comment by ohaiibuzzle** [comment] 2023-03-13 04:32
This is because of Nexon's NGSM, we are working on it

**Comment by TheMoonThatRises** [comment] 2023-04-04 16:21
Duplicate of #797.

**Closed as not planned by TheMoonThatRises** 2023-04-04 16:21 UTC
Labels: duplicate, game-support
