### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Henry-xian-qi** [PlayCover/PlayCover#724] opened 2023-01-19 13:09 UTC
### Describe the bug

In the upcoming **macOS 13.2 (22D49)**, there is an issue with **Genshin Impact** not displaying the full window when opened.

### Steps to reproduce

Updating a new version of macOS will cause the game to not display properly, downgrading will solve this problem. I have tried uninstalling and reinstalling playcover and the game before but this did not fix the problem.
Changing the resolution in the Playcover settings did not solve the problem either.
100% certain to appear

### Expected behaviour

Compatibility issues with newer versions of macOS.

### What version of PlayCover are you using?

2.0.2

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-01-19 13:29
Duplicate of https://github.com/PlayCover/PlayTools/issues/64 and fixed in https://github.com/PlayCover/PlayTools/pull/66

**Closed as not planned by TheMoonThatRises** 2023-01-19 13:29 UTC
Labels: bug
