### ISSUE TITLE
WHY DOES THIS NOT WORK

### ISSUE THREAD

**Issue by Moonshee5288** [PlayCover/PlayCover#1369] opened 2024-01-31 09:08 UTC
### Describe the bug

Every time I try to get my genshin impact to open I get a error message that is different to what anyone else has gotten. I have made other bug reports and have also tried the terminal trick from a previous bug report

### Steps to reproduce

1. Use playcover nightly 619 or playcover beta 3.0.0 beta 2 on mac os sonoma 14.2.1
2. Use Genshin impact from any cite
3. try install it to get the first error message
4. try open it to get the second error message

### Expected behaviour

The app opens

### Crash log

```shell
/var/folders/5y/_5jrd5pn3312fvxvtdq1k5fc0000gn/T/TemporaryItems/NSIRD_PlayCover_AhU7Tp/Payload/GenshinImpact.app/PlugIns/AKInterface.bundle: replacing existing signature
/var/folders/5y/_5jrd5pn3312fvxvtdq1k5fc0000gn/T/TemporaryItems/NSIRD_PlayCover_AhU7Tp/Payload/GenshinImpact.app/PlugIns/AKInterface.bundle: resource fork, Finder information, or similar detritus not allowed

i also get this one when trying to open the app

/Users/USER/Library/Containers/io.playcover.PlayCover/Applications/com.miHoYo.GenshinImpact.app/PlugIns/AKInterface.bundle: replacing existing signature
/Users/USER/Library/Containers/io.playcover.PlayCover/Applications/com.miHoYo.GenshinImpact.app/PlugIns/AKInterface.bundle: resource fork, Finder information, or similar detritus not allowed
```

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Smallasteroid** [comment] 2024-01-31 09:57
Me too, I also got this. The only difference is I don't even get a chance to install the Genshin Impact file to playcover. 
<img width="247" alt="截屏2024-01-31 17 54 40" src="https://github.com/PlayCover/PlayCover/assets/158272734/87e439fc-0bab-4d04-a15d-f360bbaa6c4e">
I used the same version of playcover, but with MacOS Monterey (macOS 12)

**Comment by sgoleo2021** [comment] 2024-01-31 11:40
+1 MacOS14.3, same as @Smallasteroid

**Comment by Ativernad** [comment] 2024-01-31 12:16
try different ipa file
https://armconverter.com/decryptedappstore/us

**Comment by yuchenii** [comment] 2024-01-31 12:34
I installed genshin impact v4.4.0 without any problems. 
- playcover: nightly 623, try [latest nightly version](https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop)
-  ipa: [decrypt.day](https://decrypt.day/)
- MacOS:  14.2.1

**Comment by TheMoonThatRises** [comment] 2024-01-31 15:06
Duplicate of #1349.

**Closed as not planned by TheMoonThatRises** 2024-01-31 15:06 UTC
Labels: bug
