### ISSUE TITLE
API downloading failure

### ISSUE THREAD

**Issue by PlayBoxJoker** [PlayCover/PlayCover#1371] opened 2024-01-31 15:31 UTC
### App Store link

i have been trying to update Genshin form last week and i was at my peak but due to some issues form playcover i uninstall it and then tried to reinstall but it didn't worked 

### Current issues

- [X] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

everytime it fails and api error pops up which doesn't let me download and then i tried to import a discripted form of Genshin but the importing also fails and don't work properly Please fix this quickly it will mean alot to be honest

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-01-31 19:18
Duplicate of #1349. Make sure to download the IPA from the source directly instead of through the IPA library if that is an issue. Also, update to the latest nightly version, as that fixes the import bug.

**Closed as not planned by TheMoonThatRises** 2024-01-31 19:18 UTC
Labels: game-support
