### ISSUE TITLE
[Bug]: search bar condition not reset

### ISSUE THREAD

**Issue by wakou** [PlayCover/PlayCover#915] opened 2023-04-13 05:35 UTC
## Problen describe
**This is my `App Library`**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/20671600/231660833-08a4f932-1142-4530-9bd6-09122b95607a.png">

**Search `"genshin"` in search bar, get search result**
<img width="916" alt="image" src="https://user-images.githubusercontent.com/20671600/231660884-05f08323-4cfa-4a5c-b2c9-5642516c5682.png">

**Switch to `IPA Library`, then switch to `App Library`, the search bar is empty, but search condition `"genshin"` still effective.**
<img width="912" alt="image" src="https://user-images.githubusercontent.com/20671600/231660966-d2d6671e-09d6-4978-b444-819aa1162e3f.png">

## Temporary solution
input something in search bar, PlayCover would apple new condition, then you can clear search bar to get all app

## Other
I use PlayCover 2.0.5

### Steps to reproduce

1. In `App Library` tab or `IPA Library`, search something in search bar
2. Switch to another tab, then switch back
3. The search condition not reset

### Expected behaviour

The search condition reset, display all app.
Or the search bar not empty, still display previous search condition.

### Crash log

```shell
Not involved
```

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by amirsaam** [comment] 2023-05-01 15:06
Cannot reproduce this issue. Also update your PlayCover to at least 2.0.5

**Comment by TheMoonThatRises** [comment] 2023-05-01 16:03
This is fixed in the nightly builds with #753.

**Closed as completed by TheMoonThatRises** 2023-05-01 16:03 UTC
Labels: bug
