### ISSUE TITLE
[Game Support]: Goddess of Victory: Nikke

### ISSUE THREAD

**Issue by Bwainy** [PlayCover/PlayCover#1455] opened 2024-04-28 06:04 UTC
### App Store link

https://apps.apple.com/us/app/goddess-of-victory-nikke/id1585915174

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

I would love for this game to have support since it doesn't even open because of playtools.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Chang9an** [comment] 2024-04-30 07:53
remove playtools

**Comment by Cayde-20** [comment] 2024-05-03 06:17
I have the exact same issue. tried on terminal, dashboard, finder but it doesn't response

**Comment by TheMoonThatRises** [comment] 2024-05-03 20:52
Duplicate of #1339.

**Closed as not planned by TheMoonThatRises** 2024-05-03 20:52 UTC
Labels: game-support
