### ISSUE TITLE
[Bug]: Minimizing the game [碧蓝航线] window caused the game content to pause

### ISSUE THREAD

**Issue by NickeL9740** [PlayCover/PlayCover#1704] opened 2024-09-30 05:58 UTC
### Describe the bug

I am using MacOS 15.0 official version. I am sorry but I am not sure whether it is a normal condition in MacOS 15.0 due to its fundamental codes, or it is an issue in PlayCover since I haven't been using PlayCover in a while. But it functions normally previously when I was in MacOS 14.7 beta.

[Bug]: Minimizing the game [碧蓝航线] window caused the game content to pause and pop out game background notifications which never existed before. That is another bug which is not the essential focus I am mentioning in this report.

### Steps to reproduce

1. open the game and enter a loop battle.
2. minimize the window to dock.

### Expected behaviour

1. game content freezes with no pop-up windows of "continue to play\quit", no progress was made while the window being minimized.
2. game content pauses with a pop-up window of "continue to play\quit".

Game content should have been working normally in minimized window mode as in opened window mode previously.

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-09-30 06:02
Duplicate of #1568. This occurs due to a change in the way Catalyst apps work on MacOS now.

**Closed as not planned by TheMoonThatRises** 2024-09-30 06:02 UTC
Labels: bug

**Comment by NickeL9740** [comment] 2024-09-30 06:04
> Duplicate of #1568. This occurs due to a change in the way Catalyst apps work on MacOS now.

Uh, okay. I just saw that post after I posted. But still if it could be a feature to turn on and off in PlayCover would be great.

**Comment by NickeL9740** [comment] 2024-09-30 06:08
> Duplicate of #1568. This occurs due to a change in the way Catalyst apps work on MacOS now.

Then what about the notification issue I mentioned? I have never received a normal notification from the game yet since a year.

**Comment by NickeL9740** [comment] 2024-09-30 06:08
> > Duplicate of #1568. This occurs due to a change in the way Catalyst apps work on MacOS now.
> 
> Then what about the notification issue I mentioned? I have never received a normal game notification from the game yet since a year.

**Comment by Catta1997** [comment] 2024-09-30 06:31
> > Duplicate of #1568. This occurs due to a change in the way Catalyst apps work on MacOS now.
> 
> Uh, okay. I just saw that post after I posted. But still if it could be a feature to turn on and off in PlayCover would be great.

Not possible, is how app on macOS works now
