### ISSUE TITLE
[Game Support]: Dualsense controller keep getting stuck when playing “Zenless zone zero”

### ISSUE THREAD

**Issue by a5317264** [PlayCover/PlayCover#1591] opened 2024-07-14 18:50 UTC
### App Store link

https://apps.apple.com/us/app/zenless-zone-zero/id1606356401

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

As title. It stuck randomly and need to press ps button(switch between apps) to fix.
macOS 14.3.1

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment] 2024-07-14 20:39
Duplicate of #1550

**Closed as not planned by XuYicong** 2024-07-14 20:39 UTC
Labels: game-support
