### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by sc2865** [PlayCover/PlayCover#1435] opened 2024-04-04 13:36 UTC
### App Store link

https://apps.apple.com/hk/app/%E7%AC%AC%E4%BA%94%E4%BA%BA%E6%A0%BC/id1370284166

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

When the app is opened, it's icon appears in the dock and disappears/ close within a moment
The version of play cover is used is nightly 702

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ariqpradipa** [comment] 2024-04-04 15:40
try to `Clear PlayChain Data` then run the app again

**Comment by sc2865** [comment] 2024-04-05 09:03
Thx for your suggestion
i tried but the problem still exists
Would there be any other solutions? :)

**Comment by TheMoonThatRises** [comment] 2024-05-03 20:34
Duplicate of #1429. Either clear PlayChain or downgrade to an older nightly version of PlayCover.

**Closed as not planned by TheMoonThatRises** 2024-05-03 20:34 UTC
Labels: game-support
