### ISSUE TITLE
[Bug]: Golden Shovel Quits

### ISSUE THREAD

**Issue by riven-blade** [PlayCover/PlayCover#1197] opened 2023-11-05 14:11 UTC
### Describe the bug

The Golden Shovel game will exit

### Steps to reproduce

The Golden Shovel game will exit

### Expected behaviour

The Golden Shovel game will exit

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-11-05 21:39
Duplicate of #1104.

**Closed as not planned by TheMoonThatRises** 2023-11-05 21:39 UTC
Labels: game-support
