### ISSUE TITLE
[Support de jeu] : Cursor stuck in map Dofus Touch

### ISSUE THREAD

**Issue by IlaneIS** [PlayCover/PlayCover#524] opened 2022-11-19 23:25 UTC
### App Store link

https://apps.apple.com/fr/app/dofus-touch/id1041406978

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

This game has an interactive map. But the cursor is stuck at one specific spot of the map. What makes it impossible to use and play. But still, its possible to interact with things that are in the borders of the screen such as inventory, open an inventory windows then interact with it.
Is it a way to fix this ? Thank you by advance.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2022-11-20 02:06
Duplicate of #514

**Closed as not planned by IsaacMarovitz** 2022-11-20 02:06 UTC
Labels: game-support
