### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mochisoya** [PlayCover/PlayCover#1017] opened 2023-06-25 16:29 UTC
### Describe the bug

Hi ! So I've been trying to do step 1 and 2 for troubleshooting but it when I input my password and email, it kept on saying "Parameter error". I've been doing it for almost 5 times and I still hasn't worked. Please help :(

### Steps to reproduce

Step 1 was to disable it step 2 was to check smth I think or to turn smth off but when I was adding my pw in the game it still didn't work

### Expected behaviour

It would've allowed me to enter (enter in terms of like with the terms and conditions stuff)

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2023-06-25 16:31
Why is it happening?
A. You didn’t read the docs properly.

How to fix it(without reading the docs)?
A. Use PlayCover 3.0.

**Comment by mochisoya** [comment] 2023-06-25 16:33
I actually did miss maam ^^ I've went through the whole thing multiple times while fixing this issue

**Comment by TheMoonThatRises** [comment] 2023-06-25 19:49
Duplicate of #741 and #877. Use the latest version of PlayCover (3.0.0).

**Closed as not planned by TheMoonThatRises** 2023-06-25 19:49 UTC
Labels: duplicate

**Comment by hien-101** [comment] 2024-12-27 02:56
I am on playcover 3.1.0 but i still encounter this bug, i've tried the steps on the docs 2 times but it still didn't work
