### ISSUE TITLE
[Bug]: After shutting down using version 3.0.0bate, the version reverts to 2.0.5

### ISSUE THREAD

**Issue by Patrickxi9** [PlayCover/PlayCover#1337] opened 2024-01-19 12:14 UTC
### Describe the bug

After downloading version 3.0.0, I could play it normally, but when I opened the software the next day, the game could not start normally. After checking, I found that the version had reverted to 2.0.5.

### Steps to reproduce

I didn't shut down the computer after quitting the game, and found that the version had rolled back the next day.

### Expected behaviour

I hope the current version will always be maintained.

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment] 2024-01-19 12:17
Press Command + , in playcover -> disable "automatically check for updates", and if it asks you to update PlayCover then click "skip this version"

**Comment by Patrickxi9** [comment] 2024-01-19 12:21
> 按 Command + ，在 PlayCover 中 -> 禁用“自动检查更新”，如果它要求您更新 PlayCover，则单击“跳过此版本”

I have turned off automatically checking for updates before, but it still rolls back to the version on its own.

**Comment by Hantetus** [comment] 2024-01-20 12:13
> ### Describe the bug
> After downloading version 3.0.0, I could play it normally, but when I opened the software the next day, the game could not start normally. After checking, I found that the version had reverted to 2.0.5.
> 
> ### Steps to reproduce
> I didn't shut down the computer after quitting the game, and found that the version had rolled back the next day.
> 
> ### Expected behaviour
> I hope the current version will always be maintained.
> 
> ### Crash log
> _No response_
> 
> ### What version of PlayCover are you using?
> 3.0.0 beta 2
> 
> ### What version of macOS are you using?
> Sonoma (macOS 14)
> 
> ### Issue Language
> * [x]  Yes my issue is written in English

same thing

**Comment by myatix** [comment] 2024-01-27 14:52
I am having the same issue as well!

**Comment by MEMORIEmusic** [comment] 2024-01-27 15:32
Disable automatic updates in PlayCover. Press command + k -> uncheck the tick box.

**Comment by TheMoonThatRises** [comment] 2024-02-26 03:11
Duplicate of #1299.

**Closed as not planned by TheMoonThatRises** 2024-02-26 03:11 UTC
Labels: bug

**Comment by akitiyashi** [comment] 2024-08-28 16:26
> Disable automatic updates in PlayCover. Press command + k -> uncheck the tick box.

in version 3.0.0 beta 2 i cant log in Genshin... what should i do? (i tried to install 3.0.0 latest update, but i cant play at all with it. genshin open only with 3.0.0 beta 2 version)
