### ISSUE TITLE
[Game Support]: 

### ISSUE THREAD

**Issue by PlanetDance19** [PlayCover/PlayCover#491] opened 2022-11-04 02:32 UTC
### App Store link

https://apps.apple.com/kr/app/goddess-of-victory-nikke/id1585915174

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

No response after starting the game
Device: M1 Max Macbook Pro 14"
![9F3E386A9DA53EE3640C56622ABBB274](https://user-images.githubusercontent.com/99587182/199872517-61ddfa7f-b654-48b3-a0d1-4686c06e0df0.jpg)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment] 2022-11-04 19:52
Nikke is known to have issues. Please update to PlayCover 2.0.0 and install **without** injecting PlayTools. The game should be playable on the servers labeled "test". More fixes may be coming soon.

**Comment by IsaacMarovitz** [comment] 2022-12-29 22:59
Duplicate of #489

**Closed as not planned by IsaacMarovitz** 2022-12-29 22:59 UTC
Labels: game-support

**Comment by PD19Anime** [comment] 2025-07-30 02:13
@IsaacMarovitz Could you please help me delete this issue? I’ve changed my account name, but I can still find this issue through Google using my old name.
