### ISSUE TITLE
[App Support]: Identity V

### ISSUE THREAD

**Issue by CZY0880** [PlayCover/PlayCover#1045] opened 2023-07-17 23:49 UTC
### App Store link

https://apps.apple.com/sg/app/identity-v/id1347780764?l=zh

### Current issues

- [ ] App fails to install
- [X] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [ ] Other

### More details

Apps fails to open 

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-12-19 19:44
Duplicate of #657.

**Closed as not planned by TheMoonThatRises** 2023-12-19 19:44 UTC
Labels: app-support
