### ISSUE TITLE
[App Support]: Google authenticator request login everytime when open

### ISSUE THREAD

**Issue by Gythiro** [PlayCover/PlayCover#1145] opened 2023-10-10 19:48 UTC
### App Store link

https://apps.apple.com/us/app/google-authenticator/id388497605

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

once you close the app, the next time u open it need do login again.

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2023-11-05 21:27
You need to have PlayTools injected into the app in order to keep the login information persistent. The issue with not being able to click elements on the screen can be fixed by disabling smart keymapping (the issue is also fixed in https://github.com/PlayCover/PlayTools/pull/131).

**Closed as completed by TheMoonThatRises** 2023-11-05 21:27 UTC
Labels: app-support
