### ISSUE TITLE
[Bug]: PlayCover_nightly_619安装com.tencent.jkchess_1.6.17_1028__und3fined -  - 2024-01-28 02-34-17时候出现权限不足

### ISSUE THREAD

**Issue by bysyc** [PlayCover/PlayCover#1356] opened 2024-01-27 18:44 UTC
### Describe the bug

xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/jkchess'
xattr: [Errno 13] Permission denied: '/var/folders/7f/

### Steps to reproduce

<img width="1280" alt="截屏2024-01-28 02 41 49" src="https://github.com/PlayCover/PlayCover/assets/117105462/5a7d0a01-c1ba-4192-84ba-7fcbb48cb204">

### Expected behaviour

<img width="1280" alt="截屏2024-01-28 02 41 49" src="https://github.com/PlayCover/PlayCover/assets/117105462/54423940-8450-4e94-838d-4c4a38f2174c">

### Crash log

```shell
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/jkchess'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/PlugIns/Notification.appex/Notification'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/GCloudCore.framework/GCloudCore'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/crosCurl.framework/crosCurl'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/CrashSight.framework/CrashSight'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/kgvmp_dy.framework/kgvmp_dy'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/tersafe.framework/tersafe'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/TDataMaster.framework/TDataMaster'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKWebView.framework/MSDKWebView'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/TDMIDFA.framework/TDMIDFA'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/Hippy.framework/Hippy'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKSensitivity.framework/MSDKSensitivity'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/tgpa_wrapper.framework/tgpa_wrapper'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKDns.framework/MSDKDns'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKTDM.framework/MSDKTDM'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/CrashSightCore.framework/CrashSightCore'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKSystem.framework/MSDKSystem'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/GCloud.framework/GCloud'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKLBS.framework/MSDKLBS'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/CrashSightAdapter.framework/CrashSightAdapter'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/PluginCrosCurl.framework/PluginCrosCurl'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/GRobot.framework/GRobot'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKCore.framework/MSDKCore'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/TDMASA.framework/TDMASA'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/MSDKAdapter.framework/MSDKAdapter'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/enq_transceiver_dy.framework/enq_transceiver_dy'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/GPM_dylib.framework/GPM_dylib'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/CrashSightPlugin.framework/CrashSightPlugin'
xattr: [Errno 13] Permission denied: '/var/folders/7f/pbd2nq5s2z99bbf70j186qy00000gn/T/TemporaryItems/NSIRD_PlayCover_fUduZU/Payload/jkchess.app/Frameworks/GVoice_dylib.framework/GVoice_dylib'
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by jiangboO0o** [comment] 2024-01-27 20:07
我在安装金铲铲之战的时候遇到了相同的问题，文件源是：https://decrypt.day/library
我的playcover版本是[3.0.0 Beta 2]
我的macOS版本是：14.3 (23D56)
但是在安装穿越火线时没有报错。

**Comment by Ihsan-Joe** [comment] 2024-01-28 04:55
I have the same problem:(

**Comment by xuanxuan88HDDD** [comment] 2024-01-28 05:22
> 我在安装金铲铲之战的时候遇到了相同的问题，文件源是：https://decrypt.day/library 我的playcover版本是[3.0.0 Beta 2] 我的macOS版本是：14.3 (23D56) 但是在安装穿越火线时没有报错。

安装源的问题 淘宝买的没什么问题
https://item.taobao.com/item.htm?id=723694045869

**Comment by wubixiaoyu** [comment] 2024-01-28 16:36
同样的问题 什么时候能解决啊

**Comment by TheMoonThatRises** [comment] 2024-01-29 00:11
Duplicate of #1353.

**Closed as not planned by TheMoonThatRises** 2024-01-29 00:11 UTC
Labels: bug
