### ISSUE TITLE
[Bug]: Black bars appear on left and right side when in full screen with a notch

### ISSUE THREAD

**Issue by JaceThings** [PlayCover/PlayCover#201] opened 2022-08-19 20:03 UTC
### What happened?

Updated Playcover to latest version, opened Genshin Impact, went to full screen, black bars appear on the left and right
<img width="2056" alt="No 004156@2x" src="https://user-images.githubusercontent.com/60551230/185698371-8fd797ac-6d8e-4109-97ac-6555a956a2b8.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZhichGaming** [comment] 2022-08-19 20:05
Did you check adaptive display? Right click on app, click app settings. 
<img width="804" alt="Screen Shot 2022-08-19 at 16 05 18" src="https://user-images.githubusercontent.com/93055907/185698779-408d1ba3-2aae-4df8-a45e-2135e09f97b9.png">

**Comment by Depal1** [comment] 2022-08-19 20:05
This is due to the aspect ration in 1080p. Change to enable auto window resize.

**Comment by JaceThings** [comment] 2022-08-19 20:11
auto window resize is enabled, same issue
 
 
<img width="641" alt="No 004157@2x" src="https://user-images.githubusercontent.com/60551230/185699642-f3a97229-80ea-471a-ad27-7cea5a14c33e.png">

**Comment by Depal1** [comment] 2022-08-19 20:30
Try untoggling and toggling "enable auto window resize". If it works after doing that, it is another issue.

**Comment by JaceThings** [comment] 2022-08-19 21:01
> Try untoggling and toggling "enable auto window resize". If it works after doing that, it is another issue.

already tried that, nothing happens

**Comment by Depal1** [comment] 2022-08-19 21:02
Are you able to provide steps to replicate this issue?

**Comment by Candygoblen123** [comment] 2022-08-19 21:08
wrong issue sorry

**Comment by JaceThings** [comment] 2022-08-19 21:31
> Are you able to provide steps to replicate this issue?

the steps are written in the original comment, update to 1.1.1, run Genshin and fullscreen.

**Comment by Depal1** [comment] 2022-08-19 21:35
> the steps are written in the original comment, update to 1.1.1, run Genshin and fullscreen.

When this is done the black bars appear, but it gets fixed by the following

> Try untoggling and toggling "enable auto window resize".

If the black bars are present by selecting either 1080p, 1440p or 4K, it is because of the aspect ratio.

**Comment by JoseMoreville** [comment] 2022-08-19 23:29
Try clearing game preferences

**Comment by JaceThings** [comment] 2022-08-19 23:52
> Try clearing game preferences

Tried this, didnt fix much


> Try untoggling and toggling "enable auto window resize".

turning this off then playing results in black bars on the top and bottom

Turning it back on results in the current black bars on right and left

**Comment by JoseMoreville** [comment] 2022-08-19 23:58
What's your screen size?

**Comment by JaceThings** [comment] 2022-08-20 00:04
> What's your screen size?

16.2-inch (diagonal) display;

 3456 by 2234

**Comment by JoseMoreville** [comment] 2022-08-20 01:12
It is the aspect ratio

**Comment by Depal1** [comment] 2022-08-20 01:25
@Soft-Bred We need more information. I infer you are using a Mac Book Pro with a notch. Am I right? Do you have any monitors plugged in to your Mac? Does this issue present itself when all the monitors are unplugged and 'auto window resize' is enabled?

**Comment by Depal1** [comment] 2022-08-20 01:28
![image](https://user-images.githubusercontent.com/47154119/185723986-6c48672c-2a23-490f-999e-e1f709e72cf4.png)
If the answer for the first to questions is yes, you should toggle `Scale to fit below built-in camera` in app info as shown in the image. That should fix the black bars. This is not exactly a PlayCover issue itself.

**Comment by JaceThings** [comment] 2022-08-20 11:58
>If the answer for the first to questions is yes, you should toggle `Scale to fit below built-in camera` in app info as shown in the image. That should fix the black bars. This is not exactly a PlayCover issue itself.

---

This toggle is already set to off and the bars persist
<img width="377" alt="No 004162@2x" src="https://user-images.githubusercontent.com/60551230/185744979-8f205cb4-1296-4762-be7d-15e771293bc7.png">

All of the settings shown before on playcover are the same as requested 
<img width="641" alt="No 004163@2x" src="https://user-images.githubusercontent.com/60551230/185745013-c84829ef-4f1e-433a-a132-2a6d9b463a1c.png">

No external monitors are plugged in.

Turning Enable auto window resize on and off does not solve any issues either.


The only this that I think would solve it is uninstalling the genshin ipa and re-downloading using the one that appeared in the playcover launcher after updating, though I was told this is nothing more than playcover no longer checking for duplicates. 
<img width="1012" alt="No 004164@2x" src="https://user-images.githubusercontent.com/60551230/185745147-d7ab0568-6f21-413e-9994-6fa9d4475dec.png">

**Comment by Depal1** [comment] 2022-08-20 13:20
The image I sent was misleading. `Scale to fit below built-in camera ` must be toggled **On**.

**Comment by JaceThings** [comment] 2022-08-20 13:24
if `Scale to fit below built-in camera` is turned on... this happens, which is arguably worse (adding black padding to all four sides).

![telegram-cloud-photo-size-4-5766884697970948738-y](https://user-images.githubusercontent.com/60551230/185748183-4afbaa41-edde-49e4-8f8b-a91c20f8d334.jpg)

**Comment by hayatofujii** [comment] 2022-08-20 19:43
Could reproduce. However, that behavior did only show up after I launched Genshin using PlayCover 1.1.1.

I usually start the game directly by pinning it to the Dock -- first run I did it using 1.0.7. Smells like a regression.

**Comment by JoseMoreville** [comment] 2022-08-20 20:08
> Could reproduce. However, that behavior did only show up after I launched Genshin using PlayCover 1.1.1.
> 
> I usually start the game directly by pinning it to the Dock -- first run I did it using 1.0.7. Smells like a regression.

Please avoid running the game directly

**Comment by JaceThings** [comment] 2022-08-21 14:17
> I usually start the game directly by pinning it to the Dock -- first run I did it using 1.0.7. Smells like a regression.

Regardless if I open the app through playcover, or through raycast, the issue persists
<img width="862" alt="No 004174@2x" src="https://user-images.githubusercontent.com/60551230/185795208-ed114923-ea49-4966-93ff-8e72d091886c.png">

**Comment by hayatofujii** [comment] 2022-08-22 12:31
> Please avoid running the game directly

That ought to be documented then.

**Comment by JoseMoreville** [comment] 2022-08-22 16:08
> > Please avoid running the game directly
> 
> That ought to be documented then.

It was stated by the original author many times, but I'll add it to documentation for future reference

**Comment by phillipmai5184** [comment] 2022-08-24 04:33
I have this same issue, I updated to play cover 1.1.1 and genshin 3.0, and my genshin wont run in 16:10 anymore. its either black bars on the top and bottom or left and right, or both. 

Maybe this is because you can choose which iPad model you want in the settings now? (I still dont know what the point of that is, since im on a MacBook Pro 14)
I really just want to run in proper full screen again. to me, this new playcover update is just an issue. Does anyone have any info for me? Is this like a new feature of playcover or am I actually facing a problem that should be fixed soon?

**Comment by Depal1** [comment] 2022-08-24 04:41
This is an issue due to the aspect ratio. In the meantime you can use today's nightly and set up a custom resolution for your game.

**Comment by phillipmai5184** [comment] 2022-08-24 04:50
what is that? how do I go about setting up a custom resolution?

**Comment by JoseMoreville** [comment] 2022-08-24 05:05
By default playcover will take the aspect ratio of your screen bounds, that's why it might fail with notch, even with fixed ratios it might look wrong on your screen because it might have a different size/AR, I suggest you to test different window resolutions using custom resolution feature Changing app settings on playcover launcher.

I'm gonna be honest with you guys, i don't own any macbook, so i can't reproduce the issue so i can fix it, if any developer here wants to address it, is welcome to do it :)

**Comment by kamui545** [comment] 2022-08-25 10:36
> what is that? how do I go about setting up a custom resolution?

Try to rollback to 1.0.7 for now, it worked for me on 14" M1.

**Closed as completed** 2022-08-25 23:35 UTC
Labels: bug
