### ISSUE TITLE
[Bug]: Game 'Wuthering Wave' 1.4 Version Failed to get patch list:Rename Error

### ISSUE THREAD

**Issue by Jeffchen8488** [PlayCover/PlayCover#1742] opened 2024-11-18 14:17 UTC
### Describe the bug

![WechatIMG2401](https://github.com/user-attachments/assets/37f9f2a9-9dbe-4db7-94b6-eece1820f94d)

### Steps to reproduce

Game 'Wuthering Wave' 1.4 Version Failed to get patch list:Rename Error

### Expected behaviour

Game 'Wuthering Wave' 1.4 Version Failed to get patch list:Rename Error

### Crash log

```shell
Game 'Wuthering Wave' 1.4 Version Failed to get patch list:Rename Error
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by qimubaibai** [comment] 2024-11-18 15:31
https://github.com/PlayCover/PlayCover/issues/1478

**Comment by TheMoonThatRises** [comment] 2024-12-03 08:24
Duplicate of #1478. Either follow the solution in the post or use the nightly build.

**Closed as not planned by TheMoonThatRises** 2024-12-03 08:24 UTC
Labels: bug
