### ISSUE TITLE
[Game Support]: [Snowbreak]How to disable the built-in key/ joystick controller 

### ISSUE THREAD

**Issue by ReoSaKo** [PlayCover/PlayCover#1709] opened 2024-10-06 07:07 UTC
### App Store link

It seems like when I using the keymapping,
it doesn’t fully work on it. The Snowbreak has some built-in keys itself and it cannot be disabled so I can’t run the keymapping smoothy.

### Current issues

- [ ] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Snowbreak 塵白禁域

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sequoia (macOS 15)

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment] 2024-10-07 15:21
Duplicate of #1526. I believe the best way to play Snowbreak is to use the keymapping support it already has. I have tried this and it works alright. If you believe that playing with the built-in keymapping is insufficient, please let me know and I can reopen this issue.

**Closed as not planned by TheMoonThatRises** 2024-10-07 15:21 UTC
Labels: game-support
